-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 17:58:03

items.Alchemy = {
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;1:1:5;0:1:0
    [5] = { -- Mists of Pandaria
        87872, -- Desecrated Oil
        83064, -- Spinefish
        79011, -- Fool's Cap
        79010, -- Snow Lily
        76141, -- Imperial Amethyst
        76140, -- Vermilion Onyx
        76139, -- Wild Jade
        76137, -- Alexandrite
        76136, -- Pandarian Garnet
        76135, -- Roguestone
        76134, -- Sunstone
        76133, -- Lapis Lazuli
        76130, -- Tiger Opal
        76061, -- Spirit of Harmony
        72238, -- Golden Lotus
        72237, -- Rain Poppy
        72235, -- Silkweed
        72234, -- Green Tea Leaf
        72096, -- Ghost Iron Bar
        72095, -- Trillium Bar
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;1:1:4;0:1:0
    [4] = { -- Cataclysm
        65893, -- Sands of Time
        65892, -- Pyrium-Laced Crystalline Vial
        58480, -- Truegold
        58142, -- Deathblood Venom
        58088, -- Flask of Titanic Strength
        58087, -- Flask of the Winds
        58086, -- Flask of the Draconic Mind
        58085, -- Flask of Steelskin
        56850, -- Deepstone Oil
        53065, -- Albino Cavefish
        52988, -- Whiptail
        52987, -- Twilight Jasmine
        52986, -- Heartblossom
        52985, -- Azshara's Veil
        52984, -- Stormvine
        52983, -- Cinderbloom
        52329, -- Volatile Life
        52328, -- Volatile Air
        52327, -- Volatile Earth
        52326, -- Volatile Water
        52325, -- Volatile Fire
        52186, -- Elementium Bar
        52182, -- Jasper
        52181, -- Hessonite
        52180, -- Nightstone
        52179, -- Alicite
        52178, -- Zephyrite
        52177, -- Carnelian
        51950, -- Pyrium Bar
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;1:1:3;0:1:0
    [3] = { -- Wrath of the Lich King
        44958, -- Ethereal Oil
        41814, -- Glassfin Minnow
        40199, -- Pygmy Suckerfish
        40195, -- Pygmy Oil
        37921, -- Deadnettle
        37705, -- Crystallized Water
        37704, -- Crystallized Life
        37703, -- Crystallized Shadow
        37702, -- Crystallized Fire
        37701, -- Crystallized Earth
        36933, -- Forest Emerald
        36932, -- Dark Jade
        36930, -- Monarch Topaz
        36929, -- Huge Citrine
        36927, -- Twilight Opal
        36924, -- Sky Sapphire
        36923, -- Chalcedony
        36921, -- Autumn's Glow
        36918, -- Scarlet Ruby
        36917, -- Bloodstone
        36913, -- Saronite Bar
        36908, -- Frost Lotus
        36907, -- Talandra's Rose
        36906, -- Icethorn
        36905, -- Lichbloom
        36904, -- Tiger Lily
        36903, -- Adder's Tongue
        36901, -- Goldclover
        36860, -- Eternal Fire
        35627, -- Eternal Shadow
        35625, -- Eternal Life
        35624, -- Eternal Earth
        35623, -- Eternal Air
        35622, -- Eternal Water
        33448, -- Runic Mana Potion
        33447, -- Runic Healing Potion
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;1:1:2;0:1:0
    [2] = { -- Burning Crusade
        30183, -- Nether Vortex
        25868, -- Skyfire Diamond
        25867, -- Earthstorm Diamond
        23782, -- Fel Iron Casing
        23571, -- Primal Might
        23117, -- Azure Moonstone
        23112, -- Golden Draenite
        23107, -- Shadow Draenite
        23079, -- Deep Peridot
        23077, -- Blood Garnet
        22794, -- Fel Lotus
        22793, -- Mana Thistle
        22792, -- Nightmare Vine
        22791, -- Netherbloom
        22790, -- Ancient Lichen
        22789, -- Terocone
        22787, -- Ragveil
        22786, -- Dreaming Glory
        22785, -- Felweed
        22578, -- Mote of Water
        22574, -- Mote of Fire
        22573, -- Mote of Earth
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        21929, -- Flame Spessarite
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;1:1:1;0:1:0
    [1] = { -- Vanilla
        19943, -- Massive Mojo
        13468, -- Black Lotus
        13467, -- Icecap
        13466, -- Sorrowmoss
        13465, -- Mountain Silversage
        13464, -- Golden Sansam
        13463, -- Dreamfoil
        13423, -- Stonescale Oil
        13422, -- Stonescale Eel
        12938, -- Blood of Heroes
        12808, -- Essence of Undeath
        12804, -- Powerful Mojo
        12803, -- Living Essence
        12363, -- Arcane Crystal
        12359, -- Thorium Bar
        11176, -- Dream Dust
        10620, -- Thorium Ore
        10286, -- Heart of the Wild
        9262, -- Black Vitriol
        9260, -- Volatile Rum
        8846, -- Gromsblood
        8845, -- Ghost Mushroom
        8839, -- Blindweed
        8838, -- Sungrass
        8831, -- Purple Lotus
        8153, -- Wildvine
        7972, -- Ichor of Undeath
        7082, -- Essence of Air
        7080, -- Essence of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7070, -- Elemental Water
        7068, -- Elemental Fire
        7067, -- Elemental Earth
        6522, -- Deviate Fish
        6371, -- Fire Oil
        6370, -- Blackmouth Oil
        6359, -- Firefin Snapper
        6358, -- Oily Blackmouth
        5637, -- Large Fang
        5635, -- Sharp Claw
        4625, -- Firebloom
        4402, -- Small Flame Sac
        4342, -- Purple Dye
        3860, -- Mithril Bar
        3858, -- Mithril Ore
        3824, -- Shadow Oil
        3821, -- Goldthorn
        3820, -- Stranglekelp
        3819, -- Dragon's Teeth
        3818, -- Fadeleaf
        3575, -- Iron Bar
        3371, -- Crystal Vial
        3369, -- Grave Moss
        3358, -- Khadgar's Whisker
        3357, -- Liferoot
        3356, -- Kingsblood
        3355, -- Wild Steelbloom
        3164, -- Discolored Worg Heart
        2453, -- Bruiseweed
        2452, -- Swiftthistle
        2450, -- Briarthorn
        2449, -- Earthroot
        2447, -- Peacebloom
        1288, -- Large Venom Sac
        785, -- Mageroyal
        765, -- Silverleaf
        118, -- Minor Healing Potion
    },
}
