-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 17:55:50

items.Cooking = {
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;3:1:5;0:1:0
    [5] = { -- Mists of Pandaria
        102543, -- Aged Mogu'shan Cheese
        102542, -- Ancient Pandaren Spices
        102541, -- Aged Balsamic Vinegar
        102540, -- Fresh Mangos
        102539, -- Fresh Strawberries
        102538, -- Fresh Shao-Tien Rice
        102537, -- Fresh Silkfeather Hawk Eggs
        102536, -- Fresh Lushroom
        85585, -- Red Beans
        85584, -- Silkworm Pupa
        85583, -- Needle Mushrooms
        85506, -- Viseclaw Meat
        79250, -- Fresh Pomfruit
        79246, -- Delicate Blossom Petals
        75038, -- Mad Brewer's Breakfast
        75037, -- Jade Witch Brew
        75026, -- Ginseng Tea
        75014, -- Raw Crocolisk Belly
        74866, -- Golden Carp
        74865, -- Krasarang Paddlefish
        74864, -- Reef Octopus
        74863, -- Jewel Danio
        74861, -- Tiger Gourami
        74860, -- Redbelly Mandarin
        74859, -- Emperor Salmon
        74857, -- Giant Mantis Shrimp
        74856, -- Jade Lungfish
        74854, -- Instant Noodles
        74853, -- 100 Year Soy Sauce
        74852, -- Yak Milk
        74851, -- Rice
        74850, -- White Turnip
        74849, -- Pink Turnip
        74848, -- Striped Melon
        74847, -- Jade Squash
        74846, -- Witchberries
        74845, -- Ginseng
        74844, -- Red Blossom Leek
        74843, -- Scallions
        74842, -- Mogu Pumpkin
        74841, -- Juicycrunch Carrot
        74840, -- Green Cabbage
        74839, -- Wildfowl Breast
        74838, -- Raw Crab Meat
        74837, -- Raw Turtle Meat
        74834, -- Mushan Ribs
        74833, -- Raw Tiger Steak
        74832, -- Barley
        74662, -- Rice Flour
        74661, -- Black Pepper
        74660, -- Pandaren Peach
        74659, -- Farm Chicken
        74656, -- Chun Tian Spring Rolls
        74655, -- Twin Fish Platter
        74654, -- Wildfowl Roast
        74653, -- Steamed Crab Surprise
        74652, -- Fire Spirit Salmon
        74651, -- Shrimp Dumplings
        74650, -- Mogu Fish Stew
        74649, -- Braised Turtle
        74648, -- Sea Mist Rice Noodles
        74647, -- Valley Stir Fry
        74646, -- Black Pepper Ribs and Shrimp
        74645, -- Eternal Blossom Fish
        74644, -- Swirling Mist Soup
        74643, -- Sauteed Carrots
        74642, -- Charbroiled Tiger Steak
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;3:1:4;0:1:0
    [4] = { -- Cataclysm
        67229, -- Stag Flank
        62791, -- Blood Shrimp
        62786, -- Cocoa Beans
        62785, -- Delicate Wing
        62784, -- Crocolisk Tail
        62783, -- Basilisk "Liver"
        62782, -- Dragon Flank
        62781, -- Giant Turtle Tongue
        62780, -- Snake Eye
        62779, -- Monstrous Claw
        62778, -- Toughened Flesh
        60838, -- Mysterious Fortune Card
        58278, -- Tropical Sunfruit
        58265, -- Highland Pomegranate
        53072, -- Deepsea Sagefish
        53071, -- Algaefin Rockfish
        53070, -- Fathom Eel
        53069, -- Murglesnout
        53068, -- Lavascale Catfish
        53067, -- Striped Lurker
        53066, -- Blackbelly Mudfish
        53064, -- Highland Guppy
        53063, -- Mountain Trout
        53062, -- Sharptooth
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;3:1:3;0:1:0
    [3] = { -- Wrath of the Lich King
        46797, -- Mulgore Sweet Potato
        46796, -- Ripe Tirisfal Pumpkin
        46793, -- Tangy Southfury Cranberries
        46784, -- Ripe Elwynn Pumpkin
        44855, -- Teldrassil Sweet Potato
        44854, -- Tangy Wetland Cranberries
        44853, -- Honey
        44835, -- Autumnal Herbs
        44834, -- Wild Turkey
        43501, -- Northern Egg
        43013, -- Chilled Meat
        43012, -- Rhino Meat
        43011, -- Worg Haunch
        43010, -- Worm Meat
        43009, -- Shoveltusk Flank
        43007, -- Northern Spices
        41813, -- Nettlefish
        41812, -- Barrelhead Goby
        41810, -- Fangtooth Herring
        41809, -- Glacial Salmon
        41808, -- Bonescale Snapper
        41807, -- Dragonfin Angelfish
        41806, -- Musselback Sculpin
        41805, -- Borean Man O' War
        41803, -- Rockfin Grouper
        41802, -- Imperial Manta Ray
        41801, -- Moonglow Cuttlefish
        41800, -- Deep Sea Monsterbelly
        36782, -- Succulent Clam Meat
        35949, -- Tundra Berries
        35948, -- Savory Snowplum
        34736, -- Chunk o' Mammoth
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;3:1:2;0:1:0
    [2] = { -- Burning Crusade
        35562, -- Bear Flank
        34412, -- Sparkling Apple Cider
        33824, -- Crescent-Tail Skullfish
        33823, -- Bloodfin Catfish
        31671, -- Serpent Flesh
        31670, -- Raptor Ribs
        30817, -- Simple Flour
        30816, -- Spice Bread
        27682, -- Talbuk Venison
        27681, -- Warped Flesh
        27678, -- Clefthoof Meat
        27677, -- Chunk o' Basilisk
        27674, -- Ravager Flesh
        27671, -- Buzzard Meat
        27669, -- Bat Flesh
        27668, -- Lynx Meat
        27516, -- Enormous Barbed Gill Trout
        27515, -- Huge Spotted Feltail
        27439, -- Furious Crawdad
        27438, -- Golden Darter
        27437, -- Icefin Bluefish
        27435, -- Figluster's Mudfish
        27429, -- Zangarian Sporefish
        27425, -- Spotted Feltail
        27422, -- Barbed Gill Trout
        24477, -- Jaggal Clam Meat
        23676, -- Moongraze Stag Tenderloin
        22644, -- Crunchy Spider Leg
        22577, -- Mote of Shadow
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;3:1:1;0:1:0
    [1] = { -- Vanilla
        21153, -- Raw Greater Sagefish
        21071, -- Raw Sagefish
        21024, -- Chimaerok Tenderloin
        20424, -- Sandworm Meat
        18255, -- Runn Tum Tuber
        17196, -- Holiday Spirits
        17194, -- Holiday Spices
        13893, -- Large Raw Mightfish
        13889, -- Raw Whitescale Salmon
        13888, -- Darkclaw Lobster
        13760, -- Raw Sunscale Salmon
        13759, -- Raw Nightfin Snapper
        13758, -- Raw Redgill
        13757, -- Lightning Eel
        13756, -- Raw Summer Bass
        13755, -- Winter Squid
        13754, -- Raw Glossy Mightfish
        12808, -- Essence of Undeath
        12223, -- Meaty Bat Wing
        12208, -- Tender Wolf Meat
        12207, -- Giant Egg
        12206, -- Tender Crab Meat
        12205, -- White Spider Meat
        12204, -- Heavy Kodo Meat
        12203, -- Red Wolf Meat
        12202, -- Tiger Meat
        12184, -- Raptor Flesh
        12037, -- Mystery Meat
        9260, -- Volatile Rum
        9061, -- Goblin Rocket Fuel
        8365, -- Raw Mithril Head Trout
        8150, -- Deeprock Salt
        7974, -- Zesty Clam Meat
        6889, -- Small Egg
        6522, -- Deviate Fish
        6362, -- Raw Rockscale Cod
        6361, -- Raw Rainbow Fin Albacore
        6317, -- Raw Loch Frenzy
        6308, -- Raw Bristle Whisker Catfish
        6303, -- Raw Slitherskin Mackerel
        6291, -- Raw Brilliant Smallfish
        6289, -- Raw Longjaw Mud Snapper
        5504, -- Tangy Clam Meat
        5503, -- Clam Meat
        5471, -- Stag Meat
        5470, -- Thunder Lizard Tail
        5469, -- Strider Meat
        5468, -- Soft Frenzy Flesh
        5467, -- Kodo Meat
        5466, -- Scorpid Stinger
        5465, -- Small Spider Leg
        5051, -- Dig Rat
        4655, -- Giant Clam Meat
        4603, -- Raw Spotted Yellowtail
        4537, -- Tel'Abim Banana
        4402, -- Small Flame Sac
        3821, -- Goldthorn
        3731, -- Lion Meat
        3730, -- Big Bear Meat
        3712, -- Turtle Meat
        3685, -- Raptor Egg
        3667, -- Tender Crocolisk Meat
        3404, -- Buzzard Wing
        3173, -- Bear Meat
        2924, -- Crocolisk Meat
        2886, -- Crag Boar Rib
        2678, -- Mild Spices
        2677, -- Boar Ribs
        2675, -- Crawler Claw
        2674, -- Crawler Meat
        2673, -- Coyote Meat
        2672, -- Stringy Wolf Meat
        2596, -- Skin of Dwarven Stout
        2595, -- Jug of Badlands Bourbon
        2594, -- Flagon of Dwarven Honeymead
        2593, -- Flask of Stormwind Tawny
        2452, -- Swiftthistle
        2251, -- Gooey Spider Leg
        1468, -- Murloc Fin
        1179, -- Ice Cold Milk
        1080, -- Tough Condor Meat
        1015, -- Lean Wolf Flank
        785, -- Mageroyal
        769, -- Chunk of Boar Meat
        723, -- Goretusk Liver
        159, -- Refreshing Spring Water
    },
}
