-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 18:10:54

items.Elemental = {
    -- https://www.wowhead.com/mop-classic/items/trade-goods/elemental?filter=166:194;5:1;0:1
    [5] = { -- Mists of Pandaria
        90637, -- Splinter of Hate
        90636, -- Essence of Hatred
        89112, -- Mote of Harmony
        80816, -- Spirit of the Season
        76061, -- Spirit of Harmony
        76060, -- Spirit of Autumn
        76059, -- Spirit of Spring
        76058, -- Spirit of Winter
        76057, -- Spirit of Summer
    },
    -- https://www.wowhead.com/mop-classic/items/trade-goods/elemental?filter=166:194;4:1;0:1
    [4] = { -- Cataclysm
        54464, -- Random Volatile Element
        52337, -- Lifegiving Seed
        52335, -- Stormlord's Favor
        52333, -- Azsharaen Sphere
        52332, -- Spark of Ragnaros
        52330, -- Volatile Shadow
        52329, -- Volatile Life
        52328, -- Volatile Air
        52327, -- Volatile Earth
        52326, -- Volatile Water
        52325, -- Volatile Fire
    },
    -- https://www.wowhead.com/mop-classic/items/trade-goods/elemental?filter=166:194;3:1;0:1
    [3] = { -- Wrath of the Lich King
        40248, -- Eternal Might
        37705, -- Crystallized Water
        37704, -- Crystallized Life
        37703, -- Crystallized Shadow
        37702, -- Crystallized Fire
        37701, -- Crystallized Earth
        37700, -- Crystallized Air
        36860, -- Eternal Fire
        35627, -- Eternal Shadow
        35625, -- Eternal Life
        35624, -- Eternal Earth
        35623, -- Eternal Air
        35622, -- Eternal Water
        35621, -- Eternal Power
    },
    -- https://www.wowhead.com/mop-classic/items/trade-goods/elemental?filter=166:194;2:1;0:1
    [2] = { -- Burning Crusade
        23571, -- Primal Might
        22578, -- Mote of Water
        22577, -- Mote of Shadow
        22576, -- Mote of Mana
        22575, -- Mote of Life
        22574, -- Mote of Fire
        22573, -- Mote of Earth
        22572, -- Mote of Air
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
    },
    -- https://www.wowhead.com/mop-classic/items/trade-goods/elemental?filter=166:194;1:1;0:1
    [1] = { -- Vanilla
        12808, -- Essence of Undeath
        12803, -- Living Essence
        10286, -- Heart of the Wild
        7972, -- Ichor of Undeath
        7082, -- Essence of Air
        7081, -- Breath of Wind
        7080, -- Essence of Water
        7079, -- Globe of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7075, -- Core of Earth
        7070, -- Elemental Water
        7069, -- Elemental Air
        7068, -- Elemental Fire
        7067, -- Elemental Earth
    },
}
