-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 18:01:00

items.Enchanting = {
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;4:1:5;0:1:0
    [5] = { -- Mists of Pandaria
        76138, -- River's Heart
        74250, -- Mysterious Essence
        74249, -- Spirit Dust
        74248, -- Sha Crystal
        74247, -- Ethereal Shard
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;4:1:4;0:1:0
    [4] = { -- Cataclysm
        58094, -- Elixir of Impossible Accuracy
        52722, -- Maelstrom Crystal
        52721, -- Heavenly Shard
        52719, -- Greater Celestial Essence
        52718, -- Lesser Celestial Essence
        52555, -- Hypnotic Dust
        52329, -- Volatile Life
        52328, -- Volatile Air
        52327, -- Volatile Earth
        52326, -- Volatile Water
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;4:1:3;0:1:0
    [3] = { -- Wrath of the Lich King
        44958, -- Ethereal Oil
        41163, -- Titanium Bar
        37705, -- Crystallized Water
        37663, -- Titansteel Bar
        36918, -- Scarlet Ruby
        36860, -- Eternal Fire
        35625, -- Eternal Life
        35624, -- Eternal Earth
        35623, -- Eternal Air
        34057, -- Abyss Crystal
        34056, -- Lesser Cosmic Essence
        34055, -- Greater Cosmic Essence
        34054, -- Infinite Dust
        34052, -- Dream Shard
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;4:1:2;0:1:0
    [2] = { -- Burning Crusade
        23571, -- Primal Might
        23427, -- Eternium Ore
        22824, -- Elixir of Major Strength
        22794, -- Fel Lotus
        22792, -- Nightmare Vine
        22791, -- Netherbloom
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        22450, -- Void Crystal
        22449, -- Large Prismatic Shard
        22448, -- Small Prismatic Shard
        22447, -- Lesser Planar Essence
        22446, -- Greater Planar Essence
        22445, -- Arcane Dust
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;4:1:1;0:1:0
    [1] = { -- Vanilla
        20725, -- Nexus Crystal
        16204, -- Illusion Dust
        16203, -- Greater Eternal Essence
        16202, -- Lesser Eternal Essence
        14344, -- Large Brilliant Shard
        14343, -- Small Brilliant Shard
        13926, -- Golden Pearl
        13467, -- Icecap
        13446, -- Major Healing Potion
        13444, -- Major Mana Potion
        12811, -- Righteous Orb
        12808, -- Essence of Undeath
        12803, -- Living Essence
        12359, -- Thorium Bar
        11291, -- Star Wood
        11178, -- Large Radiant Shard
        11177, -- Small Radiant Shard
        11176, -- Dream Dust
        11175, -- Greater Nether Essence
        11174, -- Lesser Nether Essence
        11139, -- Large Glowing Shard
        11138, -- Small Glowing Shard
        11137, -- Vision Dust
        11135, -- Greater Mystic Essence
        11134, -- Lesser Mystic Essence
        11084, -- Large Glimmering Shard
        11083, -- Soul Dust
        11082, -- Greater Astral Essence
        10998, -- Lesser Astral Essence
        10978, -- Small Glimmering Shard
        10940, -- Strange Dust
        10939, -- Greater Magic Essence
        10938, -- Lesser Magic Essence
        9224, -- Elixir of Demonslaying
        8838, -- Sungrass
        8831, -- Purple Lotus
        8170, -- Rugged Leather
        8153, -- Wildvine
        7909, -- Aquamarine
        7392, -- Green Whelp Scale
        7082, -- Essence of Air
        7080, -- Essence of Water
        7078, -- Essence of Fire
        7076, -- Essence of Earth
        7067, -- Elemental Earth
        6370, -- Blackmouth Oil
        6037, -- Truesilver Bar
        5637, -- Large Fang
        4625, -- Firebloom
        4470, -- Simple Wood
        3819, -- Dragon's Teeth
        3371, -- Crystal Vial
        3356, -- Kingsblood
        2772, -- Iron Ore
    },
}
