-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 18:17:40

items.Herbalism = {
    -- https://www.wowhead.com/mop-classic/items?filter=70:194:166;1:1:5;0:1:0
    [5] = { -- Mists of Pandaria
        103643, -- Dew of Eternal Morning
        97624, -- Desecrated Herb Pod
        97623, -- Fool's Cap Spores
        97622, -- Snow Lily Petal
        97621, -- Silkweed Stem
        97620, -- Rain Poppy Petal
        97619, -- Torn Green Tea Leaf
        89641, -- Water Spirit
        89640, -- Life Spirit
        89639, -- Desecrated Herb
        81210, -- Shimmering Pollen
        81198, -- Animate Leaf
        79011, -- Fool's Cap
        79010, -- Snow Lily
        72238, -- Golden Lotus
        72237, -- Rain Poppy
        72235, -- Silkweed
        72234, -- Green Tea Leaf
    },
    -- https://www.wowhead.com/mop-classic/items?filter=70:194:166;1:1:4;0:1:0
    [4] = { -- Cataclysm
        69772, -- Vibrant Petals
        67357, -- Wriggling Worm
        63122, -- Lifegiving Seed
        54630, -- Half-Wilted Flower
        54628, -- Pointy Thorn
        54627, -- Wilted Flower
        52988, -- Whiptail
        52987, -- Twilight Jasmine
        52986, -- Heartblossom
        52985, -- Azshara's Veil
        52984, -- Stormvine
        52983, -- Cinderbloom
        52329, -- Volatile Life
    },
    -- https://www.wowhead.com/mop-classic/items?filter=70:194:166;1:1:3;0:1:0
    [3] = { -- Wrath of the Lich King
        39970, -- Fire Leaf
        39516, -- Frosty Mushroom
        37921, -- Deadnettle
        37704, -- Crystallized Life
        36908, -- Frost Lotus
        36907, -- Talandra's Rose
        36906, -- Icethorn
        36905, -- Lichbloom
        36904, -- Tiger Lily
        36903, -- Adder's Tongue
        36901, -- Goldclover
        35947, -- Sparkling Frostcap
        33452, -- Honey-Spiced Lichen
    },
    -- https://www.wowhead.com/mop-classic/items?filter=70:194:166;1:1:2;0:1:0
    [2] = { -- Burning Crusade
        35229, -- Nether Residue
        32506, -- Netherwing Egg
        32468, -- Netherdust Pollen
        29453, -- Sporeggar Mushroom
        27859, -- Zangar Caps
        25813, -- Small Mushroom
        24401, -- Unidentified Plant Parts
        23988, -- Mutated Vine
        23987, -- Mutated Petal
        23331, -- Broken Vine
        23330, -- Wilted Petal
        22797, -- Nightmare Seed
        22795, -- Fel Blossom
        22794, -- Fel Lotus
        22793, -- Mana Thistle
        22792, -- Nightmare Vine
        22791, -- Netherbloom
        22790, -- Ancient Lichen
        22789, -- Terocone
        22788, -- Flame Cap
        22787, -- Ragveil
        22786, -- Dreaming Glory
        22785, -- Felweed
        22710, -- Bloodthistle
        22576, -- Mote of Mana
        22575, -- Mote of Life
    },
    -- https://www.wowhead.com/mop-classic/items?filter=70:194:166;1:1:1;0:1:0
    [1] = { -- Vanilla
        19726, -- Bloodvine
        18223, -- Serrated Petal
        18222, -- Thorny Vine
        13468, -- Black Lotus
        13467, -- Icecap
        13466, -- Sorrowmoss
        13465, -- Mountain Silversage
        13464, -- Golden Sansam
        13463, -- Dreamfoil
        11514, -- Fel Creep
        8846, -- Gromsblood
        8845, -- Ghost Mushroom
        8839, -- Blindweed
        8838, -- Sungrass
        8836, -- Arthas' Tears
        8831, -- Purple Lotus
        8153, -- Wildvine
        5056, -- Root Sample
        4625, -- Firebloom
        3821, -- Goldthorn
        3820, -- Stranglekelp
        3819, -- Dragon's Teeth
        3818, -- Fadeleaf
        3369, -- Grave Moss
        3358, -- Khadgar's Whisker
        3357, -- Liferoot
        3356, -- Kingsblood
        3355, -- Wild Steelbloom
        2453, -- Bruiseweed
        2452, -- Swiftthistle
        2450, -- Briarthorn
        2449, -- Earthroot
        2447, -- Peacebloom
        785, -- Mageroyal
        765, -- Silverleaf
    },
}
