-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 18:08:12

items.Inscription = {
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;15:1:5;0:1:0
    [5] = { -- Mists of Pandaria
        79731, -- Scroll of Wisdom
        79255, -- Starlight Ink
        79254, -- Ink of Dreams
        79253, -- Misty Pigment
        79251, -- Shadow Pigment
        76061, -- Spirit of Harmony
        72237, -- Rain Poppy
        72096, -- Ghost Iron Bar
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;15:1:4;0:1:0
    [4] = { -- Cataclysm
        67348, -- Bleached Jawbone
        67335, -- Silver Charm Bracelet
        67319, -- Preserved Ogre Eye
        62323, -- Deathwing Scale Fragment
        61981, -- Inferno Ink
        61980, -- Burning Embers
        61979, -- Ashen Pigment
        61978, -- Blackfallow Ink
        52329, -- Volatile Life
        52328, -- Volatile Air
        52327, -- Volatile Earth
        52326, -- Volatile Water
        52325, -- Volatile Fire
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;15:1:3;0:1:0
    [3] = { -- Wrath of the Lich King
        43127, -- Snowfall Ink
        43126, -- Ink of the Sea
        43125, -- Darkflame Ink
        43124, -- Ethereal Ink
        43123, -- Ink of the Sky
        43122, -- Shimmering Ink
        43121, -- Fiery Ink
        43120, -- Celestial Ink
        43119, -- Royal Ink
        43118, -- Jadefire Ink
        43117, -- Dawnstar Ink
        43116, -- Lion's Ink
        43115, -- Hunter's Ink
        43109, -- Icy Pigment
        43108, -- Ebon Pigment
        43107, -- Sapphire Pigment
        43106, -- Ruby Pigment
        43105, -- Indigo Pigment
        43104, -- Burnt Pigment
        43103, -- Verdant Pigment
        43102, -- Frozen Orb
        39774, -- Midnight Ink
        39469, -- Moonglow Ink
        39354, -- Light Parchment
        39343, -- Azure Pigment
        39342, -- Nether Pigment
        39341, -- Silvery Pigment
        39340, -- Violet Pigment
        39339, -- Emerald Pigment
        39338, -- Golden Pigment
        39334, -- Dusky Pigment
        39151, -- Alabaster Pigment
        37101, -- Ivory Ink
        35627, -- Eternal Shadow
        35625, -- Eternal Life
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;15:1:2;0:1:0
    [2] = { -- Burning Crusade
        21886, -- Primal Life
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;15:1:1;0:1:0
    [1] = { -- Vanilla
    },
}
