-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 18:05:55

items.Jewelcrafting = {
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;2:1:5;0:1:0
    [5] = { -- Mists of Pandaria
        102218, -- Spirit of War
        98717, -- Balanced Trillium Ingot
        94289, -- Haunting Spirit
        94111, -- Lightning Steel Ingot
        80433, -- Blood Spirit
        77468, -- High-Explosive Gunpowder
        77467, -- Ghost Iron Bolts
        76061, -- Spirit of Harmony
        72104, -- Living Steel
        72096, -- Ghost Iron Bar
        72095, -- Trillium Bar
        72093, -- Kyparite
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;2:1:4;0:1:0
    [4] = { -- Cataclysm
        71998, -- Essence of Destruction
        69237, -- Living Ember
        65365, -- Folded Obsidium
        58480, -- Truegold
        56516, -- Heavy Savage Leather
        54849, -- Obsidium Bar
        53039, -- Hardened Elementium Bar
        52329, -- Volatile Life
        52327, -- Volatile Earth
        52326, -- Volatile Water
        52325, -- Volatile Fire
        52193, -- Ember Topaz
        52191, -- Ocean Sapphire
        52190, -- Inferno Ruby
        52186, -- Elementium Bar
        52182, -- Jasper
        52178, -- Zephyrite
        52078, -- Chaos Orb
        51950, -- Pyrium Bar
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;2:1:3;0:1:0
    [3] = { -- Wrath of the Lich King
        49908, -- Primordial Saronite
        47556, -- Crusader Orb
        45087, -- Runed Orb
        43102, -- Frozen Orb
        41163, -- Titanium Bar
        37705, -- Crystallized Water
        37703, -- Crystallized Shadow
        37702, -- Crystallized Fire
        37701, -- Crystallized Earth
        37700, -- Crystallized Air
        37663, -- Titansteel Bar
        36925, -- Majestic Zircon
        36916, -- Cobalt Bar
        36913, -- Saronite Bar
        36860, -- Eternal Fire
        35627, -- Eternal Shadow
        35625, -- Eternal Life
        35624, -- Eternal Earth
        35623, -- Eternal Air
        35622, -- Eternal Water
        34054, -- Infinite Dust
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;2:1:2;0:1:0
    [2] = { -- Burning Crusade
        35128, -- Hardened Khorium
        34664, -- Sunmote
        32428, -- Heart of Darkness
        30183, -- Nether Vortex
        27503, -- Scroll of Strength V
        23573, -- Hardened Adamantite Bar
        23572, -- Primal Nether
        23571, -- Primal Might
        23449, -- Khorium Bar
        23448, -- Felsteel Bar
        23447, -- Eternium Bar
        23446, -- Adamantite Bar
        23445, -- Fel Iron Bar
        22831, -- Elixir of Major Agility
        22824, -- Elixir of Major Strength
        22573, -- Mote of Earth
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        22450, -- Void Crystal
        22449, -- Large Prismatic Shard
        22445, -- Arcane Dust
        21887, -- Knothide Leather
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
        21877, -- Netherweave Cloth
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;2:1:1;0:1:0
    [1] = { -- Vanilla
        22682, -- Frozen Rune
        22203, -- Large Obsidian Shard
        22202, -- Small Obsidian Shard
        20725, -- Nexus Crystal
        20520, -- Dark Rune
        18567, -- Elemental Flux
        17203, -- Sulfuron Ingot
        17012, -- Core Leather
        17011, -- Lava Core
        17010, -- Fiery Core
        15417, -- Devilsaur Leather
        14047, -- Runecloth
        13512, -- Flask of Supreme Power
        13510, -- Flask of the Titans
        12811, -- Righteous Orb
        12810, -- Enchanted Leather
        12809, -- Guardian Stone
        12808, -- Essence of Undeath
        12804, -- Powerful Mojo
        12803, -- Living Essence
        12800, -- Azerothian Diamond
        12799, -- Large Opal
        12662, -- Demonic Rune
        12655, -- Enchanted Thorium Bar
        12644, -- Dense Grinding Stone
        12365, -- Dense Stone
        12364, -- Huge Emerald
        12361, -- Blue Sapphire
        12360, -- Arcanite Bar
        12359, -- Thorium Bar
        11754, -- Black Diamond
        11382, -- Blood of the Mountain
        11371, -- Dark Iron Bar
        8170, -- Rugged Leather
        8153, -- Wildvine
        7972, -- Ichor of Undeath
        7971, -- Black Pearl
        7966, -- Solid Grinding Stone
        7912, -- Solid Stone
        7910, -- Star Ruby
        7909, -- Aquamarine
        7081, -- Breath of Wind
        7080, -- Essence of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7075, -- Core of Earth
        7070, -- Elemental Water
        7069, -- Elemental Air
        7068, -- Elemental Fire
        7067, -- Elemental Earth
        6037, -- Truesilver Bar
        5637, -- Large Fang
        5635, -- Sharp Claw
        5500, -- Iridescent Pearl
        5498, -- Small Lustrous Pearl
        4338, -- Mageweave Cloth
        4306, -- Silk Cloth
        4304, -- Thick Leather
        4234, -- Heavy Leather
        3864, -- Citrine
        3860, -- Mithril Bar
        3859, -- Steel Bar
        3829, -- Frost Oil
        3824, -- Shadow Oil
        3823, -- Lesser Invisibility Potion
        3577, -- Gold Bar
        3575, -- Iron Bar
        3486, -- Heavy Grinding Stone
        3478, -- Coarse Grinding Stone
        3470, -- Rough Grinding Stone
        3466, -- Strong Flux
        3391, -- Elixir of Ogre's Strength
        2880, -- Weak Flux
        2842, -- Silver Bar
        2841, -- Bronze Bar
        2840, -- Copper Bar
        2838, -- Heavy Stone
        2836, -- Coarse Stone
        2835, -- Rough Stone
        2605, -- Green Dye
        2592, -- Wool Cloth
        2589, -- Linen Cloth
        2459, -- Swiftness Potion
        2321, -- Fine Thread
        2319, -- Medium Leather
        2318, -- Light Leather
        1705, -- Lesser Moonstone
        1529, -- Jade
        1210, -- Shadowgem
        1206, -- Moss Agate
        818, -- Tigerseye
        774, -- Malachite
    },
}
