-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 18:13:46

items.Mining = {
    -- https://www.wowhead.com/mop-classic/items?filter=86:194:166;9:1:5;0:1:0
    [5] = { -- Mists of Pandaria
        72096, -- Ghost Iron Bar
        72095, -- Trillium Bar
    },
    -- https://www.wowhead.com/mop-classic/items?filter=86:194:166;9:1:4;0:1:0
    [4] = { -- Cataclysm
        54849, -- Obsidium Bar
        53039, -- Hardened Elementium Bar
        52186, -- Elementium Bar
        51950, -- Pyrium Bar
    },
    -- https://www.wowhead.com/mop-classic/items?filter=86:194:166;9:1:3;0:1:0
    [3] = { -- Wrath of the Lich King
        41163, -- Titanium Bar
        37663, -- Titansteel Bar
        36916, -- Cobalt Bar
        36913, -- Saronite Bar
    },
    -- https://www.wowhead.com/mop-classic/items?filter=86:194:166;9:1:2;0:1:0
    [2] = { -- Burning Crusade
        35128, -- Hardened Khorium
        23573, -- Hardened Adamantite Bar
        23449, -- Khorium Bar
        23448, -- Felsteel Bar
        23447, -- Eternium Bar
        23446, -- Adamantite Bar
        23445, -- Fel Iron Bar
        22574, -- Mote of Fire
        22573, -- Mote of Earth
    },
    -- https://www.wowhead.com/mop-classic/items?filter=86:194:166;9:1:1;0:1:0
    [1] = { -- Vanilla
        17771, -- Enchanted Elementium Bar
        12655, -- Enchanted Thorium Bar
        12359, -- Thorium Bar
        11371, -- Dark Iron Bar
        6037, -- Truesilver Bar
        3860, -- Mithril Bar
        3859, -- Steel Bar
        3577, -- Gold Bar
        3576, -- Tin Bar
        3575, -- Iron Bar
        2842, -- Silver Bar
        2841, -- Bronze Bar
        2840, -- Copper Bar
    },
}
