-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 17:48:23

items.Tailoring = {
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;10:1:5;0:1:0
    [5] = { -- Mists of Pandaria
        102218, -- Spirit of War
        98619, -- Celestial Cloth
        94289, -- Haunting Spirit
        82447, -- Imperial Silk
        82441, -- Bolt of Windwool Cloth
        80433, -- Blood Spirit
        76061, -- Spirit of Harmony
        72988, -- Windwool Cloth
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;10:1:4;0:1:0
    [4] = { -- Cataclysm
        71998, -- Essence of Destruction
        69237, -- Living Ember
        54440, -- Dreamcloth
        53643, -- Bolt of Embersilk Cloth
        53010, -- Embersilk Cloth
        52555, -- Hypnotic Dust
        52329, -- Volatile Life
        52328, -- Volatile Air
        52327, -- Volatile Earth
        52326, -- Volatile Water
        52325, -- Volatile Fire
        52078, -- Chaos Orb
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;10:1:3;0:1:0
    [3] = { -- Wrath of the Lich King
        49908, -- Primordial Saronite
        47556, -- Crusader Orb
        45087, -- Runed Orb
        43102, -- Frozen Orb
        42253, -- Iceweb Spider Silk
        41595, -- Spellweave
        41594, -- Moonshroud
        41593, -- Ebonweave
        41511, -- Bolt of Imbued Frostweave
        41510, -- Bolt of Frostweave
        38426, -- Eternium Thread
        38425, -- Heavy Borean Leather
        37704, -- Crystallized Life
        37702, -- Crystallized Fire
        37701, -- Crystallized Earth
        36934, -- Eye of Zul
        36930, -- Monarch Topaz
        36925, -- Majestic Zircon
        36922, -- King's Amber
        36919, -- Cardinal Ruby
        36908, -- Frost Lotus
        36860, -- Eternal Fire
        36784, -- Siren's Tear
        36783, -- Northsea Pearl
        35627, -- Eternal Shadow
        35625, -- Eternal Life
        35624, -- Eternal Earth
        35622, -- Eternal Water
        34055, -- Greater Cosmic Essence
        34054, -- Infinite Dust
        34052, -- Dream Shard
        33470, -- Frostweave Cloth
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;10:1:2;0:1:0
    [2] = { -- Burning Crusade
        34664, -- Sunmote
        32428, -- Heart of Darkness
        30183, -- Nether Vortex
        24272, -- Shadowcloth
        24271, -- Spellcloth
        23572, -- Primal Nether
        23571, -- Primal Might
        23112, -- Golden Draenite
        22794, -- Fel Lotus
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        22450, -- Void Crystal
        22446, -- Greater Planar Essence
        22445, -- Arcane Dust
        21887, -- Knothide Leather
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
        21882, -- Soul Essence
        21881, -- Netherweb Spider Silk
        21877, -- Netherweave Cloth
        21845, -- Primal Mooncloth
        21844, -- Bolt of Soulcloth
        21842, -- Bolt of Imbued Netherweave
        21840, -- Bolt of Netherweave
    },
    -- https://www.wowhead.com/mop-classic/items?filter=87:194:166;10:1:1;0:1:0
    [1] = { -- Vanilla
        22682, -- Frozen Rune
        20520, -- Dark Rune
        18240, -- Ogre Tannin
        17012, -- Core Leather
        17011, -- Lava Core
        17010, -- Fiery Core
        16203, -- Greater Eternal Essence
        14344, -- Large Brilliant Shard
        14342, -- Mooncloth
        14341, -- Rune Thread
        14256, -- Felcloth
        14227, -- Ironweb Spider Silk
        14048, -- Bolt of Runecloth
        14047, -- Runecloth
        13926, -- Golden Pearl
        13468, -- Black Lotus
        12811, -- Righteous Orb
        12810, -- Enchanted Leather
        12809, -- Guardian Stone
        12808, -- Essence of Undeath
        12804, -- Powerful Mojo
        12803, -- Living Essence
        12800, -- Azerothian Diamond
        12662, -- Demonic Rune
        12364, -- Huge Emerald
        12360, -- Arcanite Bar
        11176, -- Dream Dust
        11137, -- Vision Dust
        10290, -- Pink Dye
        10286, -- Heart of the Wild
        10285, -- Shadow Silk
        9210, -- Ghost Dye
        8831, -- Purple Lotus
        8343, -- Heavy Silken Thread
        8170, -- Rugged Leather
        8153, -- Wildvine
        7972, -- Ichor of Undeath
        7971, -- Black Pearl
        7910, -- Star Ruby
        7082, -- Essence of Air
        7080, -- Essence of Water
        7079, -- Globe of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7072, -- Naga Scale
        7071, -- Iron Buckle
        7070, -- Elemental Water
        7069, -- Elemental Air
        7068, -- Elemental Fire
        7067, -- Elemental Earth
        6371, -- Fire Oil
        6261, -- Orange Dye
        6260, -- Blue Dye
        6048, -- Shadow Protection Potion
        6037, -- Truesilver Bar
        5500, -- Iridescent Pearl
        5498, -- Small Lustrous Pearl
        4625, -- Firebloom
        4342, -- Purple Dye
        4341, -- Yellow Dye
        4340, -- Gray Dye
        4339, -- Bolt of Mageweave
        4338, -- Mageweave Cloth
        4337, -- Thick Spider's Silk
        4306, -- Silk Cloth
        4305, -- Bolt of Silk Cloth
        4304, -- Thick Leather
        4291, -- Silken Thread
        4234, -- Heavy Leather
        3864, -- Citrine
        3829, -- Frost Oil
        3827, -- Mana Potion
        3824, -- Shadow Oil
        3577, -- Gold Bar
        3383, -- Elixir of Wisdom
        3182, -- Spider's Silk
        2997, -- Bolt of Woolen Cloth
        2996, -- Bolt of Linen Cloth
        2605, -- Green Dye
        2604, -- Red Dye
        2592, -- Wool Cloth
        2589, -- Linen Cloth
        2325, -- Black Dye
        2324, -- Bleach
        2321, -- Fine Thread
        2320, -- Coarse Thread
        2319, -- Medium Leather
        2318, -- Light Leather
        1529, -- Jade
        929, -- Healing Potion
    },
}
