-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 20:25:05

items.Alchemy = {
    -- https://www.wowhead.com/tbc/items?filter=87:194:166;1:1:2;0:1:0
    [2] = { -- Burning Crusade
        30183, -- Nether Vortex
        25868, -- Skyfire Diamond
        25867, -- Earthstorm Diamond
        23782, -- Fel Iron Casing
        23571, -- Primal Might
        23117, -- Azure Moonstone
        23112, -- Golden Draenite
        23107, -- Shadow Draenite
        23079, -- Deep Peridot
        23077, -- Blood Garnet
        22794, -- Fel Lotus
        22793, -- Mana Thistle
        22792, -- Nightmare Vine
        22791, -- Netherbloom
        22790, -- Ancient Lichen
        22789, -- Terocone
        22787, -- Ragveil
        22786, -- Dreaming Glory
        22785, -- Felweed
        22578, -- Mote of Water
        22574, -- Mote of Fire
        22573, -- Mote of Earth
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        21929, -- Flame Spessarite
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
    },
    -- https://www.wowhead.com/tbc/items?filter=87:194:166;1:1:1;0:1:0
    [1] = { -- Vanilla
        19943, -- Massive Mojo
        18256, -- Imbued Vial
        13468, -- Black Lotus
        13467, -- Icecap
        13466, -- Plaguebloom
        13465, -- Mountain Silversage
        13464, -- Golden Sansam
        13463, -- Dreamfoil
        13423, -- Stonescale Oil
        13422, -- Stonescale Eel
        12938, -- Blood of Heroes
        12808, -- Essence of Undeath
        12804, -- Powerful Mojo
        12803, -- Living Essence
        12363, -- Arcane Crystal
        12359, -- Thorium Bar
        11176, -- Dream Dust
        10620, -- Thorium Ore
        10286, -- Heart of the Wild
        9262, -- Black Vitriol
        9260, -- Volatile Rum
        8925, -- Crystal Vial
        8846, -- Gromsblood
        8845, -- Ghost Mushroom
        8839, -- Blindweed
        8838, -- Sungrass
        8836, -- Arthas' Tears
        8831, -- Purple Lotus
        8153, -- Wildvine
        7972, -- Ichor of Undeath
        7082, -- Essence of Air
        7080, -- Essence of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7070, -- Elemental Water
        7068, -- Elemental Fire
        7067, -- Elemental Earth
        6522, -- Deviate Fish
        6371, -- Fire Oil
        6370, -- Blackmouth Oil
        6359, -- Firefin Snapper
        6358, -- Oily Blackmouth
        5637, -- Large Fang
        5635, -- Sharp Claw
        4625, -- Firebloom
        4402, -- Small Flame Sac
        4342, -- Purple Dye
        3860, -- Mithril Bar
        3858, -- Mithril Ore
        3824, -- Shadow Oil
        3821, -- Goldthorn
        3820, -- Stranglekelp
        3819, -- Wintersbite
        3818, -- Fadeleaf
        3575, -- Iron Bar
        3372, -- Leaded Vial
        3371, -- Empty Vial
        3369, -- Grave Moss
        3358, -- Khadgar's Whisker
        3357, -- Liferoot
        3356, -- Kingsblood
        3355, -- Wild Steelbloom
        3164, -- Discolored Worg Heart
        2453, -- Bruiseweed
        2452, -- Swiftthistle
        2450, -- Briarthorn
        2449, -- Earthroot
        2447, -- Peacebloom
        1288, -- Large Venom Sac
        785, -- Mageroyal
        765, -- Silverleaf
        118, -- Minor Healing Potion
    },
}
