-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 20:25:13

items.Cooking = {
    -- https://www.wowhead.com/tbc/items?filter=87:194:166;3:1:2;0:1:0
    [2] = { -- Burning Crusade
        35562, -- Bear Flank
        34412, -- Sparkling Apple Cider
        33824, -- Crescent-Tail Skullfish
        33823, -- Bloodfin Catfish
        31671, -- Serpent Flesh
        31670, -- Raptor Ribs
        30817, -- Simple Flour
        27682, -- Talbuk Venison
        27681, -- Warped Flesh
        27678, -- Clefthoof Meat
        27677, -- Chunk o' Basilisk
        27676, -- Strange Spores
        27674, -- Ravager Flesh
        27671, -- Buzzard Meat
        27669, -- Bat Flesh
        27668, -- Lynx Meat
        27516, -- Enormous Barbed Gill Trout
        27515, -- Huge Spotted Feltail
        27439, -- Furious Crawdad
        27438, -- Golden Darter
        27437, -- Icefin Bluefish
        27435, -- Figluster's Mudfish
        27429, -- Zangarian Sporefish
        27425, -- Spotted Feltail
        27422, -- Barbed Gill Trout
        24477, -- Jaggal Clam Meat
        23676, -- Moongraze Stag Tenderloin
        22644, -- Crunchy Spider Leg
    },
    -- https://www.wowhead.com/tbc/items?filter=87:194:166;3:1:1;0:1:0
    [1] = { -- Vanilla
        21153, -- Raw Greater Sagefish
        21071, -- Raw Sagefish
        21024, -- Chimaerok Tenderloin
        20424, -- Sandworm Meat
        18255, -- Runn Tum Tuber
        17196, -- Holiday Spirits
        17194, -- Holiday Spices
        13893, -- Large Raw Mightfish
        13889, -- Raw Whitescale Salmon
        13888, -- Darkclaw Lobster
        13760, -- Raw Sunscale Salmon
        13759, -- Raw Nightfin Snapper
        13758, -- Raw Redgill
        13757, -- Lightning Eel
        13756, -- Raw Summer Bass
        13755, -- Winter Squid
        13754, -- Raw Glossy Mightfish
        12223, -- Meaty Bat Wing
        12208, -- Tender Wolf Meat
        12207, -- Giant Egg
        12206, -- Tender Crab Meat
        12205, -- White Spider Meat
        12204, -- Heavy Kodo Meat
        12203, -- Red Wolf Meat
        12202, -- Tiger Meat
        12184, -- Raptor Flesh
        12037, -- Mystery Meat
        9061, -- Goblin Rocket Fuel
        8365, -- Raw Mithril Head Trout
        8150, -- Deeprock Salt
        7974, -- Zesty Clam Meat
        6889, -- Small Egg
        6522, -- Deviate Fish
        6362, -- Raw Rockscale Cod
        6361, -- Raw Rainbow Fin Albacore
        6317, -- Raw Loch Frenzy
        6308, -- Raw Bristle Whisker Catfish
        6303, -- Raw Slitherskin Mackerel
        6291, -- Raw Brilliant Smallfish
        6289, -- Raw Longjaw Mud Snapper
        5504, -- Tangy Clam Meat
        5503, -- Clam Meat
        5471, -- Stag Meat
        5470, -- Thunder Lizard Tail
        5469, -- Strider Meat
        5468, -- Soft Frenzy Flesh
        5467, -- Kodo Meat
        5466, -- Scorpid Stinger
        5465, -- Small Spider Leg
        5051, -- Dig Rat
        4655, -- Giant Clam Meat
        4603, -- Raw Spotted Yellowtail
        4539, -- Goldenbark Apple
        4536, -- Shiny Red Apple
        4470, -- Simple Wood
        4402, -- Small Flame Sac
        3821, -- Goldthorn
        3731, -- Lion Meat
        3730, -- Big Bear Meat
        3713, -- Soothing Spices
        3712, -- Turtle Meat
        3685, -- Raptor Egg
        3667, -- Tender Crocolisk Meat
        3404, -- Buzzard Wing
        3174, -- Spider Ichor
        3173, -- Bear Meat
        3172, -- Boar Intestines
        2924, -- Crocolisk Meat
        2894, -- Rhapsody Malt
        2886, -- Crag Boar Rib
        2692, -- Hot Spices
        2678, -- Mild Spices
        2677, -- Boar Ribs
        2675, -- Crawler Claw
        2674, -- Crawler Meat
        2673, -- Coyote Meat
        2672, -- Stringy Wolf Meat
        2665, -- Stormwind Seasoning Herbs
        2596, -- Skin of Dwarven Stout
        2594, -- Flagon of Dwarven Honeymead
        2593, -- Flask of Stormwind Tawny
        2452, -- Swiftthistle
        2251, -- Gooey Spider Leg
        1468, -- Murloc Fin
        1179, -- Ice Cold Milk
        1081, -- Crisp Spider Meat
        1080, -- Tough Condor Meat
        1015, -- Lean Wolf Flank
        785, -- Mageroyal
        769, -- Chunk of Boar Meat
        731, -- Goretusk Snout
        730, -- Murloc Eye
        729, -- Stringy Vulture Meat
        723, -- Goretusk Liver
        159, -- Refreshing Spring Water
    },
}
