-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 20:25:17

items.Elemental = {
    -- https://www.wowhead.com/tbc/items/trade-goods/elemental?filter=166:194;2:1;0:1
    [2] = { -- Burning Crusade
        23571, -- Primal Might
        22578, -- Mote of Water
        22577, -- Mote of Shadow
        22576, -- Mote of Mana
        22575, -- Mote of Life
        22574, -- Mote of Fire
        22573, -- Mote of Earth
        22572, -- Mote of Air
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
    },
    -- https://www.wowhead.com/tbc/items/trade-goods/elemental?filter=166:194;1:1;0:1
    [1] = { -- Vanilla
        12808, -- Essence of Undeath
        12803, -- Living Essence
        10286, -- Heart of the Wild
        7972, -- Ichor of Undeath
        7082, -- Essence of Air
        7081, -- Breath of Wind
        7080, -- Essence of Water
        7079, -- Globe of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7075, -- Core of Earth
        7070, -- Elemental Water
        7069, -- Elemental Air
        7068, -- Elemental Fire
        7067, -- Elemental Earth
    },
}
