-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 20:25:21

items.Enchanting = {
    -- https://www.wowhead.com/tbc/items?filter=87:194:166;4:1:2;0:1:0
    [2] = { -- Burning Crusade
        23572, -- Primal Nether
        23571, -- Primal Might
        23427, -- Eternium Ore
        22824, -- Elixir of Major Strength
        22794, -- Fel Lotus
        22792, -- Nightmare Vine
        22791, -- Netherbloom
        22578, -- Mote of Water
        22574, -- Mote of Fire
        22573, -- Mote of Earth
        22572, -- Mote of Air
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        22450, -- Void Crystal
        22449, -- Large Prismatic Shard
        22448, -- Small Prismatic Shard
        22447, -- Lesser Planar Essence
        22446, -- Greater Planar Essence
        22445, -- Arcane Dust
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
    },
    -- https://www.wowhead.com/tbc/items?filter=87:194:166;4:1:1;0:1:0
    [1] = { -- Vanilla
        20725, -- Nexus Crystal
        18256, -- Imbued Vial
        17035, -- Stranglethorn Seed
        17034, -- Maple Seed
        16204, -- Illusion Dust
        16203, -- Greater Eternal Essence
        16202, -- Lesser Eternal Essence
        14344, -- Large Brilliant Shard
        14343, -- Small Brilliant Shard
        13926, -- Golden Pearl
        13467, -- Icecap
        13446, -- Major Healing Potion
        13444, -- Major Mana Potion
        12811, -- Righteous Orb
        12808, -- Essence of Undeath
        12803, -- Living Essence
        12359, -- Thorium Bar
        11382, -- Blood of the Mountain
        11291, -- Star Wood
        11178, -- Large Radiant Shard
        11177, -- Small Radiant Shard
        11176, -- Dream Dust
        11175, -- Greater Nether Essence
        11174, -- Lesser Nether Essence
        11139, -- Large Glowing Shard
        11138, -- Small Glowing Shard
        11137, -- Vision Dust
        11135, -- Greater Mystic Essence
        11134, -- Lesser Mystic Essence
        11084, -- Large Glimmering Shard
        11083, -- Soul Dust
        11082, -- Greater Astral Essence
        10998, -- Lesser Astral Essence
        10978, -- Small Glimmering Shard
        10940, -- Strange Dust
        10939, -- Greater Magic Essence
        10938, -- Lesser Magic Essence
        9224, -- Elixir of Demonslaying
        8925, -- Crystal Vial
        8838, -- Sungrass
        8831, -- Purple Lotus
        8170, -- Rugged Leather
        8153, -- Wildvine
        7972, -- Ichor of Undeath
        7971, -- Black Pearl
        7909, -- Aquamarine
        7392, -- Green Whelp Scale
        7082, -- Essence of Air
        7081, -- Breath of Wind
        7080, -- Essence of Water
        7079, -- Globe of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7075, -- Core of Earth
        7068, -- Elemental Fire
        7067, -- Elemental Earth
        6371, -- Fire Oil
        6370, -- Blackmouth Oil
        6048, -- Shadow Protection Potion
        6037, -- Truesilver Bar
        5637, -- Large Fang
        5500, -- Iridescent Pearl
        4625, -- Firebloom
        4470, -- Simple Wood
        3829, -- Frost Oil
        3819, -- Wintersbite
        3372, -- Leaded Vial
        3371, -- Empty Vial
        3356, -- Kingsblood
        2772, -- Iron Ore
    },
}
