-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 20:25:25

items.Engineering = {
    -- https://www.wowhead.com/tbc/items?filter=87:194:166;5:1:2;0:1:0
    [2] = { -- Burning Crusade
        35128, -- Hardened Khorium
        32423, -- Icy Blasting Primers
        24272, -- Shadowcloth
        24271, -- Spellcloth
        23826, -- The Bigger One
        23819, -- Elemental Seaforium Charge
        23793, -- Heavy Knothide Leather
        23787, -- Felsteel Stabilizer
        23786, -- Khorium Power Core
        23785, -- Hardened Adamantite Tube
        23784, -- Adamantite Frame
        23783, -- Handful of Fel Iron Bolts
        23782, -- Fel Iron Casing
        23781, -- Elemental Blasting Powder
        23573, -- Hardened Adamantite Bar
        23572, -- Primal Nether
        23571, -- Primal Might
        23449, -- Khorium Bar
        23448, -- Felsteel Bar
        23446, -- Adamantite Bar
        23445, -- Fel Iron Bar
        23441, -- Nightseye
        23440, -- Dawnstone
        23439, -- Noble Topaz
        23438, -- Star of Elune
        23437, -- Talasite
        23436, -- Living Ruby
        23112, -- Golden Draenite
        23079, -- Deep Peridot
        23077, -- Blood Garnet
        22832, -- Super Mana Potion
        22829, -- Super Healing Potion
        22574, -- Mote of Fire
        22573, -- Mote of Earth
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        22449, -- Large Prismatic Shard
        22448, -- Small Prismatic Shard
        22445, -- Arcane Dust
        21929, -- Flame Spessarite
        21887, -- Knothide Leather
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
        21877, -- Netherweave Cloth
        21840, -- Bolt of Netherweave
        20816, -- Delicate Copper Wire
    },
    -- https://www.wowhead.com/tbc/items?filter=87:194:166;5:1:1;0:1:0
    [1] = { -- Vanilla
        19774, -- Souldarite
        19726, -- Bloodvine
        18631, -- Truesilver Transformer
        17202, -- Snowball
        17020, -- Arcane Powder
        17011, -- Lava Core
        17010, -- Fiery Core
        16006, -- Delicate Arcanite Converter
        16000, -- Thorium Tube
        15994, -- Thorium Widget
        15992, -- Dense Blasting Powder
        15407, -- Cured Rugged Hide
        14227, -- Ironweb Spider Silk
        14047, -- Runecloth
        13467, -- Icecap
        12810, -- Enchanted Leather
        12808, -- Essence of Undeath
        12804, -- Powerful Mojo
        12803, -- Living Essence
        12800, -- Azerothian Diamond
        12799, -- Large Opal
        12655, -- Enchanted Thorium Bar
        12365, -- Dense Stone
        12364, -- Huge Emerald
        12361, -- Blue Sapphire
        12360, -- Arcanite Bar
        12359, -- Thorium Bar
        11371, -- Dark Iron Bar
        11291, -- Star Wood
        10648, -- Blank Parchment
        10647, -- Engineer's Ink
        10592, -- Catseye Elixir
        10586, -- The Big One
        10561, -- Mithril Casing
        10560, -- Unstable Trigger
        10559, -- Mithril Tube
        10558, -- Gold Power Core
        10546, -- Deadly Scope
        10507, -- Solid Dynamite
        10505, -- Solid Blasting Powder
        10286, -- Heart of the Wild
        10285, -- Shadow Silk
        9061, -- Goblin Rocket Fuel
        9060, -- Inlaid Mithril Cylinder
        8170, -- Rugged Leather
        8153, -- Wildvine
        8151, -- Flask of Mojo
        8150, -- Deeprock Salt
        7972, -- Ichor of Undeath
        7912, -- Solid Stone
        7910, -- Star Ruby
        7909, -- Aquamarine
        7191, -- Fused Wiring
        7082, -- Essence of Air
        7080, -- Essence of Water
        7079, -- Globe of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7075, -- Core of Earth
        7069, -- Elemental Air
        7068, -- Elemental Fire
        7067, -- Elemental Earth
        6530, -- Nightcrawlers
        6037, -- Truesilver Bar
        4611, -- Blue Pearl
        4470, -- Simple Wood
        4407, -- Accurate Scope
        4404, -- Silver Contact
        4402, -- Small Flame Sac
        4400, -- Heavy Stock
        4399, -- Wooden Stock
        4394, -- Big Iron Bomb
        4389, -- Gyrochronatom
        4387, -- Iron Strut
        4382, -- Bronze Framework
        4377, -- Heavy Blasting Powder
        4375, -- Whirring Bronze Gizmo
        4371, -- Bronze Tube
        4364, -- Coarse Blasting Powder
        4363, -- Copper Modulator
        4361, -- Copper Tube
        4359, -- Handful of Copper Bolts
        4357, -- Rough Blasting Powder
        4342, -- Purple Dye
        4339, -- Bolt of Mageweave
        4338, -- Mageweave Cloth
        4337, -- Thick Spider's Silk
        4306, -- Silk Cloth
        4304, -- Thick Leather
        4234, -- Heavy Leather
        3864, -- Citrine
        3860, -- Mithril Bar
        3859, -- Steel Bar
        3829, -- Frost Oil
        3577, -- Gold Bar
        3575, -- Iron Bar
        2880, -- Weak Flux
        2842, -- Silver Bar
        2841, -- Bronze Bar
        2840, -- Copper Bar
        2838, -- Heavy Stone
        2836, -- Coarse Stone
        2835, -- Rough Stone
        2605, -- Green Dye
        2592, -- Wool Cloth
        2589, -- Linen Cloth
        2319, -- Medium Leather
        2318, -- Light Leather
        1705, -- Lesser Moonstone
        1529, -- Jade
        1210, -- Shadowgem
        1206, -- Moss Agate
        818, -- Tigerseye
        814, -- Flask of Oil
        774, -- Malachite
        159, -- Refreshing Spring Water
    },
}
