-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 20:25:29

items.Herbalism = {
    -- https://www.wowhead.com/tbc/items?filter=70:194:166;1:1:2;0:1:0
    [2] = { -- Burning Crusade
        35229, -- Nether Residue
        32506, -- Netherwing Egg
        32468, -- Netherdust Pollen
        29453, -- Sporeggar Mushroom
        27859, -- Zangar Caps
        25813, -- Small Mushroom
        24401, -- Unidentified Plant Parts
        22797, -- Nightmare Seed
        22795, -- Fel Blossom
        22794, -- Fel Lotus
        22793, -- Mana Thistle
        22792, -- Nightmare Vine
        22791, -- Netherbloom
        22790, -- Ancient Lichen
        22789, -- Terocone
        22788, -- Flame Cap
        22787, -- Ragveil
        22786, -- Dreaming Glory
        22785, -- Felweed
        22710, -- Bloodthistle
        22576, -- Mote of Mana
        22575, -- Mote of Life
    },
    -- https://www.wowhead.com/tbc/items?filter=70:194:166;1:1:1;0:1:0
    [1] = { -- Vanilla
        19726, -- Bloodvine
        13468, -- Black Lotus
        13467, -- Icecap
        13466, -- Plaguebloom
        13465, -- Mountain Silversage
        13464, -- Golden Sansam
        13463, -- Dreamfoil
        11514, -- Fel Creep
        8846, -- Gromsblood
        8845, -- Ghost Mushroom
        8839, -- Blindweed
        8838, -- Sungrass
        8836, -- Arthas' Tears
        8831, -- Purple Lotus
        8153, -- Wildvine
        5056, -- Root Sample
        4625, -- Firebloom
        3821, -- Goldthorn
        3820, -- Stranglekelp
        3819, -- Wintersbite
        3818, -- Fadeleaf
        3369, -- Grave Moss
        3358, -- Khadgar's Whisker
        3357, -- Liferoot
        3356, -- Kingsblood
        3355, -- Wild Steelbloom
        2453, -- Bruiseweed
        2452, -- Swiftthistle
        2450, -- Briarthorn
        2449, -- Earthroot
        2447, -- Peacebloom
        785, -- Mageroyal
        765, -- Silverleaf
    },
}
