-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 20:25:33

items.Leatherworking = {
    -- https://www.wowhead.com/tbc/items?filter=87:194:166;8:1:2;0:1:0
    [2] = { -- Burning Crusade
        34664, -- Sunmote
        32428, -- Heart of Darkness
        30183, -- Nether Vortex
        29548, -- Nether Dragonscales
        29547, -- Wind Scales
        29539, -- Cobra Scales
        25719, -- Arakkoa Feather
        25708, -- Thick Clefthoof Leather
        25707, -- Fel Hide
        25700, -- Fel Scales
        25699, -- Crystal Infused Leather
        25649, -- Knothide Leather Scraps
        23793, -- Heavy Knothide Leather
        23572, -- Primal Nether
        23571, -- Primal Might
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        22450, -- Void Crystal
        22448, -- Small Prismatic Shard
        22445, -- Arcane Dust
        21887, -- Knothide Leather
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
        21844, -- Bolt of Soulcloth
    },
    -- https://www.wowhead.com/tbc/items?filter=87:194:166;8:1:1;0:1:0
    [1] = { -- Vanilla
        22682, -- Frozen Rune
        20501, -- Heavy Silithid Carapace
        20500, -- Light Silithid Carapace
        20498, -- Silithid Chitin
        20381, -- Dreamscale
        19768, -- Primal Tiger Leather
        19767, -- Primal Bat Leather
        19726, -- Bloodvine
        18512, -- Larval Acid
        18240, -- Ogre Tannin
        17056, -- Light Feather
        17012, -- Core Leather
        17011, -- Lava Core
        17010, -- Fiery Core
        15423, -- Chimera Leather
        15422, -- Frostsaber Leather
        15420, -- Ironfeather
        15419, -- Warbear Leather
        15417, -- Devilsaur Leather
        15416, -- Black Dragonscale
        15415, -- Blue Dragonscale
        15414, -- Red Dragonscale
        15412, -- Green Dragonscale
        15410, -- Scale of Onyxia
        15409, -- Refined Deeprock Salt
        15408, -- Heavy Scorpid Scale
        15407, -- Cured Rugged Hide
        14342, -- Mooncloth
        14341, -- Rune Thread
        14256, -- Felcloth
        14227, -- Ironweb Spider Silk
        14048, -- Bolt of Runecloth
        14047, -- Runecloth
        12810, -- Enchanted Leather
        12809, -- Guardian Stone
        12804, -- Powerful Mojo
        12803, -- Living Essence
        12753, -- Skin of Shadow
        12607, -- Brilliant Chromatic Scale
        11754, -- Black Diamond
        8951, -- Elixir of Greater Defense
        8949, -- Elixir of Agility
        8368, -- Thick Wolfhide
        8343, -- Heavy Silken Thread
        8172, -- Cured Thick Hide
        8171, -- Rugged Hide
        8170, -- Rugged Leather
        8169, -- Thick Hide
        8168, -- Jet Black Feather
        8167, -- Turtle Scale
        8165, -- Worn Dragonscale
        8154, -- Scorpid Scale
        8153, -- Wildvine
        8152, -- Flask of Big Mojo
        8151, -- Flask of Mojo
        8150, -- Deeprock Salt
        8146, -- Wicked Claw
        7971, -- Black Pearl
        7428, -- Shadowcat Hide
        7392, -- Green Whelp Scale
        7287, -- Red Whelp Scale
        7286, -- Black Whelp Scale
        7082, -- Essence of Air
        7081, -- Breath of Wind
        7080, -- Essence of Water
        7079, -- Globe of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7075, -- Core of Earth
        7071, -- Iron Buckle
        7070, -- Elemental Water
        7067, -- Elemental Earth
        6471, -- Perfect Deviate Scale
        6470, -- Deviate Scale
        5785, -- Thick Murloc Scale
        5784, -- Slimy Murloc Scale
        5637, -- Large Fang
        5633, -- Great Rage Potion
        5500, -- Iridescent Pearl
        5498, -- Small Lustrous Pearl
        5373, -- Lucky Charm
        5116, -- Long Tail Feather
        5082, -- Thin Kodo Leather
        4461, -- Raptor Hide
        4342, -- Purple Dye
        4340, -- Gray Dye
        4338, -- Mageweave Cloth
        4337, -- Thick Spider's Silk
        4305, -- Bolt of Silk Cloth
        4304, -- Thick Leather
        4291, -- Silken Thread
        4289, -- Salt
        4236, -- Cured Heavy Hide
        4235, -- Heavy Hide
        4234, -- Heavy Leather
        4233, -- Cured Medium Hide
        4232, -- Medium Hide
        4231, -- Cured Light Hide
        4096, -- Coarse Gorilla Hair
        3864, -- Citrine
        3824, -- Shadow Oil
        3390, -- Elixir of Lesser Agility
        3389, -- Elixir of Defense
        3383, -- Elixir of Wisdom
        3356, -- Kingsblood
        3182, -- Spider's Silk
        2997, -- Bolt of Woolen Cloth
        2934, -- Ruined Leather Scraps
        2840, -- Copper Bar
        2605, -- Green Dye
        2604, -- Red Dye
        2459, -- Swiftness Potion
        2457, -- Elixir of Minor Agility
        2325, -- Black Dye
        2324, -- Bleach
        2321, -- Fine Thread
        2320, -- Coarse Thread
        2319, -- Medium Leather
        2318, -- Light Leather
        1529, -- Jade
        1210, -- Shadowgem
        1206, -- Moss Agate
        783, -- Light Hide
    },
}
