-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 20:25:45

items.Mining = {
    -- https://www.wowhead.com/tbc/items?filter=73:194:166;1:1:2;0:1:0
    [2] = { -- Burning Crusade
        35229, -- Nether Residue
        34907, -- Shattered Gem Fragments
        32506, -- Netherwing Egg
        32464, -- Nethercite Ore
        32249, -- Seaspray Emerald
        32231, -- Pyrestone
        32230, -- Shadowsong Amethyst
        32229, -- Lionseye
        32228, -- Empyrean Sapphire
        32227, -- Crimson Spinel
        24189, -- Crystalline Fragments
        23441, -- Nightseye
        23440, -- Dawnstone
        23439, -- Noble Topaz
        23438, -- Star of Elune
        23437, -- Talasite
        23436, -- Living Ruby
        23427, -- Eternium Ore
        23426, -- Khorium Ore
        23425, -- Adamantite Ore
        23424, -- Fel Iron Ore
        23117, -- Azure Moonstone
        23112, -- Golden Draenite
        23107, -- Shadow Draenite
        23079, -- Deep Peridot
        23077, -- Blood Garnet
        22634, -- Underlight Ore
        22574, -- Mote of Fire
        22573, -- Mote of Earth
        21929, -- Flame Spessarite
    },
    -- https://www.wowhead.com/tbc/items?filter=73:194:166;1:1:1;0:1:0
    [1] = { -- Vanilla
        22203, -- Large Obsidian Shard
        22202, -- Small Obsidian Shard
        19774, -- Souldarite
        17056, -- Light Feather
        12800, -- Azerothian Diamond
        12799, -- Large Opal
        12365, -- Dense Stone
        12364, -- Huge Emerald
        12363, -- Arcane Crystal
        12361, -- Blue Sapphire
        12223, -- Meaty Bat Wing
        11754, -- Black Diamond
        11513, -- Tainted Vitriol
        11382, -- Blood of the Mountain
        11370, -- Dark Iron Ore
        10620, -- Thorium Ore
        9262, -- Black Vitriol
        7912, -- Solid Stone
        7911, -- Truesilver Ore
        7910, -- Star Ruby
        7909, -- Aquamarine
        7101, -- Bug Eye
        7100, -- Sticky Ichor
        7098, -- Splintered Tusk
        7096, -- Plucked Feather
        7076, -- Essence of Earth
        7074, -- Chipped Claw
        7073, -- Broken Fang
        6303, -- Raw Slitherskin Mackerel
        5833, -- Indurium Ore
        5364, -- Dry Salt Lick
        5362, -- Chew Toy
        5075, -- Blood Shard
        4874, -- Clean Fishbones
        4873, -- Dry Hardened Barnacle
        4872, -- Dry Scorpid Eye
        4870, -- Canvas Scraps
        4867, -- Broken Scorpid Leg
        4865, -- Ruined Pelt
        4776, -- Ruffled Feather
        4775, -- Cracked Bill
        4757, -- Cracked Egg Shells
        4702, -- Prospector's Pick
        4604, -- Forest Mushroom Cap
        4536, -- Shiny Red Apple
        4278, -- Lesser Bloodstone Ore
        3864, -- Citrine
        3858, -- Mithril Ore
        3340, -- Incendicite Ore
        3299, -- Fractured Canine
        3171, -- Broken Boar Tusk
        3170, -- Large Bear Tooth
        3169, -- Chipped Bear Tooth
        2838, -- Heavy Stone
        2836, -- Coarse Stone
        2835, -- Rough Stone
        2798, -- Rethban Ore
        2776, -- Gold Ore
        2775, -- Silver Ore
        2772, -- Iron Ore
        2771, -- Tin Ore
        2770, -- Copper Ore
        2672, -- Stringy Wolf Meat
        2590, -- Forest Spider Webbing
        2589, -- Linen Cloth
        2070, -- Darnassian Bleu
        1705, -- Lesser Moonstone
        1529, -- Jade
        1476, -- Snapped Spider Limb
        1210, -- Shadowgem
        1206, -- Moss Agate
        1181, -- Scroll of Spirit
        818, -- Tigerseye
        779, -- Shiny Seashell
        774, -- Malachite
        771, -- Chipped Boar Tusk
        755, -- Melted Candle
        159, -- Refreshing Spring Water
        118, -- Minor Healing Potion
        117, -- Tough Jerky
    },
}
