-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 20:25:38

items.Mining = {
    -- https://www.wowhead.com/tbc/items?filter=86:194:166;9:1:2;0:1:0
    [2] = { -- Burning Crusade
        35128, -- Hardened Khorium
        23573, -- Hardened Adamantite Bar
        23449, -- Khorium Bar
        23448, -- Felsteel Bar
        23447, -- Eternium Bar
        23446, -- Adamantite Bar
        23445, -- Fel Iron Bar
        22574, -- Mote of Fire
        22573, -- Mote of Earth
    },
    -- https://www.wowhead.com/tbc/items?filter=86:194:166;9:1:1;0:1:0
    [1] = { -- Vanilla
        17771, -- Elementium Bar
        12359, -- Thorium Bar
        11371, -- Dark Iron Bar
        6037, -- Truesilver Bar
        3860, -- Mithril Bar
        3859, -- Steel Bar
        3577, -- Gold Bar
        3576, -- Tin Bar
        3575, -- Iron Bar
        2842, -- Silver Bar
        2841, -- Bronze Bar
        2840, -- Copper Bar
    },
}
