-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 20:25:41

items.Mining = {
    -- https://www.wowhead.com/tbc/items?filter=87:166:194;9:2:1;0:0:1
    [2] = { -- Burning Crusade
        23573, -- Hardened Adamantite Bar
        23449, -- Khorium Bar
        23447, -- Eternium Bar
        23446, -- Adamantite Bar
        23445, -- Fel Iron Bar
        23427, -- Eternium Ore
        23426, -- Khorium Ore
        23425, -- Adamantite Ore
        23424, -- Fel Iron Ore
        22452, -- Primal Earth
        21884, -- Primal Fire
    },
    -- https://www.wowhead.com/tbc/items?filter=87:166:194;9:1:1;0:0:1
    [1] = { -- Vanilla
        18567, -- Elemental Flux
        18562, -- Elementium Ore
        17010, -- Fiery Core
        12360, -- Arcanite Bar
        11370, -- Dark Iron Ore
        10620, -- Thorium Ore
        7911, -- Truesilver Ore
        3858, -- Mithril Ore
        3857, -- Coal
        3576, -- Tin Bar
        3575, -- Iron Bar
        2840, -- Copper Bar
        2776, -- Gold Ore
        2775, -- Silver Ore
        2772, -- Iron Ore
        2771, -- Tin Ore
        2770, -- Copper Ore
    },
}
