#!/usr/bin/env python3
"""Merge generated WoW item-table Lua files.

Usage:
    python merge_tables.py "Mining*.lua"
    python merge_tables.py "Mining*.lua" Mining_merged.lua

Matching files are merged by Lua table name and expansion number. Duplicate
item IDs are emitted once, with items sorted from largest to smallest ID.
"""

from __future__ import annotations

import argparse
import glob
import re
from collections import OrderedDict
from dataclasses import dataclass, field
from pathlib import Path

TABLE_PATTERN = re.compile(r"^\s*items\.([A-Za-z_][A-Za-z0-9_]*)\s*=\s*\{\s*$")
EXPANSION_PATTERN = re.compile(
    r"^\s*\[(\d+)\]\s*=\s*\{\s*(?:--\s*(.*?))?\s*$"
)
ITEM_PATTERN = re.compile(r"^\s*(\d+)\s*,\s*--\s*(.*?)\s*$")
URL_PATTERN = re.compile(r"^\s*--\s+(https?://\S+)\s*$")


@dataclass
class Expansion:
    name: str = ""
    source_urls: list[str] = field(default_factory=list)
    items: dict[int, str] = field(default_factory=dict)


TableData = OrderedDict[str, OrderedDict[int, Expansion]]


def expand_inputs(pattern: str, output_file: Path | None) -> list[Path]:
    matches = sorted(Path(match) for match in glob.glob(pattern))
    if not matches and Path(pattern).is_file():
        matches = [Path(pattern)]

    output_resolved = output_file.resolve() if output_file else None
    unique_matches: list[Path] = []
    seen: set[Path] = set()
    for match in matches:
        resolved = match.resolve()
        if resolved == output_resolved or resolved in seen:
            continue
        seen.add(resolved)
        unique_matches.append(match)

    if not unique_matches:
        raise FileNotFoundError(f"No files matched: {pattern}")
    return unique_matches


def parse_file(path: Path, tables: TableData) -> None:
    current_table: str | None = None
    current_expansion: Expansion | None = None
    pending_url: str | None = None

    for line_number, line in enumerate(
        path.read_text(encoding="utf-8-sig").splitlines(), start=1
    ):
        table_match = TABLE_PATTERN.match(line)
        if table_match:
            current_table = table_match.group(1)
            tables.setdefault(current_table, OrderedDict())
            current_expansion = None
            pending_url = None
            continue

        if current_table is None:
            continue

        url_match = URL_PATTERN.match(line)
        if url_match:
            pending_url = url_match.group(1)
            continue

        expansion_match = EXPANSION_PATTERN.match(line)
        if expansion_match:
            expansion_number = int(expansion_match.group(1))
            expansion = tables[current_table].setdefault(
                expansion_number,
                Expansion(name=expansion_match.group(2) or ""),
            )
            if expansion_match.group(2) and not expansion.name:
                expansion.name = expansion_match.group(2)
            if pending_url and pending_url not in expansion.source_urls:
                expansion.source_urls.append(pending_url)
            pending_url = None
            current_expansion = expansion
            continue

        if current_expansion is None:
            if line.strip() == "}":
                current_table = None
            continue

        item_match = ITEM_PATTERN.match(line)
        if item_match:
            item_id = int(item_match.group(1))
            current_expansion.items.setdefault(item_id, item_match.group(2))
            continue

        if line.strip() == "}":
            current_expansion = None
            continue

        if line.strip() == "}" and current_table is not None:
            current_table = None

    if not tables:
        raise ValueError(f"No supported items tables found in {path}")


def build_lua(tables: TableData) -> str:
    lines = [
        "-- Generated by merge_tables.py",
        "",
    ]
    for table_name, expansions in tables.items():
        lines.append(f"items.{table_name} = {{")
        for expansion_number in sorted(expansions, reverse=True):
            expansion = expansions[expansion_number]
            for source_url in expansion.source_urls:
                lines.append(f"    -- {source_url}")
            suffix = f" -- {expansion.name}" if expansion.name else ""
            lines.append(f"    [{expansion_number}] = {{{suffix}")
            for item_id in sorted(expansion.items, reverse=True):
                lines.append(f"        {item_id}, -- {expansion.items[item_id]}")
            lines.append("    },")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def default_output(files: list[Path]) -> Path:
    stem = files[0].stem
    return files[0].with_name(f"{stem}_merged.lua")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("pattern", help="Input Lua file or wildcard pattern")
    parser.add_argument("output", nargs="?", help="Output Lua file")
    args = parser.parse_args()

    output_file = Path(args.output).resolve() if args.output else None
    try:
        input_files = expand_inputs(args.pattern, output_file)
        tables: TableData = OrderedDict()
        for input_file in input_files:
            parse_file(input_file, tables)
        if output_file is None:
            output_file = default_output(input_files).resolve()
        output_file.write_text(build_lua(tables), encoding="utf-8", newline="\r\n")
    except (FileNotFoundError, OSError, ValueError) as error:
        parser.error(str(error))

    print(f"Merged {len(input_files)} file(s) into: {output_file}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
