-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 10:20:09

items.Alchemy = {
    -- https://www.wowhead.com/items?filter=87:194:166;1:1:12;0:1:0
    [12] = { -- Midnight
        274781, -- Cursebound Globe
        274777, -- Neutralized Venom Clot
        251285, -- Petrified Root
        251283, -- Tormented Tantalum
        247811, -- Oil of Heartwood
        243602, -- Radiant Shard
        243599, -- Eversinging Dust
        242651, -- Stabilized Derivate
        241307, -- Refreshing Serum
        241305, -- Silvermoon Health Potion
        241283, -- Wondrous Synergist
        241281, -- Composite Flora
        240991, -- Sunglass Vial
        238525, -- Fantastic Fur
        238520, -- Void-Tempered Plating
        238518, -- Void-Tempered Hide
        238383, -- Eversong Trout
        238369, -- Bloomtail Minnow
        238365, -- Sin'dorei Swarmer
        236952, -- Mote of Pure Void
        236951, -- Mote of Wild Magic
        236950, -- Mote of Primal Energy
        236949, -- Mote of Light
        236780, -- Nocturnal Lotus
        236778, -- Mana Lily
        236776, -- Argentleaf
        236774, -- Azeroot
        236770, -- Sanguithorn
        236761, -- Tranquility Bloom
    },
    -- https://www.wowhead.com/items?filter=87:194:166;1:1:11;0:1:0
    [11] = { -- The War Within
        256963, -- Thalassian Lumber
        251773, -- Dragonpine Lumber
        251772, -- Arden Lumber
        251768, -- Darkpine Lumber
        251767, -- Fel-Touched Lumber
        251766, -- Shadowmoon Lumber
        251764, -- Ashwood Lumber
        251763, -- Bamboo Lumber
        251762, -- Coldwind Lumber
        248012, -- Dornic Fir Lumber
        245586, -- Ironwood Lumber
        242691, -- Olemba Lumber
        226205, -- Distilled Algari Freshwater
        221763, -- Viridian Charmcap
        221758, -- Profaned Tinderbox
        221756, -- Vial of Kaheti Oils
        213759, -- Inverted Prism
        213613, -- Leyline Residue
        213612, -- Viridescent Spores
        213611, -- Writhing Sample
        213610, -- Crystalline Powder
        213197, -- Null Lotus
        212754, -- Crystalforged Cauldron
        212563, -- Harmonious Horticulture
        212292, -- Vicious Flask of Honor
        212245, -- Slumbering Soul Serum
        211806, -- Gilded Vial
        211805, -- Gleaming Transmutagen
        211804, -- Volatile Transmutagen
        211803, -- Mercurial Transmutagen
        211802, -- Ominous Transmutagen
        210828, -- Dilution Solution
        210815, -- Coreway Catalyst
        210814, -- Artisan's Acuity
        210808, -- Arathor's Spear
        210805, -- Blessing Blossom
        210802, -- Orbinid
        210799, -- Luredrop
        210796, -- Mycobloom
    },
    -- https://www.wowhead.com/items?filter=87:194:166;1:1:10;0:1:0
    [10] = { -- Dragonflight
        204463, -- Dracothyst
        204460, -- Zaralek Glowspores
        203398, -- Dampening Powder
        201406, -- Glowing Titan Orb
        201405, -- Tuft of Primal Wool
        194727, -- Fiery Spirit
        193368, -- Silken Gemdust
        192883, -- Glossy Stone
        191570, -- Dragon's Alchemical Solution
        191496, -- Omnium Draconis
        191493, -- Primal Convergent
        191474, -- Draconic Vial
        191470, -- Writhebark
        191467, -- Bubble Poppy
        191464, -- Saxifrage
        191460, -- Hochenblume
        191387, -- Elemental Potion of Power
        191384, -- Aerated Mana Potion
        191378, -- Refreshing Healing Potion
        191369, -- Potion of Withering Vitality
        191363, -- Potion of Frozen Focus
        191357, -- Phial of Elemental Chaos
        191339, -- Phial of Tepid Versatility
        190456, -- Artisan's Mettle
        190331, -- Awakened Decay
        190330, -- Rousing Decay
        190329, -- Awakened Frost
        190328, -- Rousing Frost
        190327, -- Awakened Air
        190326, -- Rousing Air
        190324, -- Awakened Order
        190321, -- Awakened Fire
        190316, -- Awakened Earth
        190312, -- Khaz'gorite Ore
        189143, -- Draconium Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;1:1:9;0:1:0
    [9] = { -- Shadowland
        187707, -- Progenitor Essentia
        187699, -- First Flower
        183953, -- Sealing Wax
        183950, -- Distilled Death Extract
        182073, -- Fresh Bramblethorn Trimmings
        182072, -- Bramblethorn Juice
        182071, -- Refined Submission
        182049, -- Bones of Defeated Enemies
        182048, -- Crushed Bones
        182047, -- Brutal Oil
        182027, -- Fresh Breezebloom Trimmings
        182026, -- Pulverized Breezebloom
        182025, -- Distilled Resolve
        181985, -- Fresh Dreamroot Trimmings
        181984, -- Powdered Dreamroot
        181983, -- Liquid Sleep
        180732, -- Rune Etched Vial
        180457, -- Shadestone
        178787, -- Orboreal Shard
        177061, -- Twilight Bark
        173202, -- Shrouded Cloth
        173170, -- Essence of Rebirth
        171841, -- Shaded Stone
        171840, -- Porous Stone
        171292, -- Ground Nightshade
        171291, -- Ground Rising Glory
        171290, -- Ground Marrowroot
        171289, -- Ground Widowbloom
        171288, -- Ground Vigil's Torch
        171287, -- Ground Death Blossom
        171286, -- Embalmer's Oil
        171285, -- Shadowcore Oil
        171276, -- Spectral Flask of Power
        171268, -- Spiritual Mana Potion
        171267, -- Spiritual Healing Potion
        170554, -- Vigil's Torch
    },
    -- https://www.wowhead.com/items?filter=87:194:166;1:1:8;0:1:0
    [8] = { -- BfA
        171315, -- Nightshade
        170553, -- Void Focus Splinter
        169701, -- Death Blossom
        168654, -- Greater Flask of the Undertow
        168653, -- Greater Flask of the Vast Horizon
        168652, -- Greater Flask of Endless Fathoms
        168651, -- Greater Flask of the Currents
        168589, -- Marrowroot
        168586, -- Rising Glory
        168583, -- Widowbloom
        168487, -- Zin'anthid
        166374, -- Test Vial
        166373, -- Storm Silver Shards
        166372, -- Sand Shifter Scales
        166371, -- Dried Star Moss Leaves
        165948, -- Tidalcore
        165703, -- Breath of Bwonsamdi
        162519, -- Mystical Cauldron
        162461, -- Sanguicell
        162460, -- Hydrocore
        158186, -- Distilled Water
        154898, -- Meaty Haunch
        154897, -- Stringy Loins
        154164, -- Blood-Stained Bone
        152668, -- Expulsom
        152641, -- Flask of the Undertow
        152640, -- Flask of the Vast Horizon
        152639, -- Flask of Endless Fathoms
        152638, -- Flask of the Currents
        152579, -- Storm Silver Ore
        152577, -- Deep Sea Satin
        152576, -- Tidespray Linen
        152547, -- Great Sea Catfish
        152543, -- Sand Shifter
        152512, -- Monelite Ore
        152511, -- Sea Stalk
        152510, -- Anchor Weed
        152509, -- Siren's Pollen
        152508, -- Winter's Kiss
        152507, -- Akunda's Bite
        152506, -- Star Moss
        152505, -- Riverbud
        152495, -- Coastal Mana Potion
        152494, -- Coastal Healing Potion
    },
    -- https://www.wowhead.com/items?filter=87:194:166;1:1:7;0:1:0
    [7] = { -- Legion
        156930, -- Rich Illusion Dust
        151568, -- Primal Sargerite
        151565, -- Astral Glory
        137597, -- Oily Transmutagen
        137596, -- Black Transmutagen
        137595, -- Viscous Transmutagen
        133607, -- Silver Mackerel
        128304, -- Yseralline Seed
        127850, -- Flask of Ten Thousand Scars
        127849, -- Flask of the Countless Armies
        127848, -- Flask of the Seventh Demon
        127847, -- Flask of the Whispered Pact
        127838, -- Sylvan Elixir
        127836, -- Ancient Rejuvenation Potion
        127835, -- Ancient Mana Potion
        127834, -- Ancient Healing Potion
        124461, -- Demonsteel Bar
        124444, -- Infernal Brimstone
        124440, -- Arkhana
        124439, -- Unbroken Tooth
        124438, -- Unbroken Claw
        124437, -- Shal'dorei Silk
        124124, -- Blood of Sargeras
        124121, -- Wildfowl Egg
        124120, -- Leyblood
        124119, -- Big Gamy Ribs
        124118, -- Fatty Bearsteak
        124117, -- Lean Shank
        124115, -- Stormscale
        124113, -- Stonehide Leather
        124112, -- Black Barracuda
        124111, -- Runescale Koi
        124110, -- Stormray
        124109, -- Highmountain Salmon
        124108, -- Mossgill Perch
        124107, -- Cursed Queenfish
        124106, -- Felwort
        124105, -- Starlight Rose
        124104, -- Fjarnskaggl
        124103, -- Foxflower
        124102, -- Dreamleaf
        124101, -- Aethril
        123919, -- Felslate
        123918, -- Leystone Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;1:1:6;0:1:0
    [6] = { -- WoD
        127759, -- Felblight
        118472, -- Savage Blood
        117454, -- Gorgrond Grapes
        113264, -- Sorcerous Air
        113263, -- Sorcerous Earth
        113262, -- Sorcerous Water
        113261, -- Sorcerous Fire
        109223, -- Healing Tonic
        109222, -- Draenic Mana Potion
        109152, -- Draenic Stamina Flask
        109148, -- Draenic Strength Flask
        109147, -- Draenic Intellect Flask
        109145, -- Draenic Agility Flask
        109144, -- Blackwater Whiptail Flesh
        109143, -- Abyssal Gulper Eel Flesh
        109142, -- Sea Scorpion Segment
        109141, -- Fire Ammonite Tentacle
        109140, -- Blind Lake Sturgeon Flesh
        109139, -- Fat Sleeper Flesh
        109138, -- Jawless Skulker Flesh
        109137, -- Crescent Saberfish Flesh
        109129, -- Talador Orchid
        109128, -- Nagrand Arrowbloom
        109127, -- Starflower
        109126, -- Gorgrond Flytrap
        109125, -- Fireweed
        109124, -- Frostweed
        109123, -- Crescent Oil
        109119, -- True Iron Ore
        109118, -- Blackrock Ore
        108996, -- Alchemical Catalyst
    },
    -- https://www.wowhead.com/items?filter=87:194:166;1:1:5;0:1:0
    [5] = { -- MoP
        87872, -- Desecrated Oil
        83064, -- Spinefish
        79011, -- Fool's Cap
        79010, -- Snow Lily
        76141, -- Imperial Amethyst
        76140, -- Vermilion Onyx
        76139, -- Wild Jade
        76137, -- Alexandrite
        76136, -- Pandarian Garnet
        76135, -- Roguestone
        76134, -- Sunstone
        76133, -- Lapis Lazuli
        76130, -- Tiger Opal
        76098, -- Master Mana Potion
        76061, -- Spirit of Harmony
        72238, -- Golden Lotus
        72237, -- Rain Poppy
        72235, -- Silkweed
        72234, -- Green Tea Leaf
        72096, -- Ghost Iron Bar
        72095, -- Trillium Bar
    },
    -- https://www.wowhead.com/items?filter=87:194:166;1:1:4;0:1:0
    [4] = { -- Cataclysm
        69237, -- Living Ember
        65893, -- Sands of Time
        65892, -- Pyrium-Laced Crystalline Vial
        58480, -- Truegold
        58142, -- Deathblood Venom
        58088, -- Flask of Titanic Strength
        58087, -- Flask of the Winds
        58086, -- Flask of the Draconic Mind
        58085, -- Flask of Steelskin
        56850, -- Deepstone Oil
        54849, -- Obsidium Bar
        53065, -- Albino Cavefish
        52988, -- Whiptail
        52987, -- Twilight Jasmine
        52986, -- Heartblossom
        52985, -- Azshara's Veil
        52984, -- Stormvine
        52983, -- Cinderbloom
        52329, -- Volatile Life
        52328, -- Volatile Air
        52327, -- Volatile Earth
        52326, -- Volatile Water
        52325, -- Volatile Fire
        52186, -- Elementium Bar
        52182, -- Jasper
        52181, -- Hessonite
        52180, -- Nightstone
        52179, -- Alicite
        52178, -- Zephyrite
        52177, -- Carnelian
        51950, -- Pyrium Bar
    },
    -- https://www.wowhead.com/items?filter=87:194:166;1:1:3;0:1:0
    [3] = { -- WolTK
        44958, -- Ethereal Oil
        43102, -- Frozen Orb
        41814, -- Glassfin Minnow
        40199, -- Pygmy Suckerfish
        40195, -- Pygmy Oil
        40077, -- Crazy Alchemist's Potion
        37921, -- Deadnettle
        37705, -- Crystallized Water
        37704, -- Crystallized Life
        37703, -- Crystallized Shadow
        37702, -- Crystallized Fire
        37701, -- Crystallized Earth
        36933, -- Forest Emerald
        36932, -- Dark Jade
        36930, -- Monarch Topaz
        36929, -- Huge Citrine
        36927, -- Twilight Opal
        36924, -- Sky Sapphire
        36923, -- Chalcedony
        36921, -- Autumn's Glow
        36918, -- Scarlet Ruby
        36917, -- Bloodstone
        36913, -- Saronite Bar
        36908, -- Frost Lotus
        36907, -- Talandra's Rose
        36906, -- Icethorn
        36905, -- Lichbloom
        36904, -- Tiger Lily
        36903, -- Adder's Tongue
        36901, -- Goldclover
        36860, -- Eternal Fire
        35627, -- Eternal Shadow
        35625, -- Eternal Life
        35624, -- Eternal Earth
        35623, -- Eternal Air
        35622, -- Eternal Water
        33448, -- Runic Mana Potion
        33447, -- Runic Healing Potion
    },
    -- https://www.wowhead.com/items?filter=87:194:166;1:1:2;0:1:0
    [2] = { -- TBC
        34440, -- Mad Alchemist's Potion
        30183, -- Nether Vortex
        25868, -- Skyfire Diamond
        25867, -- Earthstorm Diamond
        23782, -- Fel Iron Casing
        23573, -- Hardened Adamantite Bar
        23571, -- Primal Might
        23449, -- Khorium Bar
        23117, -- Azure Moonstone
        23112, -- Golden Draenite
        23107, -- Shadow Draenite
        23079, -- Deep Peridot
        23077, -- Blood Garnet
        22861, -- Flask of Blinding Light
        22794, -- Fel Lotus
        22793, -- Mana Thistle
        22792, -- Nightmare Vine
        22791, -- Netherbloom
        22790, -- Ancient Lichen
        22789, -- Terocone
        22787, -- Ragveil
        22786, -- Dreaming Glory
        22785, -- Felweed
        22578, -- Mote of Water
        22574, -- Mote of Fire
        22573, -- Mote of Earth
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        21929, -- Flame Spessarite
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
        21840, -- Bolt of Netherweave
    },
    -- https://www.wowhead.com/items?filter=87:194:166;1:1:1;0:1:0
    [1] = { -- Classic
        20520, -- Dark Rune
        19943, -- Massive Mojo
        19441, -- Huge Venom Sac
        13468, -- Black Lotus
        13467, -- Icecap
        13466, -- Sorrowmoss
        13465, -- Mountain Silversage
        13464, -- Golden Sansam
        13463, -- Dreamfoil
        13423, -- Stonescale Oil
        13422, -- Stonescale Eel
        12808, -- Essence of Undeath
        12804, -- Powerful Mojo
        12803, -- Living Essence
        12363, -- Arcane Crystal
        12360, -- Arcanite Bar
        12359, -- Thorium Bar
        10620, -- Thorium Ore
        10286, -- Heart of the Wild
        9262, -- Black Vitriol
        9260, -- Volatile Rum
        8846, -- Gromsblood
        8845, -- Ghost Mushroom
        8839, -- Blindweed
        8838, -- Sungrass
        8831, -- Purple Lotus
        8153, -- Wildvine
        7972, -- Ichor of Undeath
        7082, -- Essence of Air
        7080, -- Essence of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7070, -- Elemental Water
        7068, -- Elemental Fire
        7067, -- Elemental Earth
        6522, -- Deviate Fish
        6371, -- Fire Oil
        6370, -- Blackmouth Oil
        6359, -- Firefin Snapper
        6358, -- Oily Blackmouth
        5637, -- Large Fang
        5635, -- Sharp Claw
        4625, -- Firebloom
        4402, -- Small Flame Sac
        4342, -- Purple Dye
        3860, -- Mithril Bar
        3858, -- Mithril Ore
        3824, -- Shadow Oil
        3821, -- Goldthorn
        3820, -- Stranglekelp
        3819, -- Dragon's Teeth
        3818, -- Fadeleaf
        3575, -- Iron Bar
        3371, -- Crystal Vial
        3369, -- Grave Moss
        3358, -- Khadgar's Whisker
        3357, -- Liferoot
        3356, -- Kingsblood
        3355, -- Wild Steelbloom
        3164, -- Discolored Worg Heart
        2453, -- Bruiseweed
        2452, -- Swiftthistle
        2450, -- Briarthorn
        2449, -- Earthroot
        2447, -- Peacebloom
        2325, -- Black Dye
        1475, -- Small Venom Sac
        1288, -- Large Venom Sac
        785, -- Mageroyal
        765, -- Silverleaf
        118, -- Minor Healing Potion
    },
}
