-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 10:44:43

items.Blacksmithing = {
    -- https://www.wowhead.com/items?filter=87:194:166;2:1:12;0:1:0
    [12] = { -- Midnight
        274781, -- Cursebound Globe
        274777, -- Neutralized Venom Clot
        251285, -- Petrified Root
        251283, -- Tormented Tantalum
        245345, -- Fused Vitality
        244637, -- Silvermoon Weapon Wrap
        244635, -- Sin'dorei Armor Banding
        243060, -- Luminant Flux
        242788, -- Dusk-Shrouded Stone
        238530, -- Majestic Fin
        238529, -- Majestic Hide
        238528, -- Majestic Claw
        238204, -- Sterling Alloy
        238202, -- Gloaming Alloy
        238197, -- Refulgent Copper Ingot
        237366, -- Dazzling Thorium
        237364, -- Brilliant Silver Ore
        237362, -- Umbral Tin Ore
        237359, -- Refulgent Copper Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;2:1:11;0:1:0
    [11] = { -- The War Within
        256963, -- Thalassian Lumber
        251773, -- Dragonpine Lumber
        251772, -- Arden Lumber
        251768, -- Darkpine Lumber
        251767, -- Fel-Touched Lumber
        251766, -- Shadowmoon Lumber
        251764, -- Ashwood Lumber
        251763, -- Bamboo Lumber
        251762, -- Coldwind Lumber
        248012, -- Dornic Fir Lumber
        245586, -- Ironwood Lumber
        242691, -- Olemba Lumber
        226202, -- Echoing Flux
        222523, -- Coreforged Skeleton Key
        222426, -- Ironclaw Alloy
        222423, -- Sanctified Alloy
        222420, -- Charged Alloy
        222417, -- Core Alloy
        221856, -- Whimsical Wiring
        221853, -- Handful of Bismuth Bolts
        221758, -- Profaned Tinderbox
        221757, -- Gloomfathom Hide
        221756, -- Vial of Kaheti Oils
        221754, -- Ringing Deeps Ingot
        219901, -- Storm-Touched Weapon Wrap
        219013, -- Superb Beast Fang
        213610, -- Crystalline Powder
        210939, -- Null Stone
        210936, -- Ironclaw Ore
        210933, -- Aqirite
        210930, -- Bismuth
        210814, -- Artisan's Acuity
    },
    -- https://www.wowhead.com/items?filter=87:194:166;2:1:10;0:1:0
    [10] = { -- Dragonflight
        207702, -- Wartorn Scrap
        205413, -- Obsidian Cobraskin
        205257, -- Temporal Vestigial
        204995, -- Shadowed Alloy
        204857, -- Ancient Elementium Fragment
        204464, -- Shadowflame Essence
        203865, -- Brilliant Wizard Oil
        203862, -- Brilliant Mana Oil
        203399, -- Damaged Trident
        201406, -- Glowing Titan Orb
        201403, -- Mastodon Tusk
        201402, -- Large Sturdy Femur
        201400, -- Aquatic Maw
        201399, -- Primal Bear Spine
        194727, -- Fiery Spirit
        193922, -- Wildercloth
        193920, -- Earthen Soul
        193919, -- Frosty Soul
        193368, -- Silken Gemdust
        193362, -- Fiery Soul
        193360, -- Centaur's Trophy Necklace
        192883, -- Glossy Stone
        192849, -- Eternity Amber
        192846, -- Sundered Onyx
        192843, -- Vibrant Emerald
        192840, -- Mystic Sapphire
        192837, -- Queen's Ruby
        191363, -- Potion of Frozen Focus
        190536, -- Infurious Alloy
        190533, -- Obsidian Seared Alloy
        190530, -- Frostfire Alloy
        190456, -- Artisan's Mettle
        190452, -- Primal Flux
        190450, -- Awakened Ire
        190395, -- Serevite Ore
        190329, -- Awakened Frost
        190324, -- Awakened Order
        190321, -- Awakened Fire
        190316, -- Awakened Earth
        190312, -- Khaz'gorite Ore
        189541, -- Primal Molten Alloy
        189143, -- Draconium Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;2:1:9;0:1:0
    [9] = { -- Shadowlands
        187707, -- Progenitor Essentia
        187700, -- Progenium Ore
        186017, -- Korthite Crystal
        182094, -- Borrowed Sinvyr Rod
        182093, -- Soft Manacle Chains
        182092, -- Tempered Manacle Chains
        182091, -- Borrowed Sinvyr Bar
        182090, -- Binding Cuffs
        182089, -- Enchanted Rivets
        182088, -- Borrowed Oxxein Ore
        182087, -- Soft Heavy Razor
        182086, -- Hardened Heavy Razor
        181860, -- Borrowed Twilight Bark
        181793, -- Shattered Kyrian Shield Fragment
        181792, -- Tarnished Kyrian Shield
        181790, -- Reforged Kyrian Shield
        181789, -- Wooden Arrowhead Mold
        181788, -- Unrefined Arrowheads
        181787, -- Molten Phaedrum
        181783, -- Borrowed Phaedrum Ore
        180733, -- Luminous Flux
        178787, -- Orboreal Shard
        173204, -- Lightless Silk
        173202, -- Shrouded Cloth
        173173, -- Essence of Valor
        173171, -- Essence of Torment
        173109, -- Angerseye
        173060, -- Aerated Water
        172437, -- Enchanted Elethium Bar
        171841, -- Shaded Stone
        171840, -- Porous Stone
        171833, -- Elethium Ore
        171832, -- Sinvyr Ore
        171831, -- Phaedrum Ore
        171830, -- Oxxein Ore
        171829, -- Solenium Ore
        171828, -- Laestrite Ore
        171428, -- Shadowghast Ingot
    },
    -- https://www.wowhead.com/items?filter=87:194:166;2:1:8;0:1:0
    [8] = { -- Battle for Azeroth
        170553, -- Void Focus Splinter
        169445, -- Dredged Leather Bladder
        168185, -- Osmenite Ore
        168135, -- Titan's Blood
        165948, -- Tidalcore
        165703, -- Breath of Bwonsamdi
        162461, -- Sanguicell
        162460, -- Hydrocore
        160298, -- Durable Flux
        154898, -- Meaty Haunch
        152812, -- Monel-Hardened Hoofplates
        152668, -- Expulsom
        152579, -- Storm Silver Ore
        152513, -- Platinum Ore
        152512, -- Monelite Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;2:1:7;0:1:0
    [7] = { -- Legion
        151923, -- Empyrial Rivet
        151568, -- Primal Sargerite
        151564, -- Empyrium
        133591, -- River Onion
        133589, -- Dalapeño Pepper
        133588, -- Flaked Sea Salt
        130179, -- Eye of Prophecy
        128777, -- Heated Leystone Bar
        124461, -- Demonsteel Bar
        124454, -- Brimstone-Crusted Armguards
        124453, -- Brimstone-Covered Armguards
        124451, -- Felsmith's Infernal Brimstone
        124450, -- Engraved Leystone Armguards
        124449, -- Felsmith's Leystone Armguards
        124444, -- Infernal Brimstone
        124441, -- Leylight Shard
        124440, -- Arkhana
        124439, -- Unbroken Tooth
        124438, -- Unbroken Claw
        124437, -- Shal'dorei Silk
        124436, -- Foxflower Flux
        124435, -- Leystone Neckplate
        124432, -- Leystone Dome
        124431, -- Leystone Faceguard
        124430, -- Leystone Soleplate
        124429, -- Leystone Footguard
        124428, -- Leystone Heelguard
        124427, -- Leystone Shinplate
        124425, -- Felsmith's Leystone Bar
        124423, -- Heated Hard Leystone Ingot
        124422, -- Hard Leystone Ingot
        124421, -- Lump of Leystone Slag
        124420, -- Leystone Shard
        124418, -- Leystone Slag
        124417, -- Shopkeeper's Leystone Ore
        124407, -- Large Heated Metal Scrap
        124406, -- Medium Heated Metal Scrap
        124405, -- Small Heated Metal Scrap
        124404, -- Large Metal Scrap
        124403, -- Medium Metal Scrap
        124402, -- Small Metal Scrap
        124396, -- Dull Hard Leystone Armguards
        124395, -- Heated Hard Leystone Bar
        124394, -- Hard Leystone Bar
        124393, -- Leystone Slag
        124392, -- Shopkeeper's Leystone Ore
        124124, -- Blood of Sargeras
        124116, -- Felhide
        124115, -- Stormscale
        124113, -- Stonehide Leather
        124109, -- Highmountain Salmon
        124010, -- Leystone Fingerguard
        124009, -- Leystone Cuffplate
        124007, -- Leystone Bar
        124005, -- Shopkeeper's Leystone Ore
        123919, -- Felslate
        123918, -- Leystone Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;2:1:6;0:1:0
    [6] = { -- Warlords of Draenor
        127759, -- Felblight
        120945, -- Primal Spirit
        118472, -- Savage Blood
        113261, -- Sorcerous Fire
        111557, -- Sumptuous Fur
        110609, -- Raw Beast Hide
        109119, -- True Iron Ore
        109118, -- Blackrock Ore
        108257, -- Truesteel Ingot
    },
    -- https://www.wowhead.com/items?filter=87:194:166;2:1:5;0:1:0
    [5] = { -- Mists of Pandaria
        102218, -- Spirit of War
        98717, -- Balanced Trillium Ingot
        94289, -- Haunting Spirit
        94111, -- Lightning Steel Ingot
        80433, -- Blood Spirit
        77468, -- High-Explosive Gunpowder
        77467, -- Ghost Iron Bolts
        76061, -- Spirit of Harmony
        72104, -- Living Steel
        72096, -- Ghost Iron Bar
        72095, -- Trillium Bar
        72093, -- Kyparite
        72092, -- Ghost Iron Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;2:1:4;0:1:0
    [4] = { -- Cataclysm
        71998, -- Essence of Destruction
        69237, -- Living Ember
        65365, -- Folded Obsidium
        58480, -- Truegold
        56516, -- Heavy Savage Leather
        54849, -- Obsidium Bar
        53039, -- Hardened Elementium Bar
        53038, -- Obsidium Ore
        52329, -- Volatile Life
        52327, -- Volatile Earth
        52326, -- Volatile Water
        52325, -- Volatile Fire
        52193, -- Ember Topaz
        52191, -- Ocean Sapphire
        52190, -- Inferno Ruby
        52186, -- Elementium Bar
        52185, -- Elementium Ore
        52182, -- Jasper
        52178, -- Zephyrite
        52078, -- Chaos Orb
        51950, -- Pyrium Bar
    },
    -- https://www.wowhead.com/items?filter=87:194:166;2:1:3;0:1:0
    [3] = { -- Wrath of the Lich King
        49908, -- Primordial Saronite
        47556, -- Crusader Orb
        45087, -- Runed Orb
        43102, -- Frozen Orb
        41163, -- Titanium Bar
        37705, -- Crystallized Water
        37703, -- Crystallized Shadow
        37702, -- Crystallized Fire
        37701, -- Crystallized Earth
        37700, -- Crystallized Air
        37663, -- Titansteel Bar
        36925, -- Majestic Zircon
        36916, -- Cobalt Bar
        36913, -- Saronite Bar
        36912, -- Saronite Ore
        36909, -- Cobalt Ore
        36860, -- Eternal Fire
        35627, -- Eternal Shadow
        35625, -- Eternal Life
        35624, -- Eternal Earth
        35623, -- Eternal Air
        35622, -- Eternal Water
        34054, -- Infinite Dust
    },
    -- https://www.wowhead.com/items?filter=87:194:166;2:1:2;0:1:0
    [2] = { -- Burning Crusade
        35128, -- Hardened Khorium
        34664, -- Sunmote
        32428, -- Heart of Darkness
        30183, -- Nether Vortex
        27503, -- Scroll of Strength V
        25868, -- Skyfire Diamond
        23573, -- Hardened Adamantite Bar
        23572, -- Primal Nether
        23571, -- Primal Might
        23449, -- Khorium Bar
        23448, -- Felsteel Bar
        23447, -- Eternium Bar
        23446, -- Adamantite Bar
        23445, -- Fel Iron Bar
        23424, -- Fel Iron Ore
        22831, -- Elixir of Major Agility
        22824, -- Elixir of Major Strength
        22573, -- Mote of Earth
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        22450, -- Void Crystal
        22449, -- Large Prismatic Shard
        22445, -- Arcane Dust
        21887, -- Knothide Leather
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
        21877, -- Netherweave Cloth
        21845, -- Primal Mooncloth
    },
    -- https://www.wowhead.com/items?filter=87:194:166;2:1:1;0:1:0
    [1] = { -- Vanilla
        22682, -- Frozen Rune
        22203, -- Large Obsidian Shard
        22202, -- Small Obsidian Shard
        20520, -- Dark Rune
        20007, -- Mageblood Elixir
        20004, -- Mighty Troll's Blood Elixir
        19943, -- Massive Mojo
        19931, -- Gurubashi Mojo Madness
        19441, -- Huge Venom Sac
        18567, -- Elemental Flux
        18335, -- Pristine Black Diamond
        17203, -- Sulfuron Ingot
        17012, -- Core Leather
        17011, -- Lava Core
        17010, -- Fiery Core
        15417, -- Devilsaur Leather
        14344, -- Large Brilliant Shard
        14256, -- Felcloth
        14047, -- Runecloth
        13926, -- Golden Pearl
        13512, -- Flask of Supreme Power
        13510, -- Flask of the Titans
        12811, -- Righteous Orb
        12810, -- Enchanted Leather
        12809, -- Guardian Stone
        12808, -- Essence of Undeath
        12804, -- Powerful Mojo
        12803, -- Living Essence
        12800, -- Azerothian Diamond
        12799, -- Large Opal
        12662, -- Demonic Rune
        12655, -- Enchanted Thorium Bar
        12644, -- Dense Grinding Stone
        12365, -- Dense Stone
        12364, -- Huge Emerald
        12361, -- Blue Sapphire
        12360, -- Arcanite Bar
        12359, -- Thorium Bar
        11754, -- Black Diamond
        11382, -- Blood of the Mountain
        11371, -- Dark Iron Bar
        10620, -- Thorium Ore
        9210, -- Ghost Dye
        8170, -- Rugged Leather
        8153, -- Wildvine
        7972, -- Ichor of Undeath
        7971, -- Black Pearl
        7966, -- Solid Grinding Stone
        7912, -- Solid Stone
        7910, -- Star Ruby
        7909, -- Aquamarine
        7081, -- Breath of Wind
        7080, -- Essence of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7075, -- Core of Earth
        7070, -- Elemental Water
        7069, -- Elemental Air
        7068, -- Elemental Fire
        7067, -- Elemental Earth
        6041, -- Steel Weapon Chain
        6037, -- Truesilver Bar
        5637, -- Large Fang
        5635, -- Sharp Claw
        5500, -- Iridescent Pearl
        5498, -- Small Lustrous Pearl
        4338, -- Mageweave Cloth
        4306, -- Silk Cloth
        4304, -- Thick Leather
        4234, -- Heavy Leather
        3864, -- Citrine
        3860, -- Mithril Bar
        3859, -- Steel Bar
        3858, -- Mithril Ore
        3857, -- Coal
        3829, -- Frost Oil
        3824, -- Shadow Oil
        3823, -- Lesser Invisibility Potion
        3577, -- Gold Bar
        3575, -- Iron Bar
        3486, -- Heavy Grinding Stone
        3478, -- Coarse Grinding Stone
        3470, -- Rough Grinding Stone
        3466, -- Strong Flux
        3391, -- Elixir of Ogre's Strength
        2880, -- Weak Flux
        2842, -- Silver Bar
        2841, -- Bronze Bar
        2840, -- Copper Bar
        2838, -- Heavy Stone
        2836, -- Coarse Stone
        2835, -- Rough Stone
        2772, -- Iron Ore
        2771, -- Tin Ore
        2770, -- Copper Ore
        2605, -- Green Dye
        2604, -- Red Dye
        2592, -- Wool Cloth
        2589, -- Linen Cloth
        2459, -- Swiftness Potion
        2321, -- Fine Thread
        2319, -- Medium Leather
        2318, -- Light Leather
        1705, -- Lesser Moonstone
        1529, -- Jade
        1210, -- Shadowgem
        1206, -- Moss Agate
        818, -- Tigerseye
        774, -- Malachite
    },
}
