-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 10:04:35

items.Cooking = {
    -- https://www.wowhead.com/items?filter=87:194:166;3:1:12;0:1:0
    [12] = { -- Midnight
        274781, -- Cursebound Globe
        274777, -- Neutralized Venom Clot
        274594, -- Polluted Puffer
        274591, -- Coiled Stargorger
        274590, -- Sulfurous Sludgefish
        274589, -- Ula'tek Snakehead
        253403, -- Thalassian Fillet
        251285, -- Petrified Root
        242647, -- Tavern Fixings
        242646, -- Pouch of Spices
        242645, -- Ripened Vegetable Assortment
        242644, -- Mana-Wyrm Essence
        242643, -- A Big Ol' Stick of Butter
        242642, -- Thalassian Herbs
        242641, -- Cooking Spirits
        242640, -- Plant Protein
        242639, -- Practically Pork
        238384, -- Sunwell Fish
        238383, -- Eversong Trout
        238379, -- Warping Wise
        238378, -- Shimmersiren
        238377, -- Blood Hunter
        238376, -- Lucky Loa
        238374, -- Tender Lumifin
        238373, -- Ominous Octopus
        238372, -- Restored Songfish
        238371, -- Arcane Wyrmfish
        238369, -- Bloomtail Minnow
        238368, -- Twisted Tetra
        238367, -- Root Crab
        238366, -- Lynxfish
        236951, -- Mote of Wild Magic
        236950, -- Mote of Primal Energy
        236778, -- Mana Lily
        236776, -- Argentleaf
        236774, -- Azeroot
        236770, -- Sanguithorn
        236761, -- Tranquility Bloom
    },
    -- https://www.wowhead.com/items?filter=87:194:166;3:1:11;0:1:0
    [11] = { -- The War Within
        259894, -- Perfect Preservatives
        251773, -- Dragonpine Lumber
        251772, -- Arden Lumber
        251768, -- Darkpine Lumber
        251766, -- Shadowmoon Lumber
        251763, -- Bamboo Lumber
        248012, -- Dornic Fir Lumber
        235845, -- Undermine Clam Meat
        225912, -- Hot Honeycomb
        225883, -- Prepared Ghoulfish
        225876, -- Fine Egg Powder
        224762, -- Delver's Waterskin
        223977, -- Coagulated Yolk
        223971, -- Azj-Kahet Special
        223968, -- Spongey Scramble
        222741, -- Fresh Fillet
        222739, -- Spiced Meat Stock
        222738, -- Portioned Steak
        222737, -- Chopped Mycobloom
        222731, -- Outsider's Provisions
        222705, -- Roasted Mycobloom
        222703, -- Simple Stew
        222701, -- Clumped Flour
        222700, -- Granulated Spices
        222699, -- Khaz Algar Tomato
        222697, -- Coreway Dust
        222696, -- Crunchy Peppers
        222695, -- Twined Herbs
        221754, -- Ringing Deeps Ingot
        220153, -- Awoken Coelacanth
        220151, -- Queen's Lurefish
        220150, -- Spiked Sea Raven
        220149, -- Sanguine Dogfish
        220147, -- Kaheti Slum Shark
        220146, -- Regal Dottyback
        220145, -- Arathor Hammerfish
        220144, -- Roaring Anglerseeker
        220142, -- Quiet River Bass
        220138, -- Nibbling Minnow
        220137, -- Bismuth Bitterling
        220136, -- Crystalline Sturgeon
        220135, -- Bloody Perch
        220134, -- Dilly-Dally Dace
        212508, -- Stunning Sapphire
        210936, -- Ironclaw Ore
        210933, -- Aqirite
        210930, -- Bismuth
    },
    -- https://www.wowhead.com/items?filter=87:194:166;3:1:10;0:1:0
    [10] = { -- Dragonflight
        204793, -- Suja's Sweet Salt
        203400, -- Lackluster Spices
        202710, -- Grilled Southfury Salmon
        202709, -- Spicy Seared Talbuk Steak
        202708, -- Curried Coconut Crab
        202707, -- Un'goro Coconut
        202706, -- Zandali Piri Piri
        202031, -- Farahlon Fenugreek
        202030, -- Ground Gorgrond Pepper
        202029, -- Isle Lemon
        202028, -- Southfury Salmon
        202027, -- Fresh Talbuk Steak
        202026, -- Durotar Coast Crab
        202025, -- Keg of Ancestral Ale
        200953, -- Wild Dragon Fruit
        200061, -- Prismatic Leaper
        199344, -- Magma Thresher
        197790, -- Roast Duck Delight
        197789, -- Riverside Picnic
        197788, -- Braised Bruffalon Brisket
        197787, -- Great Cerulean Sea
        197786, -- Thousandbone Tongueslicer
        197785, -- Revenge, Served Cold
        197784, -- Sizzling Seafood Medley
        197783, -- Aromatic Seafood Platter
        197782, -- Feisty Fish Sticks
        197776, -- Thrice-Spiced Mammoth Kabob
        197774, -- Charred Hornswog Steaks
        197770, -- Zesty Water
        197768, -- Celebratory Cake
        197767, -- Blubbery Muffin
        197766, -- Snow in a Cone
        197764, -- Salad on the Side
        197757, -- Assorted Exotic Spices
        197756, -- Pebbled Rock Salts
        197755, -- Lava Beetle
        197754, -- Salt Deposit
        197753, -- Thaldraszian Cocoa Powder
        197752, -- Conveniently Packaged Ingredients
        197751, -- Pastry Packets
        197750, -- Three-Cheese Blend
        197749, -- Ohn'ahran Potato
        197748, -- Burly Bear Haunch
        197747, -- Mighty Mammoth Ribs
        197746, -- Bruffalon Flank
        197745, -- Basilisk Eggs
        197744, -- Hornswog Hunk
        197743, -- Waterfowl Filet
        197742, -- Ribbed Mollusk Meat
        197741, -- Maybe Meat
        194970, -- Islefin Dorado
        194969, -- Temporal Dragonhead
        194968, -- Cerulean Spinefish
        194967, -- Aileron Seamoth
        194966, -- Thousandbite Piranha
        194829, -- Fated Fortune Card
        194730, -- Scalebelly Mackerel
        194691, -- Artisanal Berry Juice
        194683, -- Buttermilk
        193368, -- Silken Gemdust
        191464, -- Saxifrage
        191460, -- Hochenblume
        190395, -- Serevite Ore
        190312, -- Khaz'gorite Ore
        189143, -- Draconium Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;3:1:9;0:1:0
    [9] = { -- Shadowlands
        187812, -- Empty Kettle
        182101, -- Oat Pie Crust
        182100, -- Fresh Mushrooms
        182099, -- Fresh Turnips
        182098, -- Fresh Carrots
        182096, -- Ember Chilis
        182070, -- Fresh Beast Steak
        182069, -- Seared Cutlets
        182068, -- Ember Sauce
        182046, -- Grave Dust
        182045, -- Thick Spider Legs
        182044, -- Thick Spider Meat
        182024, -- Grazer Bones
        182023, -- Grazer Bone Broth
        182022, -- Diced Vegetables
        181988, -- Sack of Arden Oats
        181987, -- Fresh Arden Apples
        181986, -- Sliced Arden Apples
        179315, -- Shadowy Shank
        179314, -- Creeping Crawler Meat
        178786, -- Lusterwheat Flour
        177061, -- Twilight Bark
        173037, -- Elysian Thade
        173036, -- Spinefin Piranha
        173035, -- Pocked Bonefish
        173034, -- Silvergill Pike
        173033, -- Iridescent Amberjack
        173032, -- Lost Sole
        172092, -- Pallid Bone
        172059, -- Rich Grazer Milk
        172058, -- Smuggled Azerothian Produce
        172057, -- Inconceivably Aged Vinegar
        172056, -- Medley of Transplanar Spices
        172055, -- Phantasmal Haunch
        172054, -- Raw Seraphic Wing
        172053, -- Tenebrous Ribs
        172052, -- Aethereal Meat
        172049, -- Iridescent Ravioli with Apple Sauce
        171841, -- Shaded Stone
        171840, -- Porous Stone
        171829, -- Solenium Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;3:1:8;0:1:0
    [8] = { -- Battle for Azeroth
        174353, -- Questionable Meat
        174328, -- Aberrant Voidfin
        174327, -- Malformed Gnasher
        169610, -- S.P.A.R.E. Crate
        168646, -- Mauve Stinger
        168645, -- Moist Fillet
        168303, -- Rubbery Flank
        168302, -- Viper Fish
        167562, -- Ionized Minnow
        166846, -- Spare Parts
        163782, -- Cursed Haunch
        162555, -- Zocalo Cheddar
        162515, -- Midnight Salmon
        162461, -- Sanguicell
        160712, -- Powdered Sugar
        160711, -- Aromatic Fish Oil
        160710, -- Wild Berries
        160709, -- Fresh Potato
        160705, -- Major's Frothy Coffee
        160400, -- Foosaka
        160399, -- Wild Flour
        160398, -- Choral Honey
        154899, -- Thick Paleo Steak
        154898, -- Meaty Haunch
        154897, -- Stringy Loins
        154886, -- Spiced Snapper
        154885, -- Mon'Dazi
        154881, -- Kul Tiramisu
        152631, -- Briny Flesh
        152579, -- Storm Silver Ore
        152549, -- Redtail Loach
        152548, -- Tiragarde Perch
        152547, -- Great Sea Catfish
        152546, -- Lane Snapper
        152545, -- Frenzied Fangtooth
        152544, -- Slimy Mackerel
        152543, -- Sand Shifter
    },
    -- https://www.wowhead.com/items?filter=87:194:166;3:1:7;0:1:0
    [7] = { -- Legion
        142336, -- Falcosaur Egg
        138979, -- Spicy Sharp Cheddar
        133680, -- Slice of Bacon
        133607, -- Silver Mackerel
        133593, -- Royal Olive
        133592, -- Stonedark Snail
        133591, -- River Onion
        133590, -- Muskenbutter
        133589, -- Dalapeño Pepper
        133588, -- Flaked Sea Salt
        133569, -- Drogbar-Style Salmon
        133568, -- Koi-Scented Stormray
        133567, -- Barracuda Mrglgagh
        133566, -- Suramar Surf and Turf
        133565, -- Leybeque Ribs
        133564, -- Spiced Rib Roast
        133563, -- Faronaar Fizz
        133562, -- Pickled Stormray
        133561, -- Deep-Fried Mossgill
        133557, -- Salt and Pepper Shank
        129100, -- Gem Chip
        128304, -- Yseralline Seed
        124121, -- Wildfowl Egg
        124120, -- Leyblood
        124119, -- Big Gamy Ribs
        124118, -- Fatty Bearsteak
        124117, -- Lean Shank
        124112, -- Black Barracuda
        124111, -- Runescale Koi
        124110, -- Stormray
        124109, -- Highmountain Salmon
        124108, -- Mossgill Perch
        124107, -- Cursed Queenfish
        124105, -- Starlight Rose
        124104, -- Fjarnskaggl
        124103, -- Foxflower
        124102, -- Dreamleaf
        124101, -- Aethril
    },
    -- https://www.wowhead.com/items?filter=87:194:166;3:1:6;0:1:0
    [6] = { -- Warlords of Draenor
        128500, -- Fel Ham
        128499, -- Fel Egg
        124669, -- Darkmoon Daggermaw
        115352, -- Telmor-Aruuna Hard Cheese
        111449, -- Blackrock Barbecue
        111446, -- Skulker Chowder
        111445, -- Fiery Calamari
        111444, -- Fat Sleeper Cakes
        111442, -- Sturgeon Stew
        111441, -- Grilled Gulper
        111439, -- Steamed Scorpion
        111438, -- Clefthoof Sausages
        111437, -- Rylak Crepes
        111436, -- Braised Riverbeast
        111434, -- Pan-Seared Talbuk
        111433, -- Blackrock Ham
        111431, -- Hearty Elekk Steak
        109144, -- Blackwater Whiptail Flesh
        109143, -- Abyssal Gulper Eel Flesh
        109142, -- Sea Scorpion Segment
        109141, -- Fire Ammonite Tentacle
        109140, -- Blind Lake Sturgeon Flesh
        109139, -- Fat Sleeper Flesh
        109138, -- Jawless Skulker Flesh
        109137, -- Crescent Saberfish Flesh
        109136, -- Raw Boar Meat
        109135, -- Raw Riverbeast Meat
        109134, -- Raw Elekk Meat
        109133, -- Rylak Egg
        109132, -- Raw Talbuk Meat
        109131, -- Raw Clefthoof Meat
        109129, -- Talador Orchid
        109128, -- Nagrand Arrowbloom
        109127, -- Starflower
        109126, -- Gorgrond Flytrap
        109125, -- Fireweed
        109124, -- Frostweed
        109119, -- True Iron Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;3:1:5;0:1:0
    [5] = { -- Mists of Pandaria
        102543, -- Aged Mogu'shan Cheese
        102542, -- Ancient Pandaren Spices
        102541, -- Aged Balsamic Vinegar
        102540, -- Fresh Mangos
        102539, -- Fresh Strawberries
        102538, -- Fresh Shao-Tien Rice
        102537, -- Fresh Silkfeather Hawk Eggs
        102536, -- Fresh Lushroom
        85585, -- Red Beans
        85584, -- Silkworm Pupa
        85583, -- Needle Mushrooms
        85506, -- Viseclaw Meat
        79250, -- Fresh Pomfruit
        79246, -- Delicate Blossom Petals
        75038, -- Mad Brewer's Breakfast
        75037, -- Jade Witch Brew
        75026, -- Ginseng Tea
        75014, -- Raw Crocolisk Belly
        74866, -- Golden Carp
        74865, -- Krasarang Paddlefish
        74864, -- Reef Octopus
        74863, -- Jewel Danio
        74861, -- Tiger Gourami
        74860, -- Redbelly Mandarin
        74859, -- Emperor Salmon
        74857, -- Giant Mantis Shrimp
        74856, -- Jade Lungfish
        74854, -- Instant Noodles
        74853, -- 100 Year Soy Sauce
        74852, -- Yak Milk
        74851, -- Rice
        74850, -- White Turnip
        74849, -- Pink Turnip
        74848, -- Striped Melon
        74847, -- Jade Squash
        74846, -- Witchberries
        74845, -- Ginseng
        74844, -- Red Blossom Leek
        74843, -- Scallions
        74842, -- Mogu Pumpkin
        74841, -- Juicycrunch Carrot
        74840, -- Green Cabbage
        74839, -- Wildfowl Breast
        74838, -- Raw Crab Meat
        74837, -- Raw Turtle Meat
        74834, -- Mushan Ribs
        74833, -- Raw Tiger Steak
        74832, -- Barley
        74662, -- Rice Flour
        74661, -- Black Pepper
        74660, -- Pandaren Peach
        74659, -- Farm Chicken
        74656, -- Chun Tian Spring Rolls
        74655, -- Twin Fish Platter
        74654, -- Wildfowl Roast
        74653, -- Steamed Crab Surprise
        74652, -- Fire Spirit Salmon
        74651, -- Shrimp Dumplings
        74650, -- Mogu Fish Stew
        74649, -- Braised Turtle
        74648, -- Sea Mist Rice Noodles
        74647, -- Valley Stir Fry
        74646, -- Black Pepper Ribs and Shrimp
        74645, -- Eternal Blossom Fish
        74644, -- Swirling Mist Soup
        74643, -- Sauteed Carrots
        74642, -- Charbroiled Tiger Steak
    },
    -- https://www.wowhead.com/items?filter=87:194:166;3:1:4;0:1:0
    [4] = { -- Cataclysm
        67229, -- Stag Flank
        62791, -- Blood Shrimp
        62786, -- Cocoa Beans
        62785, -- Delicate Wing
        62784, -- Crocolisk Tail
        62783, -- Basilisk "Liver"
        62782, -- Dragon Flank
        62781, -- Giant Turtle Tongue
        62780, -- Snake Eye
        62779, -- Monstrous Claw
        62778, -- Toughened Flesh
        60838, -- Mysterious Fortune Card
        58278, -- Tropical Sunfruit
        58265, -- Highland Pomegranate
        53072, -- Deepsea Sagefish
        53071, -- Algaefin Rockfish
        53070, -- Fathom Eel
        53069, -- Murglesnout
        53068, -- Lavascale Catfish
        53067, -- Striped Lurker
        53066, -- Blackbelly Mudfish
        53064, -- Highland Guppy
        53063, -- Mountain Trout
        53062, -- Sharptooth
    },
    -- https://www.wowhead.com/items?filter=87:194:166;3:1:3;0:1:0
    [3] = { -- Wrath of the Lich King
        46797, -- Mulgore Sweet Potato
        46796, -- Ripe Tirisfal Pumpkin
        46793, -- Tangy Southfury Cranberries
        46784, -- Ripe Elwynn Pumpkin
        44855, -- Teldrassil Sweet Potato
        44854, -- Tangy Wetland Cranberries
        44853, -- Honey
        44835, -- Autumnal Herbs
        44834, -- Wild Turkey
        43501, -- Northern Egg
        43013, -- Chilled Meat
        43012, -- Rhino Meat
        43011, -- Worg Haunch
        43010, -- Worm Meat
        43009, -- Shoveltusk Flank
        43007, -- Northern Spices
        41813, -- Nettlefish
        41812, -- Barrelhead Goby
        41810, -- Fangtooth Herring
        41809, -- Glacial Salmon
        41808, -- Bonescale Snapper
        41807, -- Dragonfin Angelfish
        41806, -- Musselback Sculpin
        41805, -- Borean Man O' War
        41803, -- Rockfin Grouper
        41802, -- Imperial Manta Ray
        41801, -- Moonglow Cuttlefish
        41800, -- Deep Sea Monsterbelly
        36782, -- Succulent Clam Meat
        35949, -- Tundra Berries
        35948, -- Savory Snowplum
        34736, -- Chunk o' Mammoth
    },
    -- https://www.wowhead.com/items?filter=87:194:166;3:1:2;0:1:0
    [2] = { -- Burning Crusade
        35562, -- Bear Flank
        34412, -- Sparkling Apple Cider
        33824, -- Crescent-Tail Skullfish
        33823, -- Bloodfin Catfish
        31671, -- Serpent Flesh
        31670, -- Raptor Ribs
        30817, -- Simple Flour
        30816, -- Spice Bread
        27682, -- Talbuk Venison
        27681, -- Warped Flesh
        27678, -- Clefthoof Meat
        27677, -- Chunk o' Basilisk
        27674, -- Ravager Flesh
        27671, -- Buzzard Meat
        27669, -- Bat Flesh
        27668, -- Lynx Meat
        27516, -- Enormous Barbed Gill Trout
        27515, -- Huge Spotted Feltail
        27439, -- Furious Crawdad
        27438, -- Golden Darter
        27437, -- Icefin Bluefish
        27435, -- Figluster's Mudfish
        27429, -- Zangarian Sporefish
        27425, -- Spotted Feltail
        27422, -- Barbed Gill Trout
        24477, -- Jaggal Clam Meat
        23676, -- Moongraze Stag Tenderloin
        22644, -- Crunchy Spider Leg
        22577, -- Mote of Shadow
    },
    -- https://www.wowhead.com/items?filter=87:194:166;3:1:1;0:1:0
    [1] = { -- Vanilla
        21153, -- Raw Greater Sagefish
        21071, -- Raw Sagefish
        21024, -- Chimaerok Tenderloin
        20424, -- Sandworm Meat
        18255, -- Runn Tum Tuber
        17202, -- Snowball
        17196, -- Holiday Spirits
        17194, -- Holiday Spices
        13893, -- Large Raw Mightfish
        13889, -- Raw Whitescale Salmon
        13888, -- Darkclaw Lobster
        13760, -- Raw Sunscale Salmon
        13759, -- Raw Nightfin Snapper
        13758, -- Raw Redgill
        13757, -- Lightning Eel
        13756, -- Raw Summer Bass
        13755, -- Winter Squid
        13754, -- Raw Glossy Mightfish
        12808, -- Essence of Undeath
        12223, -- Meaty Bat Wing
        12208, -- Tender Wolf Meat
        12207, -- Giant Egg
        12206, -- Tender Crab Meat
        12205, -- White Spider Meat
        12204, -- Heavy Kodo Meat
        12203, -- Red Wolf Meat
        12202, -- Tiger Meat
        12184, -- Raptor Flesh
        12037, -- Mystery Meat
        9260, -- Volatile Rum
        9061, -- Goblin Rocket Fuel
        8365, -- Raw Mithril Head Trout
        8150, -- Deeprock Salt
        7974, -- Zesty Clam Meat
        6889, -- Small Egg
        6522, -- Deviate Fish
        6362, -- Raw Rockscale Cod
        6361, -- Raw Rainbow Fin Albacore
        6317, -- Raw Loch Frenzy
        6308, -- Raw Bristle Whisker Catfish
        6303, -- Raw Slitherskin Mackerel
        6291, -- Raw Brilliant Smallfish
        6289, -- Raw Longjaw Mud Snapper
        5504, -- Tangy Clam Meat
        5503, -- Clam Meat
        5471, -- Stag Meat
        5470, -- Thunder Lizard Tail
        5469, -- Strider Meat
        5468, -- Soft Frenzy Flesh
        5467, -- Kodo Meat
        5466, -- Scorpid Stinger
        5465, -- Small Spider Leg
        5051, -- Dig Rat
        4655, -- Giant Clam Meat
        4603, -- Raw Spotted Yellowtail
        4537, -- Tel'Abim Banana
        4402, -- Small Flame Sac
        3927, -- Fine Aged Cheddar
        3821, -- Goldthorn
        3731, -- Lion Meat
        3730, -- Big Bear Meat
        3712, -- Turtle Meat
        3685, -- Raptor Egg
        3667, -- Tender Crocolisk Meat
        3577, -- Gold Bar
        3404, -- Buzzard Wing
        3173, -- Bear Meat
        2924, -- Crocolisk Meat
        2886, -- Crag Boar Rib
        2678, -- Mild Spices
        2677, -- Boar Ribs
        2675, -- Crawler Claw
        2674, -- Crawler Meat
        2673, -- Coyote Meat
        2672, -- Stringy Wolf Meat
        2596, -- Skin of Dwarven Stout
        2595, -- Jug of Badlands Bourbon
        2594, -- Flagon of Dwarven Mead
        2593, -- Flask of Stormwind Tawny
        2452, -- Swiftthistle
        2447, -- Peacebloom
        2251, -- Gooey Spider Leg
        1468, -- Murloc Fin
        1179, -- Ice Cold Milk
        1080, -- Tough Condor Meat
        1015, -- Lean Wolf Flank
        785, -- Mageroyal
        769, -- Chunk of Boar Meat
        723, -- Goretusk Liver
        159, -- Refreshing Spring Water
    },
}
