-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 11:11:50

items.Elemental = {
    -- https://www.wowhead.com/items/trade-goods/elemental?filter=166;12;0
    [12] = { -- Midnight
    },
    -- https://www.wowhead.com/items/trade-goods/elemental?filter=166;11;0
    [11] = { -- The War Within
        231757, -- Fractured Spark of Starlight
        230905, -- Fractured Spark of Fortunes
        211297, -- Fractured Spark of Omens
    },
    -- https://www.wowhead.com/items/trade-goods/elemental?filter=166;10;0
    [10] = { -- Dragonflight
        211515, -- Splintered Spark of Awakening
        208396, -- Splintered Spark of Dreams
        205259, -- Order Soul
        204717, -- Splintered Spark of Shadowflame
        194729, -- Fiery Spirit
        194728, -- Fiery Spirit
        194727, -- Fiery Spirit
        193921, -- Airy Soul
        193920, -- Earthen Soul
        193919, -- Frosty Soul
        193379, -- Elemental Harmony
        193378, -- Elemental Harmony
        193362, -- Fiery Soul
        192887, -- Elemental Harmony
        191784, -- Dragon Shard of Knowledge
        190451, -- Rousing Ire
        190450, -- Awakened Ire
        190331, -- Awakened Decay
        190330, -- Rousing Decay
        190329, -- Awakened Frost
        190328, -- Rousing Frost
        190327, -- Awakened Air
        190326, -- Rousing Air
        190324, -- Awakened Order
        190322, -- Rousing Order
        190321, -- Awakened Fire
        190320, -- Rousing Fire
        190319, -- Resourceful!
        190318, -- Perception!
        190316, -- Awakened Earth
        190315, -- Rousing Earth
    },
    -- https://www.wowhead.com/items/trade-goods/elemental?filter=166;9;0
    [9] = { -- Shadowlands
        187707, -- Progenitor Essentia
        186017, -- Korthite Crystal
        178787, -- Orboreal Shard
    },
    -- https://www.wowhead.com/items/trade-goods/elemental?filter=166;8;0
    [8] = { -- Battle for Azeroth
        174097, -- [DNT] Corruptium
        165948, -- Tidalcore
        165703, -- Breath of Bwonsamdi
        163203, -- Hypersensitive Azeritometer Sensor
        162461, -- Sanguicell
        162460, -- Hydrocore
        152668, -- Expulsom
    },
    -- https://www.wowhead.com/items/trade-goods/elemental?filter=166;7;0
    [7] = { -- Legion
        151568, -- Primal Sargerite
        141323, -- Wild Transmutation
        124124, -- Blood of Sargeras
        124123, -- Demonfire
        124122, -- Leyfire
    },
    -- https://www.wowhead.com/items/trade-goods/elemental?filter=166;6;0
    [6] = { -- Warlords of Draenor
        120945, -- Primal Spirit
        113264, -- Sorcerous Air
        113263, -- Sorcerous Earth
        113262, -- Sorcerous Water
        113261, -- Sorcerous Fire
    },
    -- https://www.wowhead.com/items/trade-goods/elemental?filter=166;5;0
    [5] = { -- Mists of Pandaria
        89112, -- Mote of Harmony
        76061, -- Spirit of Harmony
    },
    -- https://www.wowhead.com/items/trade-goods/elemental?filter=166;4;0
    [4] = { -- Cataclysm
        54464, -- Random Volatile Element
        52329, -- Volatile Life
        52328, -- Volatile Air
        52327, -- Volatile Earth
        52326, -- Volatile Water
        52325, -- Volatile Fire
    },
    -- https://www.wowhead.com/items/trade-goods/elemental?filter=166;3;0
    [3] = { -- Wrath of the Lich King
        37705, -- Crystallized Water
        37704, -- Crystallized Life
        37703, -- Crystallized Shadow
        37702, -- Crystallized Fire
        37701, -- Crystallized Earth
        37700, -- Crystallized Air
        36860, -- Eternal Fire
        35627, -- Eternal Shadow
        35625, -- Eternal Life
        35624, -- Eternal Earth
        35623, -- Eternal Air
        35622, -- Eternal Water
    },
    -- https://www.wowhead.com/items/trade-goods/elemental?filter=166;2;0
    [2] = { -- Burning Crusade
        30183, -- Nether Vortex
        23572, -- Primal Nether
        23571, -- Primal Might
        22578, -- Mote of Water
        22577, -- Mote of Shadow
        22576, -- Mote of Mana
        22575, -- Mote of Life
        22574, -- Mote of Fire
        22573, -- Mote of Earth
        22572, -- Mote of Air
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
    },
    -- https://www.wowhead.com/items/trade-goods/elemental?filter=166;1;0
    [1] = { -- Vanilla
        12808, -- Essence of Undeath
        12803, -- Living Essence
        10286, -- Heart of the Wild
        7972, -- Ichor of Undeath
        7082, -- Essence of Air
        7081, -- Breath of Wind
        7080, -- Essence of Water
        7079, -- Globe of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7075, -- Core of Earth
        7070, -- Elemental Water
        7069, -- Elemental Air
        7068, -- Elemental Fire
        7067, -- Elemental Earth
    },
}
