-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 10:24:10

items.Enchanting = {
    -- https://www.wowhead.com/items?filter=87:194:166;4:1:12;0:1:0
    [12] = { -- Midnight
        274781, -- Cursebound Globe
        274777, -- Neutralized Venom Clot
        251665, -- Silverleaf Thread
        251285, -- Petrified Root
        251283, -- Tormented Tantalum
        245882, -- Thalassian Songwater
        245881, -- Lexicologist's Vellum
        245805, -- Sienna Ink
        245801, -- Munsell Ink
        245345, -- Fused Vitality
        244637, -- Silvermoon Weapon Wrap
        243605, -- Dawn Crystal
        243602, -- Radiant Shard
        243599, -- Eversinging Dust
        243060, -- Luminant Flux
        242788, -- Dusk-Shrouded Stone
        242787, -- Crystalline Glass
        242612, -- Flawless Amani Lapis
        242611, -- Flawless Tenebrous Amethyst
        242610, -- Flawless Harandar Peridot
        240991, -- Sunglass Vial
        239201, -- Sunfire Silk Bolt
        239198, -- Arcanoweave Bolt
        238530, -- Majestic Fin
        238529, -- Majestic Hide
        238528, -- Majestic Claw
        238525, -- Fantastic Fur
        238523, -- Carving Canine
        238522, -- Peerless Plumage
        238383, -- Eversong Trout
        238204, -- Sterling Alloy
        238202, -- Gloaming Alloy
        238197, -- Refulgent Copper Ingot
        237366, -- Dazzling Thorium
        237364, -- Brilliant Silver Ore
        236952, -- Mote of Pure Void
        236951, -- Mote of Wild Magic
        236950, -- Mote of Primal Energy
        236949, -- Mote of Light
        236774, -- Azeroot
    },
    -- https://www.wowhead.com/items?filter=87:194:166;4:1:11;0:1:0
    [11] = { -- The War Within
        256963, -- Thalassian Lumber
        251773, -- Dragonpine Lumber
        251772, -- Arden Lumber
        251768, -- Darkpine Lumber
        251767, -- Fel-Touched Lumber
        251766, -- Shadowmoon Lumber
        251764, -- Ashwood Lumber
        251763, -- Bamboo Lumber
        251762, -- Coldwind Lumber
        249218, -- Manaforged Instrument
        248012, -- Dornic Fir Lumber
        245586, -- Ironwood Lumber
        242691, -- Olemba Lumber
        224108, -- Oil of Beledar's Grace
        222555, -- Codified Greenwood
        222417, -- Core Alloy
        221859, -- Gyrating Gear
        221763, -- Viridian Charmcap
        221758, -- Profaned Tinderbox
        221756, -- Vial of Kaheti Oils
        221754, -- Ringing Deeps Ingot
        220790, -- Nascent Runed Harbinger Crest
        220789, -- Nascent Gilded Harbinger Crest
        220788, -- Nascent Weathered Harbinger Crest
        219952, -- Refulgent Crystal
        219949, -- Gleaming Shard
        219946, -- Storm Dust
        218338, -- Bottled Storm
        213613, -- Leyline Residue
        213612, -- Viridescent Spores
        213611, -- Writhing Sample
        213610, -- Crystalline Powder
        210939, -- Null Stone
        210814, -- Artisan's Acuity
    },
    -- https://www.wowhead.com/items?filter=87:194:166;4:1:10;0:1:0
    [10] = { -- Dragonflight
        211523, -- Nascent Whelpling's Awakened Crest
        211522, -- Nascent Aspect's Awakened Crest
        211521, -- Nascent Wyrm's Awakened Crest
        208395, -- Nascent Whelpling's Dreaming Crest
        208394, -- Nascent Wyrm's Dreaming Crest
        208393, -- Nascent Aspect's Dreaming Crest
        208212, -- Dreaming Essence
        205263, -- Empowered Flightstone
        204464, -- Shadowflame Essence
        204463, -- Dracothyst
        204460, -- Zaralek Glowspores
        204196, -- Wyrm's Shadowflame Crest
        204194, -- Aspect's Shadowflame Crest
        204193, -- Whelpling's Shadowflame Crest
        203401, -- Dull Crystal
        201584, -- Serevite Rod
        201406, -- Glowing Titan Orb
        201401, -- Iridescent Plume
        200113, -- Resonant Crystal
        194862, -- Runed Writhebark
        194784, -- Glittering Parchment
        194727, -- Fiery Spirit
        194124, -- Vibrant Shard
        194123, -- Chromatic Dust
        193922, -- Wildercloth
        192869, -- Illimited Diamond
        191470, -- Writhebark
        190456, -- Artisan's Mettle
        190329, -- Awakened Frost
        190328, -- Rousing Frost
        190327, -- Awakened Air
        190326, -- Rousing Air
        190324, -- Awakened Order
        190322, -- Rousing Order
        190321, -- Awakened Fire
        190320, -- Rousing Fire
        190316, -- Awakened Earth
        190315, -- Rousing Earth
        190312, -- Khaz'gorite Ore
        189541, -- Primal Molten Alloy
        189143, -- Draconium Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;4:1:9;0:1:0
    [9] = { -- Shadowlands
        187703, -- Silken Protofiber
        187700, -- Progenium Ore
        183951, -- Immortal Shard
        182066, -- Sanguine Crystal
        182042, -- Necrotic Essence
        182020, -- Transcendent Dust
        181990, -- Twilight Dust
        177061, -- Twilight Bark
        173204, -- Lightless Silk
        172232, -- Eternal Crystal
        172231, -- Sacred Shard
        172230, -- Soul Dust
        172097, -- Heavy Callous Hide
        171833, -- Elethium Ore
        171832, -- Sinvyr Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;4:1:8;0:1:0
    [8] = { -- Battle for Azeroth
        168185, -- Osmenite Ore
        168127, -- Lingering Drust Essence
        165948, -- Tidalcore
        165703, -- Breath of Bwonsamdi
        162461, -- Sanguicell
        162460, -- Hydrocore
        158186, -- Distilled Water
        154165, -- Calcified Bone
        152877, -- Veiled Crystal
        152876, -- Umbra Shard
        152875, -- Gloom Dust
        152812, -- Monel-Hardened Hoofplates
        152668, -- Expulsom
        152541, -- Coarse Leather
    },
    -- https://www.wowhead.com/items?filter=87:194:166;4:1:7;0:1:0
    [7] = { -- Legion
        156930, -- Rich Illusion Dust
        127835, -- Ancient Mana Potion
        124461, -- Demonsteel Bar
        124444, -- Infernal Brimstone
        124442, -- Chaos Crystal
        124441, -- Leylight Shard
        124440, -- Arkhana
        124124, -- Blood of Sargeras
        124116, -- Felhide
        124106, -- Felwort
    },
    -- https://www.wowhead.com/items?filter=87:194:166;4:1:6;0:1:0
    [6] = { -- Warlords of Draenor
        120945, -- Primal Spirit
        118472, -- Savage Blood
        113588, -- Temporal Crystal
        113264, -- Sorcerous Air
        113263, -- Sorcerous Earth
        113262, -- Sorcerous Water
        113261, -- Sorcerous Fire
        111557, -- Sumptuous Fur
        111245, -- Luminous Shard
        109693, -- Draenic Dust
        109118, -- Blackrock Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;4:1:5;0:1:0
    [5] = { -- Mists of Pandaria
        94289, -- Haunting Spirit
        76142, -- Sun's Radiance
        76141, -- Imperial Amethyst
        76140, -- Vermilion Onyx
        76139, -- Wild Jade
        76138, -- River's Heart
        76131, -- Primordial Ruby
        76061, -- Spirit of Harmony
        74250, -- Mysterious Essence
        74249, -- Spirit Dust
        74248, -- Sha Crystal
        74247, -- Ethereal Shard
        72988, -- Windwool Cloth
    },
    -- https://www.wowhead.com/items?filter=87:194:166;4:1:4;0:1:0
    [4] = { -- Cataclysm
        69237, -- Living Ember
        58094, -- Elixir of Impossible Accuracy
        53039, -- Hardened Elementium Bar
        52722, -- Maelstrom Crystal
        52721, -- Heavenly Shard
        52719, -- Greater Celestial Essence
        52718, -- Lesser Celestial Essence
        52555, -- Hypnotic Dust
        52329, -- Volatile Life
        52328, -- Volatile Air
        52327, -- Volatile Earth
        52326, -- Volatile Water
        52325, -- Volatile Fire
    },
    -- https://www.wowhead.com/items?filter=87:194:166;4:1:3;0:1:0
    [3] = { -- Wrath of the Lich King
        44958, -- Ethereal Oil
        41510, -- Bolt of Frostweave
        41163, -- Titanium Bar
        39354, -- Light Parchment
        38682, -- Enchanting Vellum
        37705, -- Crystallized Water
        37663, -- Titansteel Bar
        36918, -- Scarlet Ruby
        36860, -- Eternal Fire
        35625, -- Eternal Life
        35624, -- Eternal Earth
        35623, -- Eternal Air
        35622, -- Eternal Water
        34057, -- Abyss Crystal
        34056, -- Lesser Cosmic Essence
        34055, -- Greater Cosmic Essence
        34054, -- Infinite Dust
        34052, -- Dream Shard
    },
    -- https://www.wowhead.com/items?filter=87:194:166;4:1:2;0:1:0
    [2] = { -- Burning Crusade
        23571, -- Primal Might
        23427, -- Eternium Ore
        22824, -- Elixir of Major Strength
        22794, -- Fel Lotus
        22792, -- Nightmare Vine
        22791, -- Netherbloom
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        22450, -- Void Crystal
        22449, -- Large Prismatic Shard
        22448, -- Small Prismatic Shard
        22447, -- Lesser Planar Essence
        22446, -- Greater Planar Essence
        22445, -- Arcane Dust
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
    },
    -- https://www.wowhead.com/items?filter=87:194:166;4:1:1;0:1:0
    [1] = { -- Vanilla
        20520, -- Dark Rune
        20002, -- Greater Dreamless Sleep Potion
        19931, -- Gurubashi Mojo Madness
        17056, -- Light Feather
        17010, -- Fiery Core
        16204, -- Light Illusion Dust
        16203, -- Greater Eternal Essence
        16202, -- Lesser Eternal Essence
        14344, -- Large Brilliant Shard
        14343, -- Small Brilliant Shard
        14256, -- Felcloth
        13926, -- Golden Pearl
        13467, -- Icecap
        13446, -- Major Healing Potion
        13444, -- Major Mana Potion
        12811, -- Righteous Orb
        12808, -- Essence of Undeath
        12803, -- Living Essence
        12800, -- Azerothian Diamond
        12655, -- Enchanted Thorium Bar
        12365, -- Dense Stone
        12359, -- Thorium Bar
        11291, -- Star Wood
        10940, -- Strange Dust
        10939, -- Greater Magic Essence
        10938, -- Lesser Magic Essence
        9224, -- Elixir of Demonslaying
        8838, -- Sungrass
        8831, -- Purple Lotus
        8170, -- Rugged Leather
        8153, -- Wildvine
        7909, -- Aquamarine
        7392, -- Green Whelp Scale
        7082, -- Essence of Air
        7080, -- Essence of Water
        7078, -- Essence of Fire
        7076, -- Essence of Earth
        7067, -- Elemental Earth
        6370, -- Blackmouth Oil
        6037, -- Truesilver Bar
        5637, -- Large Fang
        4625, -- Firebloom
        4470, -- Simple Wood
        3857, -- Coal
        3819, -- Dragon's Teeth
        3371, -- Crystal Vial
        3356, -- Kingsblood
        2772, -- Iron Ore
    },
}
