-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 10:29:04

items.Engineering = {
    -- https://www.wowhead.com/items?filter=87:194:166;5:1:12;0:1:0
    [12] = { -- Midnight
        274777, -- Neutralized Venom Clot
        253303, -- Pile of Junk
        253302, -- Malleable Wireframe
        251283, -- Tormented Tantalum
        245345, -- Fused Vitality
        243581, -- Evercore
        243578, -- Aetherlume
        243576, -- Soul Sprocket
        243574, -- Song Gear
        239702, -- Imbued Bright Linen Bolt
        238530, -- Majestic Fin
        238529, -- Majestic Hide
        238528, -- Majestic Claw
        238520, -- Void-Tempered Plating
        238518, -- Void-Tempered Hide
        237366, -- Dazzling Thorium
        237362, -- Umbral Tin Ore
        237359, -- Refulgent Copper Ore
        236952, -- Mote of Pure Void
        236951, -- Mote of Wild Magic
        236950, -- Mote of Primal Energy
        236949, -- Mote of Light
    },
    -- https://www.wowhead.com/items?filter=87:194:166;5:1:11;0:1:0
    [11] = { -- The War Within
        256963, -- Thalassian Lumber
        251773, -- Dragonpine Lumber
        251772, -- Arden Lumber
        251768, -- Darkpine Lumber
        251767, -- Fel-Touched Lumber
        251766, -- Shadowmoon Lumber
        251764, -- Ashwood Lumber
        251763, -- Bamboo Lumber
        251762, -- Coldwind Lumber
        248012, -- Dornic Fir Lumber
        245586, -- Ironwood Lumber
        242691, -- Olemba Lumber
        228956, -- Junk Bucket
        228414, -- Frayed Wiring
        227774, -- Pummel Permit
        227773, -- Pummel-Proof Plating
        227772, -- Cataclysmic Converter
        227771, -- Blinker Fluid
        227770, -- Assorted Whirligigs
        227769, -- Bountiful Bolts
        222801, -- Dawnweave Bolt
        222798, -- Duskweave Bolt
        222420, -- Charged Alloy
        222417, -- Core Alloy
        221868, -- Entropy Enhancer
        221865, -- Chaos Circuit
        221862, -- Safety Switch
        221859, -- Gyrating Gear
        221856, -- Whimsical Wiring
        221853, -- Handful of Bismuth Bolts
        221756, -- Vial of Kaheti Oils
        219892, -- Leyfused Hide
        219889, -- Sporecoated Hide
        219886, -- Writhing Hide
        219883, -- Crystalfused Hide
        219150, -- Pile of Rusted Scrap
        213753, -- Decorative Lens
        213613, -- Leyline Residue
        213611, -- Writhing Sample
        213610, -- Crystalline Powder
        213399, -- Glittering Glass
        212511, -- Ostentatious Onyx
        212508, -- Stunning Sapphire
        212505, -- Extravagant Emerald
        212498, -- Ambivalent Amber
        212495, -- Radiant Ruby
        212266, -- Potion of the Reborn Cheetah
        212263, -- Tempered Potion
        212242, -- Cavedweller's Delight
        211878, -- Algari Healing Potion
        211806, -- Gilded Vial
        210939, -- Null Stone
        210936, -- Ironclaw Ore
        210933, -- Aqirite
        210930, -- Bismuth
        210814, -- Artisan's Acuity
    },
    -- https://www.wowhead.com/items?filter=87:194:166;5:1:10;0:1:0
    [10] = { -- Dragonflight
        207702, -- Wartorn Scrap
        205260, -- Fleeting Glowspores
        205257, -- Temporal Vestigial
        204464, -- Shadowflame Essence
        204463, -- Dracothyst
        203402, -- Broken Gnomish Voicebox
        201832, -- Smudged Lens
        201406, -- Glowing Titan Orb
        198487, -- Iridescent Water
        198278, -- Primal Deconstruction Charge
        198228, -- Gravitational Displacer
        198201, -- Assorted Safety Fuses
        198198, -- Reinforced Machine Chassis
        198195, -- Arclight Capacitor
        198192, -- Greased-Up Gears
        198189, -- Everburning Blasting Powder
        198186, -- Shock-Spring Coil
        198183, -- Handful of Serevite Bolts
        197768, -- Celebratory Cake
        194727, -- Fiery Spirit
        193932, -- Infurious Wildercloth Bolt
        193929, -- Vibrant Wildercloth Bolt
        193922, -- Wildercloth
        193921, -- Airy Soul
        193920, -- Earthen Soul
        193919, -- Frosty Soul
        193362, -- Fiery Soul
        193248, -- Infurious Scales
        193245, -- Frostbite Scales
        193236, -- Infurious Hide
        193229, -- Mireslush Hide
        193226, -- Stonecrust Hide
        193222, -- Lustrous Scaled Hide
        193216, -- Dense Hide
        193213, -- Adamant Scales
        193208, -- Resilient Leather
        193053, -- Contoured Fowlfeather
        192887, -- Elemental Harmony
        192876, -- Frameless Lens
        192862, -- Neltharite
        192856, -- Malygite
        192849, -- Eternity Amber
        192846, -- Sundered Onyx
        192843, -- Vibrant Emerald
        192840, -- Mystic Sapphire
        192837, -- Queen's Ruby
        191496, -- Omnium Draconis
        191474, -- Draconic Vial
        191396, -- Potion of Gusts
        191393, -- Potion of the Hushed Zephyr
        191378, -- Refreshing Healing Potion
        190536, -- Infurious Alloy
        190533, -- Obsidian Seared Alloy
        190530, -- Frostfire Alloy
        190456, -- Artisan's Mettle
        190450, -- Awakened Ire
        190395, -- Serevite Ore
        190330, -- Rousing Decay
        190328, -- Rousing Frost
        190327, -- Awakened Air
        190326, -- Rousing Air
        190324, -- Awakened Order
        190321, -- Awakened Fire
        190320, -- Rousing Fire
        190316, -- Awakened Earth
        190315, -- Rousing Earth
        190312, -- Khaz'gorite Ore
        189143, -- Draconium Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;5:1:9;0:1:0
    [9] = { -- Shadowlands
        187707, -- Progenitor Essentia
        187703, -- Silken Protofiber
        187700, -- Progenium Ore
        183952, -- Machinist's Oil
        183951, -- Immortal Shard
        182064, -- Machined Sinvyr Bar
        182063, -- Sinvyr Trigger Mechanism
        182062, -- Sinvyr Barrel
        182040, -- Machined Oxxein Bar
        182039, -- Handful of Oxxein Bolts
        182038, -- Bone Reinforced Oxxein Tubing
        182018, -- Machined Solenium Bar
        182017, -- Hardened Bolts
        182016, -- Piston Assembly
        181994, -- Machined Phaedrum Bar
        181993, -- Energized Battery
        181992, -- Electro Cable
        180733, -- Luminous Flux
        178787, -- Orboreal Shard
        177062, -- Penumbra Thread
        177061, -- Twilight Bark
        173202, -- Shrouded Cloth
        173173, -- Essence of Valor
        173110, -- Umbryl
        173109, -- Angerseye
        173108, -- Oriblase
        172937, -- Wormfed Gear Assembly
        172936, -- Mortal Coiled Spring
        172935, -- Porous Polishing Abrasive
        172934, -- Handful of Laestrite Bolts
        172903, -- Nutcracker Grenade
        172231, -- Sacred Shard
        172230, -- Soul Dust
        172092, -- Pallid Bone
        172089, -- Desolate Leather
        171841, -- Shaded Stone
        171840, -- Porous Stone
        171833, -- Elethium Ore
        171832, -- Sinvyr Ore
        171831, -- Phaedrum Ore
        171830, -- Oxxein Ore
        171829, -- Solenium Ore
        171828, -- Laestrite Ore
        171441, -- Laestrite Skeleton Key
        171428, -- Shadowghast Ingot
    },
    -- https://www.wowhead.com/items?filter=87:194:166;5:1:8;0:1:0
    [8] = { -- Battle for Azeroth
        170553, -- Void Focus Splinter
        168185, -- Osmenite Ore
        168152, -- Miniaturized Power Core
        166970, -- Energy Cell
        165948, -- Tidalcore
        165703, -- Breath of Bwonsamdi
        163569, -- Insulated Wiring
        162461, -- Sanguicell
        162460, -- Hydrocore
        161137, -- Blast-Fired Electric Servomotor
        161136, -- Azerite Forged Protection Plating
        161132, -- Crush Resistant Stabilizer
        160502, -- Chemical Blasting Cap
        154124, -- Laribole
        154123, -- Amberblaze
        152668, -- Expulsom
        152579, -- Storm Silver Ore
        152513, -- Platinum Ore
        152512, -- Monelite Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;5:1:7;0:1:0
    [7] = { -- Legion
        151568, -- Primal Sargerite
        151564, -- Empyrium
        144329, -- Hardened Felglass
        140785, -- Hardened Circuitboard Plating
        140781, -- X-87 Battle Circuit
        137642, -- Mark of Honor
        136638, -- True Iron Barrel
        136637, -- Oversized Blasting Cap
        136636, -- Sniping Scope
        136633, -- Loose Trigger
        132523, -- Reaves Battery
        132515, -- Failure Detection Pylon
        132514, -- Auto-Hammer
        130183, -- Shadowruby
        130178, -- Furystone
        127004, -- Imbued Silkweave
        124461, -- Demonsteel Bar
        124444, -- Infernal Brimstone
        124437, -- Shal'dorei Silk
        124124, -- Blood of Sargeras
        124121, -- Wildfowl Egg
        124119, -- Big Gamy Ribs
        124116, -- Felhide
        124115, -- Stormscale
        124113, -- Stonehide Leather
        124112, -- Black Barracuda
        124109, -- Highmountain Salmon
        124106, -- Felwort
        123919, -- Felslate
        123918, -- Leystone Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;5:1:6;0:1:0
    [6] = { -- Warlords of Draenor
        127759, -- Felblight
        120945, -- Primal Spirit
        118472, -- Savage Blood
        114931, -- Cerulean Pigment
        113588, -- Temporal Crystal
        113264, -- Sorcerous Air
        111557, -- Sumptuous Fur
        111366, -- Gearspring Parts
        109128, -- Nagrand Arrowbloom
        109119, -- True Iron Ore
        109118, -- Blackrock Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;5:1:5;0:1:0
    [5] = { -- Mists of Pandaria
        94113, -- Jard's Peculiar Energy Source
        90146, -- Tinker's Kit
        87872, -- Desecrated Oil
        83092, -- Orb of Mystery
        77531, -- Mirror Scope
        77529, -- Lord Blastington's Scope of Doom
        77468, -- High-Explosive Gunpowder
        77467, -- Ghost Iron Bolts
        76142, -- Sun's Radiance
        76140, -- Vermilion Onyx
        76139, -- Wild Jade
        76138, -- River's Heart
        76133, -- Lapis Lazuli
        76132, -- Primal Diamond
        76131, -- Primordial Ruby
        76061, -- Spirit of Harmony
        72988, -- Windwool Cloth
        72104, -- Living Steel
        72096, -- Ghost Iron Bar
        72095, -- Trillium Bar
        72093, -- Kyparite
    },
    -- https://www.wowhead.com/items?filter=87:194:166;5:1:4;0:1:0
    [4] = { -- Cataclysm
        67749, -- Electrified Ether
        62778, -- Toughened Flesh
        62654, -- Lavascale Fillet
        60224, -- Handful of Obsidium Bolts
        58480, -- Truegold
        54849, -- Obsidium Bar
        53039, -- Hardened Elementium Bar
        53010, -- Embersilk Cloth
        52976, -- Savage Leather
        52328, -- Volatile Air
        52327, -- Volatile Earth
        52325, -- Volatile Fire
        52192, -- Dream Emerald
        52191, -- Ocean Sapphire
        52190, -- Inferno Ruby
        52186, -- Elementium Bar
        52182, -- Jasper
        52181, -- Hessonite
        52179, -- Alicite
        52078, -- Chaos Orb
    },
    -- https://www.wowhead.com/items?filter=87:194:166;5:1:3;0:1:0
    [3] = { -- Wrath of the Lich King
        44501, -- Goblin-Machined Piston
        44500, -- Elementium-Plated Exhaust Pipe
        44499, -- Salvaged Iron Golem Parts
        44128, -- Arctic Fur
        43102, -- Frozen Orb
        41163, -- Titanium Bar
        41146, -- Sun Scope
        40769, -- Scrapbot Construction Kit
        40533, -- Walnut Stock
        39690, -- Volatile Blasting Trigger
        39684, -- Hair Trigger
        39683, -- Froststeel Tube
        39682, -- Overcharged Capacitor
        39681, -- Handful of Cobalt Bolts
        39354, -- Light Parchment
        38425, -- Heavy Borean Leather
        37705, -- Crystallized Water
        37702, -- Crystallized Fire
        37701, -- Crystallized Earth
        37663, -- Titansteel Bar
        36933, -- Forest Emerald
        36930, -- Monarch Topaz
        36927, -- Twilight Opal
        36924, -- Sky Sapphire
        36922, -- King's Amber
        36921, -- Autumn's Glow
        36920, -- Sun Crystal
        36918, -- Scarlet Ruby
        36916, -- Cobalt Bar
        36913, -- Saronite Bar
        36860, -- Eternal Fire
        35627, -- Eternal Shadow
        35625, -- Eternal Life
        35624, -- Eternal Earth
        35623, -- Eternal Air
        35622, -- Eternal Water
        34052, -- Dream Shard
        33568, -- Borean Leather
        33470, -- Frostweave Cloth
    },
    -- https://www.wowhead.com/items?filter=87:194:166;5:1:2;0:1:0
    [2] = { -- Burning Crusade
        35128, -- Hardened Khorium
        34113, -- Field Repair Bot 110G
        32423, -- Icy Blasting Primers
        24272, -- Shadowcloth
        24271, -- Spellcloth
        23826, -- The Bigger One
        23793, -- Heavy Knothide Leather
        23787, -- Felsteel Stabilizer
        23786, -- Khorium Power Core
        23785, -- Hardened Adamantite Tube
        23784, -- Adamantite Frame
        23783, -- Handful of Fel Iron Bolts
        23782, -- Fel Iron Casing
        23781, -- Elemental Blasting Powder
        23573, -- Hardened Adamantite Bar
        23572, -- Primal Nether
        23571, -- Primal Might
        23449, -- Khorium Bar
        23448, -- Felsteel Bar
        23446, -- Adamantite Bar
        23445, -- Fel Iron Bar
        23441, -- Nightseye
        23440, -- Dawnstone
        23439, -- Noble Topaz
        23438, -- Star of Elune
        23437, -- Talasite
        23436, -- Living Ruby
        23112, -- Golden Draenite
        23079, -- Deep Peridot
        23077, -- Blood Garnet
        22832, -- Super Mana Potion
        22829, -- Super Healing Potion
        22574, -- Mote of Fire
        22573, -- Mote of Earth
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        22449, -- Large Prismatic Shard
        22448, -- Small Prismatic Shard
        22445, -- Arcane Dust
        21929, -- Flame Spessarite
        21887, -- Knothide Leather
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
        21877, -- Netherweave Cloth
        21840, -- Bolt of Netherweave
    },
    -- https://www.wowhead.com/items?filter=87:194:166;5:1:1;0:1:0
    [1] = { -- Vanilla
        18631, -- Truesilver Transformer
        18232, -- Field Repair Bot 74A
        17202, -- Snowball
        17011, -- Lava Core
        17010, -- Fiery Core
        16006, -- Delicate Arcanite Converter
        16000, -- Thorium Tube
        15994, -- Thorium Widget
        15992, -- Dense Blasting Powder
        15407, -- Cured Rugged Hide
        14227, -- Ironweb Spider Silk
        14048, -- Bolt of Runecloth
        14047, -- Runecloth
        13467, -- Icecap
        12810, -- Enchanted Leather
        12808, -- Essence of Undeath
        12804, -- Powerful Mojo
        12803, -- Living Essence
        12800, -- Azerothian Diamond
        12799, -- Large Opal
        12655, -- Enchanted Thorium Bar
        12365, -- Dense Stone
        12364, -- Huge Emerald
        12361, -- Blue Sapphire
        12360, -- Arcanite Bar
        12359, -- Thorium Bar
        11371, -- Dark Iron Bar
        11291, -- Star Wood
        10647, -- Engineer's Ink
        10592, -- Catseye Elixir
        10586, -- The Big One
        10561, -- Mithril Casing
        10560, -- Unstable Trigger
        10559, -- Mithril Tube
        10558, -- Gold Power Core
        10546, -- Deadly Scope
        10507, -- Solid Dynamite
        10505, -- Solid Blasting Powder
        10286, -- Heart of the Wild
        10285, -- Shadow Silk
        9318, -- Red Firework
        9313, -- Green Firework
        9312, -- Blue Firework
        9061, -- Goblin Rocket Fuel
        9060, -- Inlaid Mithril Cylinder
        8170, -- Rugged Leather
        8153, -- Wildvine
        8150, -- Deeprock Salt
        7972, -- Ichor of Undeath
        7912, -- Solid Stone
        7910, -- Star Ruby
        7909, -- Aquamarine
        7191, -- Fused Wiring
        7082, -- Essence of Air
        7080, -- Essence of Water
        7079, -- Globe of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7075, -- Core of Earth
        7069, -- Elemental Air
        7068, -- Elemental Fire
        7067, -- Elemental Earth
        6530, -- Nightcrawlers
        6037, -- Truesilver Bar
        4611, -- Blue Pearl
        4470, -- Simple Wood
        4407, -- Accurate Scope
        4406, -- Standard Scope
        4404, -- Silver Contact
        4402, -- Small Flame Sac
        4400, -- Heavy Stock
        4399, -- Wooden Stock
        4394, -- Big Iron Bomb
        4389, -- Gyrochronatom
        4387, -- Iron Strut
        4382, -- Bronze Framework
        4377, -- Heavy Blasting Powder
        4375, -- Whirring Bronze Gizmo
        4371, -- Bronze Tube
        4364, -- Coarse Blasting Powder
        4359, -- Handful of Copper Bolts
        4357, -- Rough Blasting Powder
        4342, -- Purple Dye
        4339, -- Bolt of Mageweave
        4338, -- Mageweave Cloth
        4337, -- Thick Spider's Silk
        4306, -- Silk Cloth
        4304, -- Thick Leather
        4234, -- Heavy Leather
        3864, -- Citrine
        3860, -- Mithril Bar
        3859, -- Steel Bar
        3857, -- Coal
        3829, -- Frost Oil
        3577, -- Gold Bar
        3575, -- Iron Bar
        2842, -- Silver Bar
        2841, -- Bronze Bar
        2840, -- Copper Bar
        2838, -- Heavy Stone
        2836, -- Coarse Stone
        2835, -- Rough Stone
        2605, -- Green Dye
        2592, -- Wool Cloth
        2589, -- Linen Cloth
        2319, -- Medium Leather
        2318, -- Light Leather
        1705, -- Lesser Moonstone
        1529, -- Jade
        1210, -- Shadowgem
        1206, -- Moss Agate
        818, -- Tigerseye
        814, -- Flask of Oil
        774, -- Malachite
        159, -- Refreshing Spring Water
    },
}
