-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 16:54:44

items.Herbalism = {
    -- https://www.wowhead.com/items?filter=70:194:217:166;1:1:1:12;0:1:0:0
    [12] = { -- Midnight
        274781, -- Cursebound Globe
        242640, -- Plant Protein
        236952, -- Mote of Pure Void
        236951, -- Mote of Wild Magic
        236950, -- Mote of Primal Energy
        236949, -- Mote of Light
        236780, -- Nocturnal Lotus
        236779, -- Mana Lily
        236778, -- Mana Lily
        236777, -- Argentleaf
        236776, -- Argentleaf
        236775, -- Azeroot
        236774, -- Azeroot
        236771, -- Sanguithorn
        236770, -- Sanguithorn
        236767, -- Tranquility Bloom
        236761, -- Tranquility Bloom
    },
    -- https://www.wowhead.com/items?filter=70:194:217:166;1:1:1:11;0:1:0:0
    [11] = { -- The War Within
        240194, -- K'areshi Lotus
        239692, -- Phantom Bloom
        239691, -- Phantom Bloom
        239690, -- Phantom Bloom
        213613, -- Leyline Residue
        213612, -- Viridescent Spores
        213611, -- Writhing Sample
        213610, -- Crystalline Powder
        213197, -- Null Lotus
        210810, -- Arathor's Spear
        210809, -- Arathor's Spear
        210808, -- Arathor's Spear
        210807, -- Blessing Blossom
        210806, -- Blessing Blossom
        210805, -- Blessing Blossom
        210804, -- Orbinid
        210803, -- Orbinid
        210802, -- Orbinid
        210801, -- Luredrop
        210800, -- Luredrop
        210799, -- Luredrop
        210798, -- Mycobloom
        210797, -- Mycobloom
        210796, -- Mycobloom
    },
    -- https://www.wowhead.com/items?filter=70:194:217:166;1:1:1:10;0:1:0:0
    [10] = { -- Dragonflight
        204460, -- Zaralek Glowspores
        197755, -- Lava Beetle
        191472, -- Writhebark
        191471, -- Writhebark
        191470, -- Writhebark
        191469, -- Bubble Poppy
        191468, -- Bubble Poppy
        191467, -- Bubble Poppy
        191466, -- Saxifrage
        191465, -- Saxifrage
        191464, -- Saxifrage
        191462, -- Hochenblume
        191461, -- Hochenblume
        191460, -- Hochenblume
        190451, -- Rousing Ire
        190330, -- Rousing Decay
        190328, -- Rousing Frost
        190326, -- Rousing Air
        190322, -- Rousing Order
        190315, -- Rousing Earth
    },
    -- https://www.wowhead.com/items?filter=70:194:217:166;1:1:1:9;0:1:0:0
    [9] = { -- Shadowlands
        187707, -- Progenitor Essentia
        187699, -- First Flower
        170554, -- Vigil's Torch
    },
    -- https://www.wowhead.com/items?filter=70:194:217:166;1:1:1:8;0:1:0:0
    [8] = { -- Battle for Azeroth
        171315, -- Nightshade
        169701, -- Death Blossom
        169697, -- Nightshade Petal
        168589, -- Marrowroot
        168586, -- Rising Glory
        168583, -- Widowbloom
        168487, -- Zin'anthid
        163601, -- Overgrown Anchor Weed
        163595, -- Flourishing Riverbud
        163588, -- Flourishing Sea Stalk
        152511, -- Sea Stalk
        152510, -- Anchor Weed
        152509, -- Siren's Pollen
        152508, -- Winter's Kiss
        152507, -- Akunda's Bite
        152506, -- Star Moss
        152505, -- Riverbud
    },
    -- https://www.wowhead.com/items?filter=70:194:217:166;1:1:1:7;0:1:0:0
    [7] = { -- Legion
        151568, -- Primal Sargerite
        151565, -- Astral Glory
        135500, -- Singed Fjarnskaggl
        129289, -- Felwort Seed
        129288, -- Starlight Rose Seed
        129287, -- Fjarnskaggl Seed
        129286, -- Foxflower Seed
        129285, -- Dreamleaf Seed
        129284, -- Aethril Seed
        128304, -- Yseralline Seed
        124124, -- Blood of Sargeras
        124106, -- Felwort
        124105, -- Starlight Rose
        124104, -- Fjarnskaggl
        124103, -- Foxflower
        124102, -- Dreamleaf
        124101, -- Aethril
    },
    -- https://www.wowhead.com/items?filter=70:194:217:166;1:1:1:6;0:1:0:0
    [6] = { -- Warlords of Draenor
        127759, -- Felblight
        120945, -- Primal Spirit
        116053, -- Draenic Seeds
        109629, -- Talador Orchid Petal
        109628, -- Nagrand Arrowbloom Petal
        109627, -- Starflower Petal
        109626, -- Gorgrond Flytrap Ichor
        109625, -- Broken Fireweed Stem
        109624, -- Broken Frostweed Stem
        109129, -- Talador Orchid
        109128, -- Nagrand Arrowbloom
        109127, -- Starflower
        109126, -- Gorgrond Flytrap
        109125, -- Fireweed
        109124, -- Frostweed
        108365, -- Whiptail Stem
        108363, -- Heartblossom Petal
        108361, -- Stormvine Stalk
        108360, -- Cinderbloom Petal
        108359, -- Fire Leaf Bramble
        108357, -- Talandra's Rose Petal
        108356, -- Icethorn Bramble
        108355, -- Lichbloom Stalk
        108354, -- Tiger Lily Petal
        108353, -- Adder's Tongue Stem
        108352, -- Goldclover Leaf
        108351, -- Mana Thistle Leaf
        108350, -- Nightmare Vine Stem
        108349, -- Netherbloom Leaf
        108348, -- Ancient Lichen Petal
        108347, -- Terocone Leaf
        108346, -- Ragveil Cap
        108345, -- Dreaming Glory Petal
        108344, -- Felweed Stalk
        108343, -- Icecap Petal
        108342, -- Sorrowmoss Leaf
        108341, -- Mountain Silversage Stalk
        108340, -- Golden Sansam Leaf
        108339, -- Dreamfoil Blade
        108338, -- Gromsblood Leaf
        108337, -- Ghost Mushroom Cap
        108336, -- Blindweed Stem
        108335, -- Sungrass Stalk
        108333, -- Purple Lotus Petal
        108332, -- Firebloom Petal
        108331, -- Goldthorn Bramble
        108330, -- Stranglekelp Blade
        108329, -- Dragon's Teeth Stem
        108328, -- Fadeleaf Petal
        108327, -- Grave Moss Leaf
        108326, -- Khadgar's Whisker Stem
        108325, -- Liferoot Stem
        108324, -- Kingsblood Petal
        108323, -- Wild Steelbloom Petal
    },
    -- https://www.wowhead.com/items?filter=70:194:217:166;1:1:1:5;0:1:0:0
    [5] = { -- Mists of Pandaria
        97624, -- Desecrated Herb Pod
        97623, -- Fool's Cap Spores
        97622, -- Snow Lily Petal
        97621, -- Silkweed Stem
        97620, -- Rain Poppy Petal
        97619, -- Torn Green Tea Leaf
        89639, -- Desecrated Herb
        79011, -- Fool's Cap
        79010, -- Snow Lily
        72238, -- Golden Lotus
        72237, -- Rain Poppy
        72235, -- Silkweed
        72234, -- Green Tea Leaf
    },
    -- https://www.wowhead.com/items?filter=70:194:217:166;1:1:1:4;0:1:0:0
    [4] = { -- Cataclysm
        52988, -- Whiptail
        52987, -- Twilight Jasmine
        52986, -- Heartblossom
        52985, -- Azshara's Veil
        52984, -- Stormvine
        52983, -- Cinderbloom
        52329, -- Volatile Life
    },
    -- https://www.wowhead.com/items?filter=70:194:217:166;1:1:1:3;0:1:0:0
    [3] = { -- Wrath of the Lich King
        39970, -- Fire Leaf
        37921, -- Deadnettle
        37704, -- Crystallized Life
        36908, -- Frost Lotus
        36907, -- Talandra's Rose
        36906, -- Icethorn
        36905, -- Lichbloom
        36904, -- Tiger Lily
        36903, -- Adder's Tongue
        36901, -- Goldclover
    },
    -- https://www.wowhead.com/items?filter=70:194:217:166;1:1:1:2;0:1:0:0
    [2] = { -- Burning Crusade
        22794, -- Fel Lotus
        22793, -- Mana Thistle
        22792, -- Nightmare Vine
        22791, -- Netherbloom
        22790, -- Ancient Lichen
        22789, -- Terocone
        22787, -- Ragveil
        22786, -- Dreaming Glory
        22785, -- Felweed
        22576, -- Mote of Mana
        22575, -- Mote of Life
    },
    -- https://www.wowhead.com/items?filter=70:194:217:166;1:1:1:1;0:1:0:0
    [1] = { -- Vanilla
        13468, -- Black Lotus
        13467, -- Icecap
        13466, -- Sorrowmoss
        13465, -- Mountain Silversage
        13464, -- Golden Sansam
        13463, -- Dreamfoil
        8846, -- Gromsblood
        8845, -- Ghost Mushroom
        8839, -- Blindweed
        8838, -- Sungrass
        8831, -- Purple Lotus
        8153, -- Wildvine
        4625, -- Firebloom
        3821, -- Goldthorn
        3820, -- Stranglekelp
        3819, -- Dragon's Teeth
        3818, -- Fadeleaf
        3369, -- Grave Moss
        3358, -- Khadgar's Whisker
        3357, -- Liferoot
        3356, -- Kingsblood
        3355, -- Wild Steelbloom
        2453, -- Bruiseweed
        2452, -- Swiftthistle
        2450, -- Briarthorn
        2449, -- Earthroot
        2447, -- Peacebloom
        818, -- Tigerseye
        785, -- Mageroyal
        774, -- Malachite
        765, -- Silverleaf
    },
}
