-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 10:53:47

items.Inscription = {
    -- https://www.wowhead.com/items?filter=87:194:166;15:1:12;0:1:0
    [12] = { -- Midnight
        274781, -- Cursebound Globe
        274777, -- Neutralized Venom Clot
        251923, -- Thalassian Essence of the Faire
        251285, -- Petrified Root
        251283, -- Tormented Tantalum
        245882, -- Thalassian Songwater
        245881, -- Lexicologist's Vellum
        245879, -- Vantus Rune: Radiant
        245867, -- Mana Lily Pigment
        245865, -- Sanguithorn Pigment
        245807, -- Powder Pigment
        245805, -- Sienna Ink
        245803, -- Argentleaf Pigment
        245801, -- Munsell Ink
        245766, -- Soul Cipher
        245764, -- Codified Azeroot
        245345, -- Fused Vitality
        242788, -- Dusk-Shrouded Stone
        238530, -- Majestic Fin
        238529, -- Majestic Hide
        238528, -- Majestic Claw
        236952, -- Mote of Pure Void
        236951, -- Mote of Wild Magic
        236950, -- Mote of Primal Energy
        236949, -- Mote of Light
        236774, -- Azeroot
    },
    -- https://www.wowhead.com/items?filter=87:194:166;15:1:11;0:1:0
    [11] = { -- The War Within
        256963, -- Thalassian Lumber
        251773, -- Dragonpine Lumber
        251772, -- Arden Lumber
        251768, -- Darkpine Lumber
        251767, -- Fel-Touched Lumber
        251766, -- Shadowmoon Lumber
        251764, -- Ashwood Lumber
        251763, -- Bamboo Lumber
        251762, -- Coldwind Lumber
        249218, -- Manaforged Instrument
        248012, -- Dornic Fir Lumber
        245586, -- Ironwood Lumber
        242691, -- Olemba Lumber
        226205, -- Distilled Algari Freshwater
        226204, -- Fresh Parchment
        224805, -- Blossom Pigment
        224802, -- Orbinid Pigment
        222618, -- Nacreous Pigment
        222615, -- Apricate Ink
        222612, -- Luredrop Pigment
        222609, -- Shadow Ink
        222558, -- Boundless Cipher
        222555, -- Codified Greenwood
        222523, -- Coreforged Skeleton Key
        222417, -- Core Alloy
        221754, -- Ringing Deeps Ingot
        213613, -- Leyline Residue
        213612, -- Viridescent Spores
        213611, -- Writhing Sample
        213610, -- Crystalline Powder
        212664, -- Stormcharged Leather
        212508, -- Stunning Sapphire
        210814, -- Artisan's Acuity
        210808, -- Arathor's Spear
    },
    -- https://www.wowhead.com/items?filter=87:194:166;15:1:10;0:1:0
    [10] = { -- Dragonflight
        204464, -- Shadowflame Essence
        204460, -- Zaralek Glowspores
        204092, -- Auric Fleece
        203865, -- Brilliant Wizard Oil
        203403, -- Hastily Scrawled Rune
        198615, -- Pentagold Seal
        198487, -- Iridescent Water
        198421, -- Shimmering Pigment
        198418, -- Blazing Pigment
        198415, -- Flourishing Pigment
        198412, -- Serene Pigment
        197736, -- Finished Prototype Regal Barding
        197735, -- Finished Prototype Explorer's Barding
        194862, -- Runed Writhebark
        194859, -- Chilled Rune
        194856, -- Serene Ink
        194850, -- Flourishing Ink
        194784, -- Glittering Parchment
        194760, -- Burnished Ink
        194754, -- Cosmic Ink
        194751, -- Blazing Ink
        194727, -- Fiery Spirit
        193922, -- Wildercloth
        193259, -- Flawless Proto Dragon Scale
        193254, -- Rockfang Leather
        193053, -- Contoured Fowlfeather
        192872, -- Fractured Glass
        191474, -- Draconic Vial
        191470, -- Writhebark
        190456, -- Artisan's Mettle
        190450, -- Awakened Ire
        190395, -- Serevite Ore
        190331, -- Awakened Decay
        190329, -- Awakened Frost
        190328, -- Rousing Frost
        190327, -- Awakened Air
        190326, -- Rousing Air
        190324, -- Awakened Order
        190321, -- Awakened Fire
        190316, -- Awakened Earth
        190315, -- Rousing Earth
        190312, -- Khaz'gorite Ore
        189143, -- Draconium Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;15:1:9;0:1:0
    [9] = { -- Shadowlands
        187701, -- Protogenic Pelt
        187699, -- First Flower
        183953, -- Sealing Wax
        182309, -- Rigid Vellum
        182297, -- Flayed Flesh
        182286, -- Twilight Parchment
        182202, -- Borrowed Parchment
        182061, -- Prideful Pigment
        182060, -- Prideful Ink
        182059, -- Scroll of Castigation
        182037, -- Necrotic Pigment
        182036, -- Necrotic Ink
        182035, -- Scroll of Unyielding Strength
        182015, -- Opalescent Pigment
        182014, -- Opalescent Ink
        182013, -- Poem on Duty
        181997, -- Ardenberry Pigment
        181996, -- Ardenberry Ink
        181995, -- Scroll of Calming Lyrics
        180732, -- Rune Etched Vial
        177843, -- Blank Card of Putrescence
        177842, -- Blank Card of Repose
        177841, -- Blank Card of Voracity
        177840, -- Blank Card of the Indomitable
        177061, -- Twilight Bark
        175970, -- Tranquil Ink
        175886, -- Dark Parchment
        175788, -- Tranquil Pigment
        173204, -- Lightless Silk
        173202, -- Shrouded Cloth
        173172, -- Essence of Servitude
        173170, -- Essence of Rebirth
        173126, -- Straddling Jewel Doublet
        173110, -- Umbryl
        173060, -- Aerated Water
        173059, -- Luminous Ink
        173058, -- Umbral Ink
        173057, -- Luminous Pigment
        173056, -- Umbral Pigment
        172230, -- Soul Dust
        172092, -- Pallid Bone
        171832, -- Sinvyr Ore
        171829, -- Solenium Ore
        171828, -- Laestrite Ore
        170554, -- Vigil's Torch
    },
    -- https://www.wowhead.com/items?filter=87:194:166;15:1:8;0:1:0
    [8] = { -- Battle for Azeroth
        171315, -- Nightshade
        169701, -- Death Blossom
        168663, -- Maroon Ink
        168662, -- Maroon Pigment
        168589, -- Marrowroot
        168586, -- Rising Glory
        168583, -- Widowbloom
        168487, -- Zin'anthid
        168142, -- Coagulated Miasma
        165948, -- Tidalcore
        165703, -- Breath of Bwonsamdi
        162460, -- Hydrocore
        160712, -- Powdered Sugar
        160711, -- Aromatic Fish Oil
        160398, -- Choral Honey
        158205, -- Acacia Powder
        158189, -- Viridescent Ink
        158188, -- Crimson Ink
        158187, -- Ultramarine Ink
        158186, -- Distilled Water
        153669, -- Viridescent Pigment
        153636, -- Crimson Pigment
        153635, -- Ultramarine Pigment
        152668, -- Expulsom
        152576, -- Tidespray Linen
        152512, -- Monelite Ore
        152511, -- Sea Stalk
        152510, -- Anchor Weed
        152509, -- Siren's Pollen
        152508, -- Winter's Kiss
        152507, -- Akunda's Bite
        152506, -- Star Moss
        152505, -- Riverbud
    },
    -- https://www.wowhead.com/items?filter=87:194:166;15:1:7;0:1:0
    [7] = { -- Legion
        151565, -- Astral Glory
        129100, -- Gem Chip
        129034, -- Sallow Pigment
        129032, -- Roseate Pigment
        128304, -- Yseralline Seed
        127004, -- Imbued Silkweave
        124461, -- Demonsteel Bar
        124437, -- Shal'dorei Silk
        124124, -- Blood of Sargeras
        124106, -- Felwort
        124105, -- Starlight Rose
        124104, -- Fjarnskaggl
        124103, -- Foxflower
        124102, -- Dreamleaf
        124101, -- Aethril
    },
    -- https://www.wowhead.com/items?filter=87:194:166;15:1:6;0:1:0
    [6] = { -- Warlords of Draenor
        127759, -- Felblight
        120945, -- Primal Spirit
        118472, -- Savage Blood
        114931, -- Cerulean Pigment
        113509, -- Conjured Mana Bun
        113263, -- Sorcerous Earth
        113261, -- Sorcerous Fire
        113111, -- Warbinder's Ink
        112377, -- War Paints
        111557, -- Sumptuous Fur
        109129, -- Talador Orchid
        109128, -- Nagrand Arrowbloom
        109127, -- Starflower
        109126, -- Gorgrond Flytrap
        109125, -- Fireweed
        109124, -- Frostweed
        109119, -- True Iron Ore
        109118, -- Blackrock Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;15:1:5;0:1:0
    [5] = { -- Mists of Pandaria
        87872, -- Desecrated Oil
        82441, -- Bolt of Windwool Cloth
        79731, -- Scroll of Wisdom
        79255, -- Starlight Ink
        79254, -- Ink of Dreams
        79253, -- Misty Pigment
        79251, -- Shadow Pigment
        76061, -- Spirit of Harmony
        72237, -- Rain Poppy
        72104, -- Living Steel
        72096, -- Ghost Iron Bar
    },
    -- https://www.wowhead.com/items?filter=87:194:166;15:1:4;0:1:0
    [4] = { -- Cataclysm
        67335, -- Silver Charm Bracelet
        67319, -- Preserved Ogre Eye
        62323, -- Deathwing Scale Fragment
        61981, -- Inferno Ink
        61980, -- Burning Embers
        61979, -- Ashen Pigment
        61978, -- Blackfallow Ink
        56850, -- Deepstone Oil
        55053, -- Obsidium Skeleton Key
        54849, -- Obsidium Bar
        52329, -- Volatile Life
        52328, -- Volatile Air
        52327, -- Volatile Earth
        52326, -- Volatile Water
        52325, -- Volatile Fire
        52186, -- Elementium Bar
    },
    -- https://www.wowhead.com/items?filter=87:194:166;15:1:3;0:1:0
    [3] = { -- Wrath of the Lich King
        43127, -- Snowfall Ink
        43126, -- Ink of the Sea
        43125, -- Darkflame Ink
        43124, -- Ethereal Ink
        43123, -- Ink of the Sky
        43122, -- Shimmering Ink
        43121, -- Fiery Ink
        43120, -- Celestial Ink
        43119, -- Royal Ink
        43118, -- Jadefire Ink
        43117, -- Dawnstar Ink
        43116, -- Lion's Ink
        43115, -- Hunter's Ink
        43109, -- Icy Pigment
        43108, -- Ebon Pigment
        43107, -- Sapphire Pigment
        43106, -- Ruby Pigment
        43105, -- Indigo Pigment
        43104, -- Burnt Pigment
        43103, -- Verdant Pigment
        43102, -- Frozen Orb
        41163, -- Titanium Bar
        39774, -- Midnight Ink
        39469, -- Moonglow Ink
        39354, -- Light Parchment
        39343, -- Azure Pigment
        39342, -- Nether Pigment
        39341, -- Silvery Pigment
        39340, -- Violet Pigment
        39339, -- Emerald Pigment
        39338, -- Golden Pigment
        39334, -- Dusky Pigment
        39151, -- Alabaster Pigment
        37663, -- Titansteel Bar
        36931, -- Ametrine
        36916, -- Cobalt Bar
        35627, -- Eternal Shadow
        35625, -- Eternal Life
        33458, -- Scroll of Intellect VI
    },
    -- https://www.wowhead.com/items?filter=87:194:166;15:1:2;0:1:0
    [2] = { -- Burning Crusade
        23793, -- Heavy Knothide Leather
        23449, -- Khorium Bar
        22457, -- Primal Mana
        22452, -- Primal Earth
        22446, -- Greater Planar Essence
        21886, -- Primal Life
        20963, -- Mithril Filigree
    },
    -- https://www.wowhead.com/items?filter=87:194:166;15:1:1;0:1:0
    [1] = { -- Vanilla
        22682, -- Frozen Rune
        20520, -- Dark Rune
        20002, -- Greater Dreamless Sleep Potion
        19943, -- Massive Mojo
        19931, -- Gurubashi Mojo Madness
        19767, -- Primal Bat Leather
        18335, -- Pristine Black Diamond
        14344, -- Large Brilliant Shard
        13512, -- Flask of Supreme Power
        12811, -- Righteous Orb
        12810, -- Enchanted Leather
        12808, -- Essence of Undeath
        12804, -- Powerful Mojo
        12800, -- Azerothian Diamond
        12799, -- Large Opal
        12365, -- Dense Stone
        12364, -- Huge Emerald
        12361, -- Blue Sapphire
        12360, -- Arcanite Bar
        12359, -- Thorium Bar
        10308, -- Scroll of Intellect IV
        7076, -- Essence of Earth
        6037, -- Truesilver Bar
        4470, -- Simple Wood
        3577, -- Gold Bar
        3371, -- Crystal Vial
        2841, -- Bronze Bar
    },
}
