-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 10:50:25

items.Jewelcrafting = {
    -- https://www.wowhead.com/items?filter=87:194:166;7:1:12;0:1:0
    [12] = { -- Midnight
        274781, -- Cursebound Globe
        274777, -- Neutralized Venom Clot
        253307, -- Infused Heliotrope
        251665, -- Silverleaf Thread
        251285, -- Petrified Root
        251283, -- Tormented Tantalum
        245345, -- Fused Vitality
        244637, -- Silvermoon Weapon Wrap
        244633, -- Infused Scalewoven Hide
        243605, -- Dawn Crystal
        242788, -- Dusk-Shrouded Stone
        242787, -- Crystalline Glass
        242620, -- Glimmering Gemdust
        242613, -- Flawless Sanguine Garnet
        242612, -- Flawless Amani Lapis
        242611, -- Flawless Tenebrous Amethyst
        242610, -- Flawless Harandar Peridot
        242608, -- Eversong Diamond
        242607, -- Harandar Peridot
        242606, -- Tenebrous Amethyst
        242554, -- Amani Lapis
        242553, -- Sanguine Garnet
        240974, -- Kaleidoscopic Prism
        240972, -- Sin'dorei Lens
        238529, -- Majestic Hide
        238518, -- Void-Tempered Hide
        237362, -- Umbral Tin Ore
        237359, -- Refulgent Copper Ore
        236952, -- Mote of Pure Void
        236951, -- Mote of Wild Magic
        236950, -- Mote of Primal Energy
        236949, -- Mote of Light
    },
    -- https://www.wowhead.com/items?filter=87:194:166;7:1:11;0:1:0
    [11] = { -- The War Within
        256963, -- Thalassian Lumber
        251773, -- Dragonpine Lumber
        251772, -- Arden Lumber
        251768, -- Darkpine Lumber
        251767, -- Fel-Touched Lumber
        251766, -- Shadowmoon Lumber
        251764, -- Ashwood Lumber
        251763, -- Bamboo Lumber
        251762, -- Coldwind Lumber
        248012, -- Dornic Fir Lumber
        245586, -- Ironwood Lumber
        242691, -- Olemba Lumber
        239107, -- Black Blood Infused Bar
        239106, -- Shadow-Infused Onyx
        222417, -- Core Alloy
        221754, -- Ringing Deeps Ingot
        219949, -- Gleaming Shard
        215236, -- Vicious Bloodstone
        213759, -- Inverted Prism
        213756, -- Marbled Stone
        213753, -- Decorative Lens
        213750, -- Engraved Gemcutter
        213399, -- Glittering Glass
        213398, -- Handful of Pebbles
        213219, -- Crushed Gemstones
        212514, -- Blasphemite
        212511, -- Ostentatious Onyx
        212508, -- Stunning Sapphire
        212505, -- Extravagant Emerald
        212498, -- Ambivalent Amber
        212495, -- Radiant Ruby
        210939, -- Null Stone
        210936, -- Ironclaw Ore
        210933, -- Aqirite
        210930, -- Bismuth
        210814, -- Artisan's Acuity
    },
    -- https://www.wowhead.com/items?filter=87:194:166;7:1:10;0:1:0
    [10] = { -- Dragonflight
        210456, -- Dreaming Antler Fragment
        208212, -- Dreaming Essence
        207702, -- Wartorn Scrap
        205258, -- Everburning Shadowflame
        205257, -- Temporal Vestigial
        204463, -- Dracothyst
        204215, -- Dormant Primordial Fragment
        203404, -- Crystal Fork
        201406, -- Glowing Titan Orb
        201405, -- Tuft of Primal Wool
        200867, -- Glimmering Neltharite Cluster
        200866, -- Glimmering Malygite Cluster
        200865, -- Glimmering Ysemerald Cluster
        200864, -- Glimmering Alexstraszite Cluster
        200863, -- Glimmering Nozdorite Cluster
        200860, -- Draconic Stopper
        200113, -- Resonant Crystal
        194730, -- Scalebelly Mackerel
        194727, -- Fiery Spirit
        194124, -- Vibrant Shard
        194123, -- Chromatic Dust
        193929, -- Vibrant Wildercloth Bolt
        193922, -- Wildercloth
        193921, -- Airy Soul
        193920, -- Earthen Soul
        193919, -- Frosty Soul
        193368, -- Silken Gemdust
        193362, -- Fiery Soul
        193053, -- Contoured Fowlfeather
        193029, -- Projection Prism
        192887, -- Elemental Harmony
        192883, -- Glossy Stone
        192880, -- Crumbled Stone
        192876, -- Frameless Lens
        192872, -- Fractured Glass
        192869, -- Illimited Diamond
        192866, -- Nozdorite
        192862, -- Neltharite
        192859, -- Ysemerald
        192856, -- Malygite
        192852, -- Alexstraszite
        192849, -- Eternity Amber
        192846, -- Sundered Onyx
        192843, -- Vibrant Emerald
        192840, -- Mystic Sapphire
        192837, -- Queen's Ruby
        192834, -- Shimmering Clasp
        192833, -- Misshapen Filigree
        191493, -- Primal Convergent
        190456, -- Artisan's Mettle
        190451, -- Rousing Ire
        190450, -- Awakened Ire
        190395, -- Serevite Ore
        190329, -- Awakened Frost
        190328, -- Rousing Frost
        190327, -- Awakened Air
        190326, -- Rousing Air
        190324, -- Awakened Order
        190321, -- Awakened Fire
        190320, -- Rousing Fire
        190316, -- Awakened Earth
        190315, -- Rousing Earth
        190312, -- Khaz'gorite Ore
        189143, -- Draconium Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;7:1:9;0:1:0
    [9] = { -- Shadowlands
        187707, -- Progenitor Essentia
        187700, -- Progenium Ore
        186017, -- Korthite Crystal
        183954, -- Malleable Wire
        182308, -- Garnet Shard
        182289, -- Handful of Glimmering Gemstones
        182197, -- Borrowed Kyranite
        182058, -- Polished Sinvyr Bar
        182057, -- Fine Sinvyr Chain
        182056, -- Brilliant Bauble
        182034, -- Jagged Necrotic Crystal
        182033, -- Faceted Crystal
        182032, -- Hollowed Crystal
        182012, -- Borrowed Solenium Nugget
        182011, -- Solenium Wire
        182010, -- Kyranite Dangle
        182000, -- Polished Phedrum Rod
        181999, -- Polished Gemstones
        181998, -- Engraved Phaedrum Band
        178787, -- Orboreal Shard
        173173, -- Essence of Valor
        173172, -- Essence of Servitude
        173171, -- Essence of Torment
        173170, -- Essence of Rebirth
        173168, -- Laestrite Setting
        173130, -- Masterful Jewel Cluster
        173129, -- Versatile Jewel Cluster
        173128, -- Quick Jewel Cluster
        173127, -- Deadly Jewel Cluster
        173124, -- Masterful Jewel Doublet
        173123, -- Versatile Jewel Doublet
        173122, -- Quick Jewel Doublet
        173121, -- Deadly Jewel Doublet
        173110, -- Umbryl
        173109, -- Angerseye
        173108, -- Oriblase
        172232, -- Eternal Crystal
        172230, -- Soul Dust
        171841, -- Shaded Stone
        171840, -- Porous Stone
        171833, -- Elethium Ore
        171832, -- Sinvyr Ore
        171831, -- Phaedrum Ore
        171830, -- Oxxein Ore
        171829, -- Solenium Ore
        171828, -- Laestrite Ore
        171428, -- Shadowghast Ingot
    },
    -- https://www.wowhead.com/items?filter=87:194:166;7:1:8;0:1:0
    [8] = { -- Battle for Azeroth
        170553, -- Void Focus Splinter
        168635, -- Leviathan's Eye
        168193, -- Azsharine
        168192, -- Sand Spinel
        168191, -- Sea Currant
        168190, -- Lava Lazuli
        168189, -- Dark Opal
        168188, -- Sage Agate
        168185, -- Osmenite Ore
        168134, -- Fine Azerite Powder
        165948, -- Tidalcore
        165703, -- Breath of Bwonsamdi
        162461, -- Sanguicell
        162460, -- Hydrocore
        158187, -- Ultramarine Ink
        154125, -- Royal Quartz
        154124, -- Laribole
        154123, -- Amberblaze
        154122, -- Tidal Amethyst
        154121, -- Scarlet Diamond
        154120, -- Owlseye
        153706, -- Kraken's Eye
        153705, -- Kyanite
        153704, -- Viridium
        153703, -- Solstone
        153702, -- Kubiline
        153701, -- Rubellite
        153700, -- Golden Beryl
        152668, -- Expulsom
        152579, -- Storm Silver Ore
        152513, -- Platinum Ore
        152512, -- Monelite Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;7:1:7;0:1:0
    [7] = { -- Legion
        151933, -- Empyrial Florid Malachite Setting
        151932, -- Empyrial Hesselian Setting
        151722, -- Florid Malachite
        151721, -- Hesselian
        151720, -- Chemirine
        151719, -- Lightsphene
        151718, -- Argulite
        151579, -- Labradorite
        151568, -- Primal Sargerite
        151564, -- Empyrium
        130245, -- Saber's Eye
        130183, -- Shadowruby
        130182, -- Maelstrom Sapphire
        130181, -- Pandemonite
        130180, -- Dawnlight
        130179, -- Eye of Prophecy
        130178, -- Furystone
        130177, -- Queen's Opal
        130176, -- Skystone
        130175, -- Chaotic Spinel
        130174, -- Azsunite
        130173, -- Deep Amber
        130172, -- Sangrite
        129100, -- Gem Chip
        127004, -- Imbued Silkweave
        124461, -- Demonsteel Bar
        124444, -- Infernal Brimstone
        124124, -- Blood of Sargeras
        124106, -- Felwort
        123919, -- Felslate
        123918, -- Leystone Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;7:1:6;0:1:0
    [6] = { -- Warlords of Draenor
        127759, -- Felblight
        120945, -- Primal Spirit
        115815, -- Greater Stamina Taladite
        115814, -- Greater Versatility Taladite
        115812, -- Greater Mastery Taladite
        115811, -- Greater Haste Taladite
        115809, -- Greater Critical Strike Taladite
        115808, -- Stamina Taladite
        115807, -- Versatility Taladite
        115805, -- Mastery Taladite
        115804, -- Haste Taladite
        115803, -- Critical Strike Taladite
        115524, -- Taladite Crystal
        113264, -- Sorcerous Air
        113263, -- Sorcerous Earth
        113262, -- Sorcerous Water
        113261, -- Sorcerous Fire
        111557, -- Sumptuous Fur
        109129, -- Talador Orchid
        109127, -- Starflower
        109126, -- Gorgrond Flytrap
        109125, -- Fireweed
        109124, -- Frostweed
        109119, -- True Iron Ore
        109118, -- Blackrock Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;7:1:5;0:1:0
    [5] = { -- Mists of Pandaria
        83092, -- Orb of Mystery
        76734, -- Serpent's Eye
        76142, -- Sun's Radiance
        76141, -- Imperial Amethyst
        76140, -- Vermilion Onyx
        76139, -- Wild Jade
        76138, -- River's Heart
        76137, -- Alexandrite
        76136, -- Pandarian Garnet
        76135, -- Roguestone
        76134, -- Sunstone
        76133, -- Lapis Lazuli
        76132, -- Primal Diamond
        76131, -- Primordial Ruby
        76130, -- Tiger Opal
        76061, -- Spirit of Harmony
        72104, -- Living Steel
        72096, -- Ghost Iron Bar
        72095, -- Trillium Bar
    },
    -- https://www.wowhead.com/items?filter=87:194:166;7:1:4;0:1:0
    [4] = { -- Cataclysm
        71810, -- Elven Peridot
        71809, -- Shadow Spinel
        71808, -- Lava Coral
        71807, -- Deepholm Iolite
        71806, -- Lightstone
        71805, -- Queen's Garnet
        58480, -- Truegold
        54849, -- Obsidium Bar
        53010, -- Embersilk Cloth
        52555, -- Hypnotic Dust
        52329, -- Volatile Life
        52328, -- Volatile Air
        52327, -- Volatile Earth
        52326, -- Volatile Water
        52325, -- Volatile Fire
        52303, -- Shadowspirit Diamond
        52196, -- Chimera's Eye
        52195, -- Amberjewel
        52194, -- Demonseye
        52193, -- Ember Topaz
        52192, -- Dream Emerald
        52191, -- Ocean Sapphire
        52190, -- Inferno Ruby
        52188, -- Jeweler's Setting
        52186, -- Elementium Bar
        52182, -- Jasper
        52181, -- Hessonite
        52180, -- Nightstone
        52179, -- Alicite
        52178, -- Zephyrite
        52177, -- Carnelian
        52078, -- Chaos Orb
    },
    -- https://www.wowhead.com/items?filter=87:194:166;7:1:3;0:1:0
    [3] = { -- Wrath of the Lich King
        43102, -- Frozen Orb
        42225, -- Dragon's Eye
        41334, -- Earthsiege Diamond
        41266, -- Skyflare Diamond
        41163, -- Titanium Bar
        37701, -- Crystallized Earth
        36934, -- Eye of Zul
        36933, -- Forest Emerald
        36932, -- Dark Jade
        36931, -- Ametrine
        36930, -- Monarch Topaz
        36929, -- Huge Citrine
        36928, -- Dreadstone
        36927, -- Twilight Opal
        36926, -- Shadow Crystal
        36925, -- Majestic Zircon
        36924, -- Sky Sapphire
        36923, -- Chalcedony
        36922, -- King's Amber
        36921, -- Autumn's Glow
        36920, -- Sun Crystal
        36919, -- Cardinal Ruby
        36918, -- Scarlet Ruby
        36917, -- Bloodstone
        36916, -- Cobalt Bar
        36860, -- Eternal Fire
        36784, -- Siren's Tear
        36783, -- Northsea Pearl
        35627, -- Eternal Shadow
        35625, -- Eternal Life
        35624, -- Eternal Earth
        35623, -- Eternal Air
        35622, -- Eternal Water
        34054, -- Infinite Dust
        34052, -- Dream Shard
    },
    -- https://www.wowhead.com/items?filter=87:194:166;7:1:2;0:1:0
    [2] = { -- Burning Crusade
        35128, -- Hardened Khorium
        34664, -- Sunmote
        32249, -- Seaspray Emerald
        32231, -- Pyrestone
        32230, -- Shadowsong Amethyst
        32229, -- Lionseye
        32228, -- Empyrean Sapphire
        32227, -- Crimson Spinel
        31079, -- Mercurial Adamantite
        27860, -- Purified Draenic Water
        25868, -- Skyfire Diamond
        25867, -- Earthstorm Diamond
        24479, -- Shadow Pearl
        24478, -- Jaggal Pearl
        24243, -- Adamantite Powder
        23573, -- Hardened Adamantite Bar
        23572, -- Primal Nether
        23571, -- Primal Might
        23449, -- Khorium Bar
        23448, -- Felsteel Bar
        23447, -- Eternium Bar
        23446, -- Adamantite Bar
        23445, -- Fel Iron Bar
        23441, -- Nightseye
        23440, -- Dawnstone
        23439, -- Noble Topaz
        23438, -- Star of Elune
        23437, -- Talasite
        23436, -- Living Ruby
        23117, -- Azure Moonstone
        23112, -- Golden Draenite
        23107, -- Shadow Draenite
        23079, -- Deep Peridot
        23077, -- Blood Garnet
        22578, -- Mote of Water
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        21929, -- Flame Spessarite
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
        21752, -- Thorium Setting
        20963, -- Mithril Filigree
        20817, -- Bronze Setting
        20816, -- Delicate Copper Wire
    },
    -- https://www.wowhead.com/items?filter=87:194:166;7:1:1;0:1:0
    [1] = { -- Vanilla
        22682, -- Frozen Rune
        19943, -- Massive Mojo
        18335, -- Pristine Black Diamond
        17011, -- Lava Core
        16204, -- Light Illusion Dust
        14344, -- Large Brilliant Shard
        12808, -- Essence of Undeath
        12804, -- Powerful Mojo
        12803, -- Living Essence
        12800, -- Azerothian Diamond
        12799, -- Large Opal
        12662, -- Demonic Rune
        12365, -- Dense Stone
        12364, -- Huge Emerald
        12363, -- Arcane Crystal
        12361, -- Blue Sapphire
        12360, -- Arcanite Bar
        12359, -- Thorium Bar
        11754, -- Black Diamond
        11371, -- Dark Iron Bar
        10286, -- Heart of the Wild
        9210, -- Ghost Dye
        7971, -- Black Pearl
        7912, -- Solid Stone
        7910, -- Star Ruby
        7909, -- Aquamarine
        7081, -- Breath of Wind
        7079, -- Globe of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7075, -- Core of Earth
        7070, -- Elemental Water
        7067, -- Elemental Earth
        6149, -- Greater Mana Potion
        6037, -- Truesilver Bar
        5637, -- Large Fang
        5498, -- Small Lustrous Pearl
        3864, -- Citrine
        3860, -- Mithril Bar
        3827, -- Mana Potion
        3824, -- Shadow Oil
        3577, -- Gold Bar
        3575, -- Iron Bar
        3391, -- Elixir of Ogre's Strength
        2842, -- Silver Bar
        2841, -- Bronze Bar
        2840, -- Copper Bar
        2838, -- Heavy Stone
        2836, -- Coarse Stone
        2835, -- Rough Stone
        1705, -- Lesser Moonstone
        1529, -- Jade
        1210, -- Shadowgem
        1206, -- Moss Agate
        818, -- Tigerseye
        774, -- Malachite
    },
}
