-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 10:14:54

items.Leatherworking = {
    -- https://www.wowhead.com/items?filter=87:194:166;8:1:12;0:1:0
    [12] = { -- Midnight
        274781, -- Cursebound Globe
        274777, -- Neutralized Venom Clot
        274589, -- Ula'tek Snakehead
        251665, -- Silverleaf Thread
        251285, -- Petrified Root
        251283, -- Tormented Tantalum
        245345, -- Fused Vitality
        244636, -- Sin'dorei Armor Banding
        244635, -- Sin'dorei Armor Banding
        244634, -- Infused Scalewoven Hide
        244633, -- Infused Scalewoven Hide
        244631, -- Scalewoven Hide
        243737, -- Smuggler's Enchanted Edge
        243578, -- Aetherlume
        242788, -- Dusk-Shrouded Stone
        242620, -- Glimmering Gemdust
        241281, -- Composite Flora
        238530, -- Majestic Fin
        238529, -- Majestic Hide
        238528, -- Majestic Claw
        238525, -- Fantastic Fur
        238523, -- Carving Canine
        238522, -- Peerless Plumage
        238520, -- Void-Tempered Plating
        238518, -- Void-Tempered Hide
        238513, -- Void-Tempered Scales
        238511, -- Void-Tempered Leather
        238204, -- Sterling Alloy
        238202, -- Gloaming Alloy
        236952, -- Mote of Pure Void
        236951, -- Mote of Wild Magic
        236950, -- Mote of Primal Energy
        236949, -- Mote of Light
        236780, -- Nocturnal Lotus
        236761, -- Tranquility Bloom
    },
    -- https://www.wowhead.com/items?filter=87:194:166;8:1:11;0:1:0
    [11] = { -- The War Within
        256963, -- Thalassian Lumber
        251773, -- Dragonpine Lumber
        251772, -- Arden Lumber
        251768, -- Darkpine Lumber
        251767, -- Fel-Touched Lumber
        251766, -- Shadowmoon Lumber
        251764, -- Ashwood Lumber
        251763, -- Bamboo Lumber
        251762, -- Coldwind Lumber
        248012, -- Dornic Fir Lumber
        245586, -- Ironwood Lumber
        242691, -- Olemba Lumber
        224764, -- Mosswool Thread
        221856, -- Whimsical Wiring
        221853, -- Handful of Bismuth Bolts
        221758, -- Profaned Tinderbox
        221757, -- Gloomfathom Hide
        221756, -- Vial of Kaheti Oils
        221754, -- Ringing Deeps Ingot
        219901, -- Storm-Touched Weapon Wrap
        219898, -- Chitin Armor Banding
        219892, -- Leyfused Hide
        219889, -- Sporecoated Hide
        219886, -- Writhing Hide
        219883, -- Crystalfused Hide
        219880, -- Carapace-Backed Hide
        219013, -- Superb Beast Fang
        218339, -- Burning Cinderbee Setae
        218338, -- Bottled Storm
        218337, -- Honed Bone Shards
        218336, -- Kaheti Swarm Chitin
        213613, -- Leyline Residue
        213612, -- Viridescent Spores
        213611, -- Writhing Sample
        213610, -- Crystalline Powder
        212674, -- Sunless Carapace
        212670, -- Thunderous Hide
        212667, -- Gloom Chitin
        212664, -- Stormcharged Leather
        212563, -- Harmonious Horticulture
        210814, -- Artisan's Acuity
        210796, -- Mycobloom
    },
    -- https://www.wowhead.com/items?filter=87:194:166;8:1:10;0:1:0
    [10] = { -- Dragonflight
        210456, -- Dreaming Antler Fragment
        208212, -- Dreaming Essence
        207702, -- Wartorn Scrap
        205413, -- Obsidian Cobraskin
        204464, -- Shadowflame Essence
        204463, -- Dracothyst
        204460, -- Zaralek Glowspores
        203405, -- Pristine Pelt
        201405, -- Tuft of Primal Wool
        201404, -- Tallstrider Sinew
        201403, -- Mastodon Tusk
        201400, -- Aquatic Maw
        201399, -- Primal Bear Spine
        198615, -- Pentagold Seal
        194862, -- Runed Writhebark
        194727, -- Fiery Spirit
        194542, -- Prototype Explorer's Barding Framework
        194541, -- Prototype Regal Barding Framework
        193922, -- Wildercloth
        193362, -- Fiery Soul
        193360, -- Centaur's Trophy Necklace
        193259, -- Flawless Proto Dragon Scale
        193258, -- Fire-Infused Hide
        193256, -- Windsong Plumage
        193255, -- Pristine Vorquin Horn
        193254, -- Rockfang Leather
        193253, -- Cacophonous Thunderscale
        193252, -- Salamanther Scales
        193251, -- Crystalspine Fur
        193248, -- Infurious Scales
        193245, -- Frostbite Scales
        193242, -- Earthshine Scales
        193236, -- Infurious Hide
        193229, -- Mireslush Hide
        193226, -- Stonecrust Hide
        193222, -- Lustrous Scaled Hide
        193216, -- Dense Hide
        193213, -- Adamant Scales
        193208, -- Resilient Leather
        193053, -- Contoured Fowlfeather
        192869, -- Illimited Diamond
        191496, -- Omnium Draconis
        191460, -- Hochenblume
        190456, -- Artisan's Mettle
        190450, -- Awakened Ire
        190331, -- Awakened Decay
        190329, -- Awakened Frost
        190327, -- Awakened Air
        190321, -- Awakened Fire
        190316, -- Awakened Earth
        190312, -- Khaz'gorite Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;8:1:9;0:1:0
    [9] = { -- Shadowlands
        187707, -- Progenitor Essentia
        187701, -- Protogenic Pelt
        186017, -- Korthite Crystal
        183955, -- Curing Salt
        183951, -- Immortal Shard
        182290, -- Bottle of Leather Dye
        182194, -- Steelhide Sinew
        182193, -- Thick Steelhide Leather
        182055, -- Ragged Sinrunner Leather
        182054, -- Softened Leather
        182053, -- Tortured Sole
        182031, -- Unused Flesh
        182030, -- Cleaned Hide
        182029, -- Corpsestitch Thread
        182008, -- Steelhide Leather Strap
        182007, -- Steelhide Leather Belt
        182003, -- Runestag Leather
        182002, -- Dyed Runestag Leather
        182001, -- Runestag Leather Strap
        178787, -- Orboreal Shard
        177062, -- Penumbra Thread
        177061, -- Twilight Bark
        173204, -- Lightless Silk
        172438, -- Enchanted Heavy Callous Hide
        172097, -- Heavy Callous Hide
        172096, -- Heavy Desolate Leather
        172094, -- Callous Hide
        172092, -- Pallid Bone
        172089, -- Desolate Leather
        171830, -- Oxxein Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;8:1:8;0:1:0
    [8] = { -- Battle for Azeroth
        170553, -- Void Focus Splinter
        169456, -- Seabreeze Saddle Blanket
        168650, -- Cragscale
        168649, -- Dredged Leather
        168139, -- Long Regal Sinew
        168138, -- Spirit of the Bested
        167560, -- Cleaned Brilliant Scales
        167559, -- Supple Hides
        167558, -- Etched Bones
        165948, -- Tidalcore
        165703, -- Breath of Bwonsamdi
        162461, -- Sanguicell
        162460, -- Hydrocore
        160059, -- Amber Tanning Oil
        159959, -- Nylon Thread
        154722, -- Tempest Hide
        154166, -- Coarse Leather Barding
        154165, -- Calcified Bone
        154164, -- Blood-Stained Bone
        153051, -- Mistscale
        153050, -- Shimmerscale
        152668, -- Expulsom
        152579, -- Storm Silver Ore
        152542, -- Hardened Tempest Hide
        152541, -- Coarse Leather
        152513, -- Platinum Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;8:1:7;0:1:0
    [7] = { -- Legion
        151568, -- Primal Sargerite
        151567, -- Lightweave Cloth
        151566, -- Fiendish Leather
        136539, -- Tanned Stonehide Leather
        136538, -- Namha's Stonehide Leather
        130937, -- Fel Leather Cuff
        130892, -- Stalriss' Tanning Mixture
        130891, -- Namha's Tanning Mixture
        130880, -- Fel Leather Strap
        130879, -- Tanned Fel Leather
        130878, -- Shaved Felhide
        130877, -- Fresh Felhide
        130875, -- Stonehide Leather Strip
        130874, -- Stonehide Leather Toe Cap
        130873, -- Stonehide Boot Exterior
        130872, -- Stonehide Leather Lining
        130870, -- Tanned Stonehide Leather
        130869, -- Shaved Stonehide Pelt
        130868, -- Fresh Stonehide Pelt
        130182, -- Maelstrom Sapphire
        130180, -- Dawnlight
        124440, -- Arkhana
        124439, -- Unbroken Tooth
        124438, -- Unbroken Claw
        124437, -- Shal'dorei Silk
        124124, -- Blood of Sargeras
        124116, -- Felhide
        124115, -- Stormscale
        124113, -- Stonehide Leather
        123918, -- Leystone Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;8:1:6;0:1:0
    [6] = { -- Warlords of Draenor
        127759, -- Felblight
        120945, -- Primal Spirit
        118472, -- Savage Blood
        113264, -- Sorcerous Air
        113263, -- Sorcerous Earth
        112185, -- Wind Scale Fragment
        112184, -- Cobra Scale Fragment
        112183, -- Nether Dragonscale Fragment
        112182, -- Patch of Fel Hide
        112181, -- Fel Scale Fragment
        112180, -- Patch of Crystal-Infused Leather
        112179, -- Patch of Thick Clefthoof Leather
        112178, -- Jormungar Scale Fragment
        112177, -- Nerubian Chitin Fragment
        112158, -- Icy Dragonscale Fragment
        112157, -- Prismatic Scale Fragment
        112156, -- Blackened Dragonscale Fragment
        112155, -- Deepsea Scale Fragment
        111557, -- Sumptuous Fur
        110611, -- Burnished Leather
        110609, -- Raw Beast Hide
        109219, -- Draenic Strength Potion
        109218, -- Draenic Intellect Potion
        109217, -- Draenic Agility Potion
        109126, -- Gorgrond Flytrap
        109119, -- True Iron Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;8:1:5;0:1:0
    [5] = { -- Mists of Pandaria
        102218, -- Spirit of War
        98617, -- Hardened Magnificent Hide
        94289, -- Haunting Spirit
        80433, -- Blood Spirit
        79255, -- Starlight Ink
        79254, -- Ink of Dreams
        79101, -- Prismatic Scale
        76061, -- Spirit of Harmony
        72163, -- Magnificent Hide
        72162, -- Sha-Touched Leather
        72120, -- Mist-Touched Leather
    },
    -- https://www.wowhead.com/items?filter=87:194:166;8:1:4;0:1:0
    [4] = { -- Cataclysm
        71998, -- Essence of Destruction
        69237, -- Living Ember
        61981, -- Inferno Ink
        56516, -- Heavy Savage Leather
        54849, -- Obsidium Bar
        52982, -- Deepsea Scale
        52980, -- Pristine Hide
        52979, -- Blackened Dragonscale
        52977, -- Savage Leather Scraps
        52976, -- Savage Leather
        52329, -- Volatile Life
        52328, -- Volatile Air
        52327, -- Volatile Earth
        52326, -- Volatile Water
        52325, -- Volatile Fire
        52190, -- Inferno Ruby
        52078, -- Chaos Orb
    },
    -- https://www.wowhead.com/items?filter=87:194:166;8:1:3;0:1:0
    [3] = { -- Wrath of the Lich King
        49908, -- Primordial Saronite
        47556, -- Crusader Orb
        45087, -- Runed Orb
        44128, -- Arctic Fur
        43102, -- Frozen Orb
        38561, -- Jormungar Scale
        38558, -- Nerubian Chitin
        38557, -- Icy Dragonscale
        38426, -- Eternium Thread
        38425, -- Heavy Borean Leather
        37705, -- Crystallized Water
        37703, -- Crystallized Shadow
        37700, -- Crystallized Air
        36860, -- Eternal Fire
        35627, -- Eternal Shadow
        35625, -- Eternal Life
        35624, -- Eternal Earth
        35623, -- Eternal Air
        35622, -- Eternal Water
        34057, -- Abyss Crystal
        34055, -- Greater Cosmic Essence
        33568, -- Borean Leather
        33567, -- Borean Leather Scraps
    },
    -- https://www.wowhead.com/items?filter=87:194:166;8:1:2;0:1:0
    [2] = { -- Burning Crusade
        34664, -- Sunmote
        32428, -- Heart of Darkness
        30183, -- Nether Vortex
        29548, -- Nether Dragonscales
        29547, -- Wind Scales
        29539, -- Cobra Scales
        25708, -- Thick Clefthoof Leather
        25707, -- Fel Hide
        25700, -- Fel Scales
        25699, -- Crystal-Infused Leather
        25649, -- Knothide Leather Scraps
        23793, -- Heavy Knothide Leather
        23572, -- Primal Nether
        23571, -- Primal Might
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        22450, -- Void Crystal
        22448, -- Small Prismatic Shard
        22445, -- Arcane Dust
        21887, -- Knothide Leather
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
        21844, -- Bolt of Soulcloth
    },
    -- https://www.wowhead.com/items?filter=87:194:166;8:1:1;0:1:0
    [1] = { -- Vanilla
        22682, -- Frozen Rune
        20520, -- Dark Rune
        20381, -- Dreamscale
        20004, -- Mighty Troll's Blood Elixir
        20002, -- Greater Dreamless Sleep Potion
        19943, -- Massive Mojo
        19931, -- Gurubashi Mojo Madness
        19768, -- Primal Tiger Leather
        19767, -- Primal Bat Leather
        18240, -- Ogre Tannin
        17056, -- Light Feather
        17012, -- Core Leather
        17011, -- Lava Core
        17010, -- Fiery Core
        15419, -- Warbear Leather
        15417, -- Devilsaur Leather
        15416, -- Black Dragonscale
        15415, -- Blue Dragonscale
        15414, -- Red Dragonscale
        15412, -- Green Dragonscale
        15410, -- Scale of Onyxia
        15408, -- Heavy Scorpid Scale
        15407, -- Cured Rugged Hide
        14342, -- Mooncloth
        14341, -- Rune Thread
        14256, -- Felcloth
        14227, -- Ironweb Spider Silk
        14048, -- Bolt of Runecloth
        14047, -- Runecloth
        12810, -- Enchanted Leather
        12809, -- Guardian Stone
        12808, -- Essence of Undeath
        12804, -- Powerful Mojo
        12803, -- Living Essence
        12655, -- Enchanted Thorium Bar
        12607, -- Brilliant Chromatic Scale
        12364, -- Huge Emerald
        12361, -- Blue Sapphire
        12360, -- Arcanite Bar
        11754, -- Black Diamond
        11291, -- Star Wood
        10285, -- Shadow Silk
        8343, -- Heavy Silken Thread
        8172, -- Cured Thick Hide
        8171, -- Rugged Hide
        8170, -- Rugged Leather
        8169, -- Thick Hide
        8167, -- Turtle Scale
        8165, -- Worn Dragonscale
        8154, -- Scorpid Scale
        8153, -- Wildvine
        8150, -- Deeprock Salt
        7971, -- Black Pearl
        7910, -- Star Ruby
        7392, -- Green Whelp Scale
        7286, -- Black Whelp Scale
        7082, -- Essence of Air
        7081, -- Breath of Wind
        7080, -- Essence of Water
        7079, -- Globe of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7075, -- Core of Earth
        7071, -- Iron Buckle
        7070, -- Elemental Water
        7067, -- Elemental Earth
        6471, -- Perfect Deviate Scale
        6470, -- Deviate Scale
        6260, -- Blue Dye
        5785, -- Thick Murloc Scale
        5784, -- Slimy Murloc Scale
        5637, -- Large Fang
        5633, -- Great Rage Potion
        5500, -- Iridescent Pearl
        5498, -- Small Lustrous Pearl
        5373, -- Lucky Charm
        5082, -- Thin Kodo Leather
        4461, -- Raptor Hide
        4342, -- Purple Dye
        4340, -- Gray Dye
        4338, -- Mageweave Cloth
        4337, -- Thick Spider's Silk
        4305, -- Bolt of Silk Cloth
        4304, -- Thick Leather
        4291, -- Silken Thread
        4289, -- Salt
        4236, -- Cured Heavy Hide
        4235, -- Heavy Hide
        4234, -- Heavy Leather
        4233, -- Cured Medium Hide
        4232, -- Medium Hide
        4231, -- Cured Light Hide
        3864, -- Citrine
        3824, -- Shadow Oil
        3390, -- Elixir of Lesser Agility
        3389, -- Elixir of Defense
        3383, -- Elixir of Wisdom
        3356, -- Kingsblood
        3182, -- Spider's Silk
        2997, -- Bolt of Woolen Cloth
        2934, -- Ruined Leather Scraps
        2840, -- Copper Bar
        2605, -- Green Dye
        2604, -- Red Dye
        2459, -- Swiftness Potion
        2457, -- Elixir of Minor Agility
        2325, -- Black Dye
        2324, -- Bleach
        2321, -- Fine Thread
        2320, -- Coarse Thread
        2319, -- Medium Leather
        2318, -- Light Leather
        1529, -- Jade
        1206, -- Moss Agate
        783, -- Light Hide
    },
}
