-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 16:34:11

items.Mining = {
    -- https://www.wowhead.com/items?filter=87:166:194;9:12:1;0:0:1
    [12] = { -- Midnight
    },
    -- https://www.wowhead.com/items?filter=87:166:194;9:11:1;0:0:1
    [11] = { -- The War Within
        210937, -- Ironclaw Ore
        210936, -- Ironclaw Ore
        210934, -- Aqirite
        210933, -- Aqirite
        210931, -- Bismuth
        210930, -- Bismuth
    },
    -- https://www.wowhead.com/items?filter=87:166:194;9:10:1;0:0:1
    [10] = { -- Dragonflight
        194727, -- Fiery Spirit
        190396, -- Serevite Ore
        190395, -- Serevite Ore
        190313, -- Khaz'gorite Ore
        190312, -- Khaz'gorite Ore
        189143, -- Draconium Ore
        188658, -- Draconium Ore
    },
    -- https://www.wowhead.com/items?filter=87:166:194;9:9:1;0:0:1
    [9] = { -- Shadowlands
    },
    -- https://www.wowhead.com/items?filter=87:166:194;9:8:1;0:0:1
    [8] = { -- Battle for Azeroth
    },
    -- https://www.wowhead.com/items?filter=87:166:194;9:7:1;0:0:1
    [7] = { -- Legion
        156930, -- Rich Illusion Dust
    },
    -- https://www.wowhead.com/items?filter=87:166:194;9:6:1;0:0:1
    [6] = { -- Warlords of Draenor
    },
    -- https://www.wowhead.com/items?filter=87:166:194;9:5:1;0:0:1
    [5] = { -- Mists of Pandaria
        72103, -- White Trillium Ore
        72094, -- Black Trillium Ore
        72092, -- Ghost Iron Ore
    },
    -- https://www.wowhead.com/items?filter=87:166:194;9:4:1;0:0:1
    [4] = { -- Cataclysm
        53038, -- Obsidium Ore
        52327, -- Volatile Earth
        52186, -- Elementium Bar
        52185, -- Elementium Ore
        52183, -- Pyrite Ore
    },
    -- https://www.wowhead.com/items?filter=87:166:194;9:3:1;0:0:1
    [3] = { -- Wrath of the Lich King
        41163, -- Titanium Bar
        36912, -- Saronite Ore
        36910, -- Titanium Ore
        36909, -- Cobalt Ore
        36860, -- Eternal Fire
        35627, -- Eternal Shadow
        35624, -- Eternal Earth
    },
    -- https://www.wowhead.com/items?filter=87:166:194;9:2:1;0:0:1
    [2] = { -- Burning Crusade
        23573, -- Hardened Adamantite Bar
        23449, -- Khorium Bar
        23447, -- Eternium Bar
        23446, -- Adamantite Bar
        23445, -- Fel Iron Bar
        23427, -- Eternium Ore
        23426, -- Khorium Ore
        23425, -- Adamantite Ore
        23424, -- Fel Iron Ore
        22452, -- Primal Earth
        21884, -- Primal Fire
    },
    -- https://www.wowhead.com/items?filter=87:166:194;9:1:1;0:0:1
    [1] = { -- Vanilla
        18567, -- Elemental Flux
        18562, -- Elementium Ingot
        17010, -- Fiery Core
        12360, -- Arcanite Bar
        12359, -- Thorium Bar
        11370, -- Dark Iron Ore
        10620, -- Thorium Ore
        7911, -- Truesilver Ore
        3858, -- Mithril Ore
        3857, -- Coal
        3576, -- Tin Bar
        3575, -- Iron Bar
        2840, -- Copper Bar
        2776, -- Gold Ore
        2775, -- Silver Ore
        2772, -- Iron Ore
        2771, -- Tin Ore
        2770, -- Copper Ore
    },
}
