-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 16:27:24

items.Mining = {
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:12;0:1:0
    [12] = { -- Midnight
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:11;0:1:0
    [11] = { -- The War Within
        210938, -- Ironclaw Ore
        210937, -- Ironclaw Ore
        210935, -- Aqirite
        210934, -- Aqirite
        210932, -- Bismuth
        210931, -- Bismuth
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:10;0:1:0
    [10] = { -- Dragonflight
        190396, -- Serevite Ore
        190394, -- Serevite Ore
        190314, -- Khaz'gorite Ore
        190313, -- Khaz'gorite Ore
        190311, -- Draconium Ore
        188658, -- Draconium Ore
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:9;0:1:0
    [9] = { -- Shadowlands
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:8;0:1:0
    [8] = { -- Battle for Azeroth
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:7;0:1:0
    [7] = { -- Legion
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:6;0:1:0
    [6] = { -- Warlords of Draenor
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:5;0:1:0
    [5] = { -- Mists of Pandaria
        72096, -- Ghost Iron Bar
        72095, -- Trillium Bar
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:4;0:1:0
    [4] = { -- Cataclysm
        54849, -- Obsidium Bar
        53039, -- Hardened Elementium Bar
        52186, -- Elementium Bar
        51950, -- Pyrium Bar
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:3;0:1:0
    [3] = { -- Wrath of the Lich King
        41163, -- Titanium Bar
        37663, -- Titansteel Bar
        36916, -- Cobalt Bar
        36913, -- Saronite Bar
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:2;0:1:0
    [2] = { -- Burning Crusade
        35128, -- Hardened Khorium
        23573, -- Hardened Adamantite Bar
        23449, -- Khorium Bar
        23448, -- Felsteel Bar
        23447, -- Eternium Bar
        23446, -- Adamantite Bar
        23445, -- Fel Iron Bar
        22574, -- Mote of Fire
        22573, -- Mote of Earth
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:1;0:1:0
    [1] = { -- Vanilla
        17771, -- Enchanted Elementium Bar
        12655, -- Enchanted Thorium Bar
        12359, -- Thorium Bar
        11371, -- Dark Iron Bar
        6037, -- Truesilver Bar
        3860, -- Mithril Bar
        3859, -- Steel Bar
        3577, -- Gold Bar
        3576, -- Tin Bar
        3575, -- Iron Bar
        2842, -- Silver Bar
        2841, -- Bronze Bar
        2840, -- Copper Bar
    },
}
