-- Generated by merge_tables.py

items.Mining = {
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:12;0:1:0
    -- https://www.wowhead.com/items?filter=87:166:194;9:12:1;0:0:1
    -- https://www.wowhead.com/items?filter=73:194:217:166;1:1:1:12;0:1:0:0
    [12] = { -- Midnight
        274781, -- Cursebound Globe
        237366, -- Dazzling Thorium
        237365, -- Brilliant Silver Ore
        237364, -- Brilliant Silver Ore
        237363, -- Umbral Tin Ore
        237362, -- Umbral Tin Ore
        237361, -- Refulgent Copper Ore
        237359, -- Refulgent Copper Ore
        236952, -- Mote of Pure Void
        236951, -- Mote of Wild Magic
        236950, -- Mote of Primal Energy
        236949, -- Mote of Light
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:11;0:1:0
    -- https://www.wowhead.com/items?filter=87:166:194;9:11:1;0:0:1
    -- https://www.wowhead.com/items?filter=73:194:217:166;1:1:1:11;0:1:0:0
    [11] = { -- The War Within
        240216, -- K'areshi Resonating Stone
        238213, -- Desolate Talus
        238212, -- Desolate Talus
        238201, -- Desolate Talus
        224828, -- Weavercloth
        219150, -- Pile of Rusted Scrap
        217707, -- Imperfect Null Stone
        213611, -- Writhing Sample
        213610, -- Crystalline Powder
        210939, -- Null Stone
        210938, -- Ironclaw Ore
        210937, -- Ironclaw Ore
        210936, -- Ironclaw Ore
        210935, -- Aqirite
        210934, -- Aqirite
        210933, -- Aqirite
        210932, -- Bismuth
        210931, -- Bismuth
        210930, -- Bismuth
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:10;0:1:0
    -- https://www.wowhead.com/items?filter=87:166:194;9:10:1;0:0:1
    -- https://www.wowhead.com/items?filter=73:194:217:166;1:1:1:10;0:1:0:0
    [10] = { -- Dragonflight
        204460, -- Zaralek Glowspores
        197754, -- Salt Deposit
        194727, -- Fiery Spirit
        192871, -- Illimited Diamond
        192870, -- Illimited Diamond
        192869, -- Illimited Diamond
        192868, -- Nozdorite
        192867, -- Nozdorite
        192866, -- Nozdorite
        192865, -- Neltharite
        192863, -- Neltharite
        192862, -- Neltharite
        192861, -- Ysemerald
        192860, -- Ysemerald
        192859, -- Ysemerald
        192858, -- Malygite
        192857, -- Malygite
        192856, -- Malygite
        192855, -- Alexstraszite
        192853, -- Alexstraszite
        192852, -- Alexstraszite
        192851, -- Eternity Amber
        192850, -- Eternity Amber
        192849, -- Eternity Amber
        192848, -- Sundered Onyx
        192847, -- Sundered Onyx
        192846, -- Sundered Onyx
        192845, -- Vibrant Emerald
        192844, -- Vibrant Emerald
        192843, -- Vibrant Emerald
        192842, -- Mystic Sapphire
        192841, -- Mystic Sapphire
        192840, -- Mystic Sapphire
        192839, -- Queen's Ruby
        192838, -- Queen's Ruby
        192837, -- Queen's Ruby
        190451, -- Rousing Ire
        190396, -- Serevite Ore
        190395, -- Serevite Ore
        190394, -- Serevite Ore
        190328, -- Rousing Frost
        190326, -- Rousing Air
        190322, -- Rousing Order
        190320, -- Rousing Fire
        190315, -- Rousing Earth
        190314, -- Khaz'gorite Ore
        190313, -- Khaz'gorite Ore
        190312, -- Khaz'gorite Ore
        190311, -- Draconium Ore
        189143, -- Draconium Ore
        188658, -- Draconium Ore
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:9;0:1:0
    -- https://www.wowhead.com/items?filter=87:166:194;9:9:1;0:0:1
    -- https://www.wowhead.com/items?filter=73:194:217:166;1:1:1:9;0:1:0:0
    [9] = { -- Shadowlands
        187707, -- Progenitor Essentia
        187700, -- Progenium Ore
        177061, -- Twilight Bark
        171841, -- Shaded Stone
        171840, -- Porous Stone
        171833, -- Elethium Ore
        171832, -- Sinvyr Ore
        171831, -- Phaedrum Ore
        171830, -- Oxxein Ore
        171829, -- Solenium Ore
        171828, -- Laestrite Ore
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:8;0:1:0
    -- https://www.wowhead.com/items?filter=87:166:194;9:8:1;0:0:1
    -- https://www.wowhead.com/items?filter=73:194:217:166;1:1:1:8;0:1:0:0
    [8] = { -- Battle for Azeroth
        168185, -- Osmenite Ore
        163630, -- Ductile Platinum
        163629, -- Dense Storm Silver
        163628, -- Hardened Monelite
        163627, -- Smooth Platinum
        163626, -- Coarse Storm Silver
        163625, -- Rough Monelite
        163624, -- Burnished Platinum
        163623, -- Gleaming Storm Silver
        163609, -- Luminous Monelite
        152579, -- Storm Silver Ore
        152513, -- Platinum Ore
        152512, -- Monelite Ore
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:7;0:1:0
    -- https://www.wowhead.com/items?filter=87:166:194;9:7:1;0:0:1
    -- https://www.wowhead.com/items?filter=73:194:217:166;1:1:1:7;0:1:0:0
    [7] = { -- Legion
        156930, -- Rich Illusion Dust
        151720, -- Chemirine
        151719, -- Lightsphene
        151568, -- Primal Sargerite
        151564, -- Empyrium
        124444, -- Infernal Brimstone
        124438, -- Unbroken Claw
        124124, -- Blood of Sargeras
        123919, -- Felslate
        123918, -- Leystone Ore
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:6;0:1:0
    -- https://www.wowhead.com/items?filter=87:166:194;9:6:1;0:0:1
    -- https://www.wowhead.com/items?filter=73:194:217:166;1:1:1:6;0:1:0:0
    [6] = { -- Warlords of Draenor
        127759, -- Felblight
        120945, -- Primal Spirit
        115508, -- Draenic Stone
        109992, -- Blackrock Fragment
        109991, -- True Iron Nugget
        109119, -- True Iron Ore
        109118, -- Blackrock Ore
        108391, -- Titanium Ore Nugget
        108309, -- Pyrite Ore Nugget
        108308, -- Elementium Ore Nugget
        108307, -- Obsidium Ore Nugget
        108306, -- Saronite Ore Nugget
        108305, -- Cobalt Ore Nugget
        108304, -- Khorium Ore Nugget
        108302, -- Adamantite Ore Nugget
        108301, -- Fel Iron Ore Nugget
        108300, -- Mithril Ore Nugget
        108299, -- Truesilver Ore Nugget
        108298, -- Thorium Ore Nugget
        108297, -- Iron Ore Nugget
        108296, -- Gold Ore Nugget
        108294, -- Silver Ore Nugget
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:5;0:1:0
    -- https://www.wowhead.com/items?filter=87:166:194;9:5:1;0:0:1
    -- https://www.wowhead.com/items?filter=73:194:217:166;1:1:1:5;0:1:0:0
    [5] = { -- Mists of Pandaria
        97546, -- Kyparite Fragment
        97512, -- Ghost Iron Nugget
        76142, -- Sun's Radiance
        76141, -- Imperial Amethyst
        76140, -- Vermilion Onyx
        76139, -- Wild Jade
        76138, -- River's Heart
        76137, -- Alexandrite
        76136, -- Pandarian Garnet
        76135, -- Roguestone
        76134, -- Sunstone
        76133, -- Lapis Lazuli
        76131, -- Primordial Ruby
        76130, -- Tiger Opal
        72103, -- White Trillium Ore
        72096, -- Ghost Iron Bar
        72095, -- Trillium Bar
        72094, -- Black Trillium Ore
        72093, -- Kyparite
        72092, -- Ghost Iron Ore
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:4;0:1:0
    -- https://www.wowhead.com/items?filter=87:166:194;9:4:1;0:0:1
    -- https://www.wowhead.com/items?filter=73:194:217:166;1:1:1:4;0:1:0:0
    [4] = { -- Cataclysm
        54849, -- Obsidium Bar
        53039, -- Hardened Elementium Bar
        53038, -- Obsidium Ore
        52328, -- Volatile Air
        52327, -- Volatile Earth
        52326, -- Volatile Water
        52325, -- Volatile Fire
        52195, -- Amberjewel
        52194, -- Demonseye
        52193, -- Ember Topaz
        52192, -- Dream Emerald
        52191, -- Ocean Sapphire
        52190, -- Inferno Ruby
        52186, -- Elementium Bar
        52185, -- Elementium Ore
        52183, -- Pyrite Ore
        52182, -- Jasper
        52181, -- Hessonite
        52180, -- Nightstone
        52179, -- Alicite
        52178, -- Zephyrite
        52177, -- Carnelian
        51950, -- Pyrium Bar
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:3;0:1:0
    -- https://www.wowhead.com/items?filter=87:166:194;9:3:1;0:0:1
    -- https://www.wowhead.com/items?filter=73:194:217:166;1:1:1:3;0:1:0:0
    [3] = { -- Wrath of the Lich King
        41163, -- Titanium Bar
        37705, -- Crystallized Water
        37703, -- Crystallized Shadow
        37702, -- Crystallized Fire
        37701, -- Crystallized Earth
        37700, -- Crystallized Air
        37663, -- Titansteel Bar
        36933, -- Forest Emerald
        36932, -- Dark Jade
        36930, -- Monarch Topaz
        36929, -- Huge Citrine
        36927, -- Twilight Opal
        36926, -- Shadow Crystal
        36924, -- Sky Sapphire
        36923, -- Chalcedony
        36921, -- Autumn's Glow
        36920, -- Sun Crystal
        36918, -- Scarlet Ruby
        36917, -- Bloodstone
        36916, -- Cobalt Bar
        36913, -- Saronite Bar
        36912, -- Saronite Ore
        36910, -- Titanium Ore
        36909, -- Cobalt Ore
        36860, -- Eternal Fire
        35627, -- Eternal Shadow
        35624, -- Eternal Earth
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:2;0:1:0
    -- https://www.wowhead.com/items?filter=87:166:194;9:2:1;0:0:1
    -- https://www.wowhead.com/items?filter=73:194:217:166;1:1:1:2;0:1:0:0
    [2] = { -- Burning Crusade
        35128, -- Hardened Khorium
        32249, -- Seaspray Emerald
        32231, -- Pyrestone
        32230, -- Shadowsong Amethyst
        32229, -- Lionseye
        32228, -- Empyrean Sapphire
        32227, -- Crimson Spinel
        27668, -- Lynx Meat
        23676, -- Moongraze Stag Tenderloin
        23573, -- Hardened Adamantite Bar
        23449, -- Khorium Bar
        23448, -- Felsteel Bar
        23447, -- Eternium Bar
        23446, -- Adamantite Bar
        23445, -- Fel Iron Bar
        23441, -- Nightseye
        23440, -- Dawnstone
        23439, -- Noble Topaz
        23438, -- Star of Elune
        23437, -- Talasite
        23436, -- Living Ruby
        23427, -- Eternium Ore
        23426, -- Khorium Ore
        23425, -- Adamantite Ore
        23424, -- Fel Iron Ore
        23117, -- Azure Moonstone
        23112, -- Golden Draenite
        23107, -- Shadow Draenite
        23079, -- Deep Peridot
        23077, -- Blood Garnet
        22574, -- Mote of Fire
        22573, -- Mote of Earth
        22452, -- Primal Earth
        21929, -- Flame Spessarite
        21884, -- Primal Fire
    },
    -- https://www.wowhead.com/items?filter=86:194:166;9:1:1;0:1:0
    -- https://www.wowhead.com/items?filter=87:166:194;9:1:1;0:0:1
    -- https://www.wowhead.com/items?filter=73:194:217:166;1:1:1:1;0:1:0:0
    [1] = { -- Vanilla
        22203, -- Large Obsidian Shard
        22202, -- Small Obsidian Shard
        18567, -- Elemental Flux
        18562, -- Elementium Ingot
        17771, -- Enchanted Elementium Bar
        17056, -- Light Feather
        17010, -- Fiery Core
        12800, -- Azerothian Diamond
        12799, -- Large Opal
        12655, -- Enchanted Thorium Bar
        12365, -- Dense Stone
        12364, -- Huge Emerald
        12363, -- Arcane Crystal
        12361, -- Blue Sapphire
        12360, -- Arcanite Bar
        12359, -- Thorium Bar
        11754, -- Black Diamond
        11382, -- Blood of the Mountain
        11371, -- Dark Iron Bar
        11370, -- Dark Iron Ore
        10620, -- Thorium Ore
        9262, -- Black Vitriol
        8150, -- Deeprock Salt
        7912, -- Solid Stone
        7911, -- Truesilver Ore
        7910, -- Star Ruby
        7909, -- Aquamarine
        7076, -- Essence of Earth
        6037, -- Truesilver Bar
        5469, -- Strider Meat
        5466, -- Scorpid Stinger
        3864, -- Citrine
        3860, -- Mithril Bar
        3859, -- Steel Bar
        3858, -- Mithril Ore
        3857, -- Coal
        3577, -- Gold Bar
        3576, -- Tin Bar
        3575, -- Iron Bar
        2842, -- Silver Bar
        2841, -- Bronze Bar
        2840, -- Copper Bar
        2838, -- Heavy Stone
        2836, -- Coarse Stone
        2835, -- Rough Stone
        2776, -- Gold Ore
        2775, -- Silver Ore
        2772, -- Iron Ore
        2771, -- Tin Ore
        2770, -- Copper Ore
        1705, -- Lesser Moonstone
        1529, -- Jade
        1468, -- Murloc Fin
        1210, -- Shadowgem
        1206, -- Moss Agate
        818, -- Tigerseye
        774, -- Malachite
    },
}
