-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 10:08:59

items.Tailoring = {
    -- https://www.wowhead.com/items?filter=87:194:166;10:1:12;0:1:0
    [12] = { -- Midnight
        274781, -- Cursebound Globe
        274777, -- Neutralized Venom Clot
        251691, -- Embroidery Floss
        251665, -- Silverleaf Thread
        251285, -- Petrified Root
        251283, -- Tormented Tantalum
        245345, -- Fused Vitality
        243602, -- Radiant Shard
        243599, -- Eversinging Dust
        239702, -- Imbued Bright Linen Bolt
        239700, -- Bright Linen Bolt
        239201, -- Sunfire Silk Bolt
        239198, -- Arcanoweave Bolt
        238525, -- Fantastic Fur
        238523, -- Carving Canine
        238522, -- Peerless Plumage
        237018, -- Arcanoweave
        237015, -- Sunfire Silk
        236963, -- Bright Linen
        236952, -- Mote of Pure Void
        236951, -- Mote of Wild Magic
        236950, -- Mote of Primal Energy
        236949, -- Mote of Light
    },
    -- https://www.wowhead.com/items?filter=87:194:166;10:1:11;0:1:0
    [11] = { -- The War Within
        256963, -- Thalassian Lumber
        251773, -- Dragonpine Lumber
        251772, -- Arden Lumber
        251768, -- Darkpine Lumber
        251767, -- Fel-Touched Lumber
        251766, -- Shadowmoon Lumber
        251764, -- Ashwood Lumber
        251763, -- Bamboo Lumber
        251762, -- Coldwind Lumber
        248012, -- Dornic Fir Lumber
        245586, -- Ironwood Lumber
        242691, -- Olemba Lumber
        228930, -- Adorning Ribbon
        224832, -- Exquisite Weavercloth Bolt
        224828, -- Weavercloth
        224824, -- Duskweave
        224764, -- Mosswool Thread
        222804, -- Weavercloth Bolt
        222801, -- Dawnweave Bolt
        222798, -- Duskweave Bolt
        222795, -- Spool of Weaverthread
        222792, -- Spool of Dawnthread
        222789, -- Spool of Duskthread
        222615, -- Apricate Ink
        222609, -- Shadow Ink
        222423, -- Sanctified Alloy
        221865, -- Chaos Circuit
        221862, -- Safety Switch
        219952, -- Refulgent Crystal
        219949, -- Gleaming Shard
        219946, -- Storm Dust
        213759, -- Inverted Prism
        213613, -- Leyline Residue
        213611, -- Writhing Sample
        213197, -- Null Lotus
        212674, -- Sunless Carapace
        212670, -- Thunderous Hide
        212563, -- Harmonious Horticulture
        210939, -- Null Stone
        210814, -- Artisan's Acuity
    },
    -- https://www.wowhead.com/items?filter=87:194:166;10:1:10;0:1:0
    [10] = { -- Dragonflight
        208212, -- Dreaming Essence
        207702, -- Wartorn Scrap
        204460, -- Zaralek Glowspores
        203406, -- Torn Morqut Kite
        201405, -- Tuft of Primal Wool
        201404, -- Tallstrider Sinew
        201401, -- Iridescent Plume
        200113, -- Resonant Crystal
        198397, -- Rainbow Pearl
        194751, -- Blazing Ink
        194727, -- Fiery Spirit
        194124, -- Vibrant Shard
        194123, -- Chromatic Dust
        194014, -- Temporal Spellthread
        194011, -- Frozen Spellthread
        194008, -- Vibrant Spellthread
        193938, -- Azureweave Bolt
        193935, -- Chronocloth Bolt
        193932, -- Infurious Wildercloth Bolt
        193929, -- Vibrant Wildercloth Bolt
        193926, -- Wildercloth Bolt
        193922, -- Wildercloth
        193921, -- Airy Soul
        193919, -- Frosty Soul
        193368, -- Silken Gemdust
        193360, -- Centaur's Trophy Necklace
        193216, -- Dense Hide
        193053, -- Contoured Fowlfeather
        192887, -- Elemental Harmony
        192872, -- Fractured Glass
        192095, -- Spool of Wilderthread
        191496, -- Omnium Draconis
        191460, -- Hochenblume
        190456, -- Artisan's Mettle
        190450, -- Awakened Ire
        190395, -- Serevite Ore
        190331, -- Awakened Decay
        190329, -- Awakened Frost
        190327, -- Awakened Air
        190324, -- Awakened Order
        190321, -- Awakened Fire
    },
    -- https://www.wowhead.com/items?filter=87:194:166;10:1:9;0:1:0
    [9] = { -- Shadowlands
        187707, -- Progenitor Essentia
        187703, -- Silken Protofiber
        186017, -- Korthite Crystal
        182117, -- Bleakcloth
        182116, -- Bolt of Bleakcloth
        182104, -- Gossamer Thread
        182103, -- Gossamer Cloth
        182102, -- Bolt of Woven Gossamer
        182052, -- Thread of Pride
        182051, -- Bolt of Prideweave
        182050, -- Prideweave Cloth
        182028, -- Bleakthread
        182006, -- Spool of Ardensilk
        182005, -- Ardensilk Cloth
        182004, -- Bolt of Ardensilk Cloth
        178787, -- Orboreal Shard
        177062, -- Penumbra Thread
        177061, -- Twilight Bark
        173204, -- Lightless Silk
        173202, -- Shrouded Cloth
        173173, -- Essence of Valor
        173170, -- Essence of Rebirth
        172439, -- Enchanted Lightless Silk
        171828, -- Laestrite Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;10:1:8;0:1:0
    [8] = { -- Battle for Azeroth
        170553, -- Void Focus Splinter
        168649, -- Dredged Leather
        167738, -- Gilded Seaweave
        165948, -- Tidalcore
        165703, -- Breath of Bwonsamdi
        162461, -- Sanguicell
        162460, -- Hydrocore
        159959, -- Nylon Thread
        158378, -- Embroidered Deep Sea Satin
        158188, -- Crimson Ink
        152668, -- Expulsom
        152577, -- Deep Sea Satin
        152576, -- Tidespray Linen
        152513, -- Platinum Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;10:1:7;0:1:0
    [7] = { -- Legion
        156930, -- Rich Illusion Dust
        151568, -- Primal Sargerite
        151567, -- Lightweave Cloth
        142335, -- Pristine Falcosaur Feather
        135538, -- Bear Fur
        130183, -- Shadowruby
        130175, -- Chaotic Spinel
        129032, -- Roseate Pigment
        127681, -- Sharp Spritethorn
        127382, -- Tanithria's Sharpened Spritethorn
        127372, -- Silkweave Bracer Lining
        127370, -- Silkweave Bracer: Outer Layer
        127368, -- Bolt of Brimstone-Soaked Silkweave
        127364, -- Silkweave Hood Lining
        127363, -- Silkweave Hood: Outer Layer
        127359, -- Basic Silkweave Robe
        127343, -- Lyndras' Runic Catgut
        127292, -- Tanithria's Green Dye
        127291, -- Tanithria's Red Dye
        127290, -- Tanithria's Blue Dye
        127289, -- Tanithria's Purple Dye
        127287, -- Tanithria's Thread
        127286, -- Tanithria's Silkweave
        127037, -- Runic Catgut
        127004, -- Imbued Silkweave
        124461, -- Demonsteel Bar
        124440, -- Arkhana
        124439, -- Unbroken Tooth
        124438, -- Unbroken Claw
        124437, -- Shal'dorei Silk
        124124, -- Blood of Sargeras
        124115, -- Stormscale
        124113, -- Stonehide Leather
        124106, -- Felwort
        123918, -- Leystone Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;10:1:6;0:1:0
    [6] = { -- Warlords of Draenor
        127759, -- Felblight
        120945, -- Primal Spirit
        118472, -- Savage Blood
        114931, -- Cerulean Pigment
        113588, -- Temporal Crystal
        113264, -- Sorcerous Air
        113263, -- Sorcerous Earth
        111557, -- Sumptuous Fur
        111556, -- Hexweave Cloth
        110609, -- Raw Beast Hide
        109219, -- Draenic Strength Potion
        109218, -- Draenic Intellect Potion
        109217, -- Draenic Agility Potion
        109126, -- Gorgrond Flytrap
        109119, -- True Iron Ore
        109118, -- Blackrock Ore
    },
    -- https://www.wowhead.com/items?filter=87:194:166;10:1:5;0:1:0
    [5] = { -- Mists of Pandaria
        102218, -- Spirit of War
        98619, -- Celestial Cloth
        94289, -- Haunting Spirit
        82447, -- Imperial Silk
        82444, -- Greater Pearlescent Spellthread
        82441, -- Bolt of Windwool Cloth
        80433, -- Blood Spirit
        76061, -- Spirit of Harmony
        74866, -- Golden Carp
        72988, -- Windwool Cloth
    },
    -- https://www.wowhead.com/items?filter=87:194:166;10:1:4;0:1:0
    [4] = { -- Cataclysm
        71998, -- Essence of Destruction
        69237, -- Living Ember
        61981, -- Inferno Ink
        54849, -- Obsidium Bar
        54450, -- Powerful Ghostly Spellthread
        54440, -- Dreamcloth
        53643, -- Bolt of Embersilk Cloth
        53050, -- Heavy Embersilk Bandage
        53010, -- Embersilk Cloth
        52555, -- Hypnotic Dust
        52329, -- Volatile Life
        52328, -- Volatile Air
        52327, -- Volatile Earth
        52326, -- Volatile Water
        52325, -- Volatile Fire
        52078, -- Chaos Orb
    },
    -- https://www.wowhead.com/items?filter=87:194:166;10:1:3;0:1:0
    [3] = { -- Wrath of the Lich King
        49908, -- Primordial Saronite
        47556, -- Crusader Orb
        45087, -- Runed Orb
        43102, -- Frozen Orb
        42253, -- Iceweb Spider Silk
        41595, -- Spellweave
        41594, -- Moonshroud
        41593, -- Ebonweave
        41511, -- Bolt of Imbued Frostweave
        41510, -- Bolt of Frostweave
        38426, -- Eternium Thread
        38425, -- Heavy Borean Leather
        37704, -- Crystallized Life
        37702, -- Crystallized Fire
        37701, -- Crystallized Earth
        36934, -- Eye of Zul
        36930, -- Monarch Topaz
        36925, -- Majestic Zircon
        36922, -- King's Amber
        36919, -- Cardinal Ruby
        36908, -- Frost Lotus
        36860, -- Eternal Fire
        36784, -- Siren's Tear
        36783, -- Northsea Pearl
        35627, -- Eternal Shadow
        35625, -- Eternal Life
        35624, -- Eternal Earth
        35622, -- Eternal Water
        34055, -- Greater Cosmic Essence
        34054, -- Infinite Dust
        34052, -- Dream Shard
        33470, -- Frostweave Cloth
    },
    -- https://www.wowhead.com/items?filter=87:194:166;10:1:2;0:1:0
    [2] = { -- Burning Crusade
        34664, -- Sunmote
        32428, -- Heart of Darkness
        30183, -- Nether Vortex
        24272, -- Shadowcloth
        24271, -- Spellcloth
        23572, -- Primal Nether
        23571, -- Primal Might
        22794, -- Fel Lotus
        22457, -- Primal Mana
        22456, -- Primal Shadow
        22452, -- Primal Earth
        22451, -- Primal Air
        22450, -- Void Crystal
        22446, -- Greater Planar Essence
        22445, -- Arcane Dust
        21887, -- Knothide Leather
        21886, -- Primal Life
        21885, -- Primal Water
        21884, -- Primal Fire
        21882, -- Soul Essence
        21881, -- Netherweb Spider Silk
        21877, -- Netherweave Cloth
        21845, -- Primal Mooncloth
        21844, -- Bolt of Soulcloth
        21842, -- Bolt of Imbued Netherweave
        21840, -- Bolt of Netherweave
    },
    -- https://www.wowhead.com/items?filter=87:194:166;10:1:1;0:1:0
    [1] = { -- Vanilla
        22682, -- Frozen Rune
        20520, -- Dark Rune
        19768, -- Primal Tiger Leather
        19767, -- Primal Bat Leather
        18335, -- Pristine Black Diamond
        18240, -- Ogre Tannin
        17056, -- Light Feather
        17012, -- Core Leather
        17011, -- Lava Core
        17010, -- Fiery Core
        16203, -- Greater Eternal Essence
        14344, -- Large Brilliant Shard
        14342, -- Mooncloth
        14341, -- Rune Thread
        14256, -- Felcloth
        14227, -- Ironweb Spider Silk
        14048, -- Bolt of Runecloth
        14047, -- Runecloth
        13926, -- Golden Pearl
        13468, -- Black Lotus
        12811, -- Righteous Orb
        12810, -- Enchanted Leather
        12809, -- Guardian Stone
        12808, -- Essence of Undeath
        12804, -- Powerful Mojo
        12803, -- Living Essence
        12800, -- Azerothian Diamond
        12662, -- Demonic Rune
        12364, -- Huge Emerald
        12360, -- Arcanite Bar
        10290, -- Pink Dye
        10286, -- Heart of the Wild
        10285, -- Shadow Silk
        9210, -- Ghost Dye
        8831, -- Purple Lotus
        8343, -- Heavy Silken Thread
        8170, -- Rugged Leather
        8153, -- Wildvine
        7972, -- Ichor of Undeath
        7971, -- Black Pearl
        7910, -- Star Ruby
        7082, -- Essence of Air
        7080, -- Essence of Water
        7079, -- Globe of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7072, -- Naga Scale
        7071, -- Iron Buckle
        7070, -- Elemental Water
        7069, -- Elemental Air
        7068, -- Elemental Fire
        7067, -- Elemental Earth
        6371, -- Fire Oil
        6261, -- Orange Dye
        6260, -- Blue Dye
        6048, -- Shadow Protection Potion
        6037, -- Truesilver Bar
        5500, -- Iridescent Pearl
        5498, -- Small Lustrous Pearl
        4625, -- Firebloom
        4342, -- Purple Dye
        4341, -- Yellow Dye
        4340, -- Gray Dye
        4339, -- Bolt of Mageweave
        4338, -- Mageweave Cloth
        4337, -- Thick Spider's Silk
        4306, -- Silk Cloth
        4305, -- Bolt of Silk Cloth
        4304, -- Thick Leather
        4291, -- Silken Thread
        4234, -- Heavy Leather
        3864, -- Citrine
        3829, -- Frost Oil
        3827, -- Mana Potion
        3824, -- Shadow Oil
        3577, -- Gold Bar
        3383, -- Elixir of Wisdom
        3182, -- Spider's Silk
        2997, -- Bolt of Woolen Cloth
        2996, -- Bolt of Linen Cloth
        2605, -- Green Dye
        2604, -- Red Dye
        2592, -- Wool Cloth
        2589, -- Linen Cloth
        2325, -- Black Dye
        2324, -- Bleach
        2321, -- Fine Thread
        2320, -- Coarse Thread
        2319, -- Medium Leather
        2318, -- Light Leather
        1529, -- Jade
        929, -- Healing Potion
    },
}
