-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 20:03:29

items.Blacksmithing = {
    -- https://www.wowhead.com/classic/items?filter=87:194;2:1;0:1
    [1] = { -- Vanilla
        236656, -- Frozen Rune
        234006, -- Monstrous Silithid Chitin
        234004, -- Obsidian Grinding Stone
        234003, -- Obsidian-Infused Thorium Bar
        221021, -- Nightmare Seed
        213383, -- Polished Truesilver Gears
        213379, -- Hyperconductive Arcano-Filament
        213376, -- Low-Background Truesilver Plates
        213373, -- Reflective Scrapmetal
        213369, -- Faintly Glowing Leather
        22682, -- Frozen Rune
        22203, -- Large Obsidian Shard
        22202, -- Small Obsidian Shard
        20882, -- Idol of War
        20879, -- Idol of Life
        20878, -- Idol of Rebirth
        20877, -- Idol of the Sage
        20876, -- Idol of Death
        20875, -- Idol of Night
        20874, -- Idol of the Sun
        20873, -- Alabaster Idol
        20872, -- Vermillion Idol
        20871, -- Obsidian Idol
        20867, -- Onyx Idol
        20725, -- Nexus Crystal
        20520, -- Dark Rune
        20381, -- Dreamscale
        19774, -- Souldarite
        19726, -- Bloodvine
        18262, -- Elemental Sharpening Stone
        17203, -- Sulfuron Ingot
        17012, -- Core Leather
        17011, -- Lava Core
        17010, -- Fiery Core
        15417, -- Devilsaur Leather
        14047, -- Runecloth
        13512, -- Flask of Supreme Power
        13510, -- Flask of the Titans
        12938, -- Blood of Heroes
        12811, -- Righteous Orb
        12810, -- Enchanted Leather
        12809, -- Guardian Stone
        12808, -- Essence of Undeath
        12804, -- Powerful Mojo
        12803, -- Living Essence
        12800, -- Azerothian Diamond
        12799, -- Large Opal
        12753, -- Skin of Shadow
        12662, -- Demonic Rune
        12655, -- Enchanted Thorium Bar
        12644, -- Dense Grinding Stone
        12365, -- Dense Stone
        12364, -- Huge Emerald
        12361, -- Blue Sapphire
        12360, -- Arcanite Bar
        12359, -- Thorium Bar
        11754, -- Black Diamond
        11382, -- Blood of the Mountain
        11371, -- Dark Iron Bar
        11188, -- Yellow Power Crystal
        11186, -- Red Power Crystal
        11185, -- Green Power Crystal
        11184, -- Blue Power Crystal
        10938, -- Lesser Magic Essence
        8170, -- Rugged Leather
        8168, -- Jet Black Feather
        8153, -- Wildvine
        8146, -- Wicked Claw
        7972, -- Ichor of Undeath
        7971, -- Black Pearl
        7966, -- Solid Grinding Stone
        7912, -- Solid Stone
        7910, -- Star Ruby
        7909, -- Aquamarine
        7081, -- Breath of Wind
        7080, -- Essence of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7075, -- Core of Earth
        7070, -- Elemental Water
        7069, -- Elemental Air
        7068, -- Elemental Fire
        7067, -- Elemental Earth
        6037, -- Truesilver Bar
        5637, -- Large Fang
        5635, -- Sharp Claw
        5500, -- Iridescent Pearl
        5498, -- Small Lustrous Pearl
        4338, -- Mageweave Cloth
        4306, -- Silk Cloth
        4304, -- Thick Leather
        4234, -- Heavy Leather
        3864, -- Citrine
        3860, -- Mithril Bar
        3859, -- Steel Bar
        3829, -- Frost Oil
        3824, -- Shadow Oil
        3823, -- Lesser Invisibility Potion
        3577, -- Gold Bar
        3575, -- Iron Bar
        3486, -- Heavy Grinding Stone
        3478, -- Coarse Grinding Stone
        3470, -- Rough Grinding Stone
        3466, -- Strong Flux
        3391, -- Elixir of Ogre's Strength
        2880, -- Weak Flux
        2863, -- Coarse Sharpening Stone
        2842, -- Silver Bar
        2841, -- Bronze Bar
        2840, -- Copper Bar
        2838, -- Heavy Stone
        2836, -- Coarse Stone
        2835, -- Rough Stone
        2605, -- Green Dye
        2592, -- Wool Cloth
        2589, -- Linen Cloth
        2459, -- Swiftness Potion
        2321, -- Fine Thread
        2319, -- Medium Leather
        2318, -- Light Leather
        1705, -- Lesser Moonstone
        1529, -- Jade
        1210, -- Shadowgem
        1206, -- Moss Agate
        818, -- Tigerseye
        774, -- Malachite
    },
}
