-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 20:03:32

items.Enchanting = {
    -- https://www.wowhead.com/classic/items?filter=87:194;4:1;0:1
    [1] = { -- Vanilla
        234012, -- Hive Thistle
        234011, -- Qiraji Stalker Venom
        234010, -- Ancient Sandworm Bile
        234008, -- Qiraji Silk
        234007, -- Spiked Silithid Chitin
        234006, -- Monstrous Silithid Chitin
        234005, -- Obsidian Blasting Powder
        234004, -- Obsidian Grinding Stone
        234003, -- Obsidian-Infused Thorium Bar
        20725, -- Nexus Crystal
        18512, -- Larval Acid
        18256, -- Imbued Vial
        17035, -- Stranglethorn Seed
        17034, -- Maple Seed
        16204, -- Illusion Dust
        16203, -- Greater Eternal Essence
        16202, -- Lesser Eternal Essence
        14344, -- Large Brilliant Shard
        14343, -- Small Brilliant Shard
        14047, -- Runecloth
        13926, -- Golden Pearl
        13468, -- Black Lotus
        13467, -- Icecap
        13458, -- Greater Nature Protection Potion
        13180, -- Stratholme Holy Water
        12938, -- Blood of Heroes
        12811, -- Righteous Orb
        12810, -- Enchanted Leather
        12809, -- Guardian Stone
        12808, -- Essence of Undeath
        12803, -- Living Essence
        12753, -- Skin of Shadow
        12735, -- Frayed Abomination Stitching
        12359, -- Thorium Bar
        11754, -- Black Diamond
        11382, -- Blood of the Mountain
        11291, -- Star Wood
        11178, -- Large Radiant Shard
        11177, -- Small Radiant Shard
        11176, -- Dream Dust
        11175, -- Greater Nether Essence
        11174, -- Lesser Nether Essence
        11139, -- Large Glowing Shard
        11138, -- Small Glowing Shard
        11137, -- Vision Dust
        11135, -- Greater Mystic Essence
        11134, -- Lesser Mystic Essence
        11084, -- Large Glimmering Shard
        11083, -- Soul Dust
        11082, -- Greater Astral Essence
        10998, -- Lesser Astral Essence
        10978, -- Small Glimmering Shard
        10940, -- Strange Dust
        10939, -- Greater Magic Essence
        10938, -- Lesser Magic Essence
        9224, -- Elixir of Demonslaying
        8925, -- Crystal Vial
        8838, -- Sungrass
        8831, -- Purple Lotus
        8170, -- Rugged Leather
        8153, -- Wildvine
        8152, -- Flask of Big Mojo
        8151, -- Flask of Mojo
        7972, -- Ichor of Undeath
        7971, -- Black Pearl
        7909, -- Aquamarine
        7392, -- Green Whelp Scale
        7082, -- Essence of Air
        7081, -- Breath of Wind
        7080, -- Essence of Water
        7079, -- Globe of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7075, -- Core of Earth
        7068, -- Elemental Fire
        7067, -- Elemental Earth
        6371, -- Fire Oil
        6370, -- Blackmouth Oil
        6048, -- Shadow Protection Potion
        6037, -- Truesilver Bar
        5637, -- Large Fang
        5500, -- Iridescent Pearl
        4625, -- Firebloom
        4470, -- Simple Wood
        3829, -- Frost Oil
        3819, -- Wintersbite
        3372, -- Leaded Vial
        3371, -- Empty Vial
        3356, -- Kingsblood
        2772, -- Iron Ore
        2459, -- Swiftness Potion
        2452, -- Swiftthistle
        1210, -- Shadowgem
    },
}
