-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 20:03:32

items.Engineering = {
    -- https://www.wowhead.com/classic/items?filter=87:194;5:1;0:1
    [1] = { -- Vanilla
        238737, -- Tinkerbox
        234012, -- Hive Thistle
        234011, -- Qiraji Stalker Venom
        234010, -- Ancient Sandworm Bile
        234009, -- Bolt of Qiraji Silk
        234008, -- Qiraji Silk
        234007, -- Spiked Silithid Chitin
        234005, -- Obsidian Blasting Powder
        234003, -- Obsidian-Infused Thorium Bar
        221021, -- Nightmare Seed
        215430, -- Gnomeregan Fallout
        213383, -- Polished Truesilver Gears
        213381, -- Pile of Tarnished Gears
        213379, -- Hyperconductive Arcano-Filament
        213376, -- Low-Background Truesilver Plates
        213369, -- Faintly Glowing Leather
        22202, -- Small Obsidian Shard
        20881, -- Idol of Strife
        20870, -- Jasper Idol
        20868, -- Lambent Idol
        20725, -- Nexus Crystal
        19774, -- Souldarite
        19726, -- Bloodvine
        18631, -- Truesilver Transformer
        17202, -- Snowball
        17011, -- Lava Core
        17010, -- Fiery Core
        16583, -- Demonic Figurine
        16006, -- Delicate Arcanite Converter
        16000, -- Thorium Tube
        15994, -- Thorium Widget
        15992, -- Dense Blasting Powder
        15407, -- Cured Rugged Hide
        14227, -- Ironweb Spider Silk
        14047, -- Runecloth
        13467, -- Icecap
        12811, -- Righteous Orb
        12810, -- Enchanted Leather
        12808, -- Essence of Undeath
        12804, -- Powerful Mojo
        12803, -- Living Essence
        12800, -- Azerothian Diamond
        12799, -- Large Opal
        12655, -- Enchanted Thorium Bar
        12365, -- Dense Stone
        12364, -- Huge Emerald
        12363, -- Arcane Crystal
        12361, -- Blue Sapphire
        12360, -- Arcanite Bar
        12359, -- Thorium Bar
        11371, -- Dark Iron Bar
        10648, -- Blank Parchment
        10647, -- Engineer's Ink
        10592, -- Catseye Elixir
        10586, -- The Big One
        10561, -- Mithril Casing
        10560, -- Unstable Trigger
        10559, -- Mithril Tube
        10558, -- Gold Power Core
        10546, -- Deadly Scope
        10507, -- Solid Dynamite
        10505, -- Solid Blasting Powder
        10286, -- Heart of the Wild
        10285, -- Shadow Silk
        9262, -- Black Vitriol
        9061, -- Goblin Rocket Fuel
        9060, -- Inlaid Mithril Cylinder
        8170, -- Rugged Leather
        8153, -- Wildvine
        8151, -- Flask of Mojo
        8150, -- Deeprock Salt
        7972, -- Ichor of Undeath
        7912, -- Solid Stone
        7910, -- Star Ruby
        7909, -- Aquamarine
        7191, -- Fused Wiring
        7082, -- Essence of Air
        7080, -- Essence of Water
        7079, -- Globe of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7075, -- Core of Earth
        7069, -- Elemental Air
        7068, -- Elemental Fire
        7067, -- Elemental Earth
        6530, -- Nightcrawlers
        6037, -- Truesilver Bar
        4611, -- Blue Pearl
        4407, -- Accurate Scope
        4404, -- Silver Contact
        4402, -- Small Flame Sac
        4400, -- Heavy Stock
        4399, -- Wooden Stock
        4394, -- Big Iron Bomb
        4389, -- Gyrochronatom
        4387, -- Iron Strut
        4382, -- Bronze Framework
        4377, -- Heavy Blasting Powder
        4375, -- Whirring Bronze Gizmo
        4371, -- Bronze Tube
        4364, -- Coarse Blasting Powder
        4363, -- Copper Modulator
        4361, -- Copper Tube
        4359, -- Handful of Copper Bolts
        4357, -- Rough Blasting Powder
        4339, -- Bolt of Mageweave
        4338, -- Mageweave Cloth
        4337, -- Thick Spider's Silk
        4306, -- Silk Cloth
        4304, -- Thick Leather
        4234, -- Heavy Leather
        3864, -- Citrine
        3860, -- Mithril Bar
        3859, -- Steel Bar
        3829, -- Frost Oil
        3577, -- Gold Bar
        3575, -- Iron Bar
        2880, -- Weak Flux
        2842, -- Silver Bar
        2841, -- Bronze Bar
        2840, -- Copper Bar
        2838, -- Heavy Stone
        2836, -- Coarse Stone
        2835, -- Rough Stone
        2592, -- Wool Cloth
        2589, -- Linen Cloth
        2319, -- Medium Leather
        2318, -- Light Leather
        1705, -- Lesser Moonstone
        1529, -- Jade
        1210, -- Shadowgem
        1206, -- Moss Agate
        818, -- Tigerseye
        814, -- Flask of Oil
        774, -- Malachite
        159, -- Refreshing Spring Water
    },
}
