-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 20:03:34

items.Herbalism = {
    -- https://www.wowhead.com/classic/items?filter=70:194;1:1;0:1
    [1] = { -- Vanilla
        234012, -- Hive Thistle
        219514, -- Moonroot
        219454, -- Star Lotus
        219444, -- Dreamroot
        219399, -- Nightmare Moss
        19726, -- Bloodvine
        13468, -- Black Lotus
        13467, -- Icecap
        13466, -- Plaguebloom
        13465, -- Mountain Silversage
        13464, -- Golden Sansam
        13463, -- Dreamfoil
        11514, -- Fel Creep
        8846, -- Gromsblood
        8845, -- Ghost Mushroom
        8839, -- Blindweed
        8838, -- Sungrass
        8836, -- Arthas' Tears
        8831, -- Purple Lotus
        8153, -- Wildvine
        7070, -- Elemental Water
        7068, -- Elemental Fire
        7067, -- Elemental Earth
        5056, -- Root Sample
        4625, -- Firebloom
        3821, -- Goldthorn
        3820, -- Stranglekelp
        3819, -- Wintersbite
        3818, -- Fadeleaf
        3369, -- Grave Moss
        3358, -- Khadgar's Whisker
        3357, -- Liferoot
        3356, -- Kingsblood
        3355, -- Wild Steelbloom
        2453, -- Bruiseweed
        2452, -- Swiftthistle
        2450, -- Briarthorn
        2449, -- Earthroot
        2447, -- Peacebloom
        785, -- Mageroyal
        765, -- Silverleaf
    },
}
