-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 20:03:37

items.Mining = {
    -- https://www.wowhead.com/classic/items?filter=87:194;9:1;0:1
    [1] = { -- Vanilla
        22203, -- Large Obsidian Shard
        18567, -- Elemental Flux
        18562, -- Elementium Ore
        17010, -- Fiery Core
        12655, -- Enchanted Thorium Bar
        12360, -- Arcanite Bar
        11370, -- Dark Iron Ore
        10620, -- Thorium Ore
        7911, -- Truesilver Ore
        3858, -- Mithril Ore
        3857, -- Coal
        3576, -- Tin Bar
        3575, -- Iron Bar
        2840, -- Copper Bar
        2776, -- Gold Ore
        2775, -- Silver Ore
        2772, -- Iron Ore
        2771, -- Tin Ore
        2770, -- Copper Ore
    },
}
