-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 21:11:40

items.Alchemy = {
    -- https://www.wowhead.com/forever/items?filter=87:194;1:1;0:1
    [1] = { -- Vanilla
        273125, -- Lich's Index Finger
        251291, -- Heavy Thorium Bar
        249424, -- Rosecap
        249399, -- Frilled Lichen
        249391, -- Pyrite
        249274, -- Stranglevine
        248823, -- Marefoil
        248822, -- Death Lotus
        248821, -- Demonsage
        248819, -- Fel Crystal
        234012, -- Hive Thistle
        215430, -- Gnomeregan Fallout
        213371, -- Crate of Tainted Gniodine Solution
        19943, -- Massive Mojo
        18256, -- Imbued Vial
        16203, -- Greater Eternal Essence
        13513, -- Flask of Chromatic Resistance
        13512, -- Flask of Supreme Power
        13511, -- Flask of Distilled Wisdom
        13510, -- Flask of the Titans
        13468, -- Black Lotus
        13467, -- Icecap
        13466, -- Plaguebloom
        13465, -- Mountain Silversage
        13464, -- Golden Sansam
        13463, -- Dreamfoil
        13423, -- Stonescale Oil
        13422, -- Stonescale Eel
        12938, -- Blood of Heroes
        12808, -- Essence of Undeath
        12804, -- Powerful Mojo
        12803, -- Living Essence
        12363, -- Arcane Crystal
        12359, -- Thorium Bar
        11176, -- Dream Dust
        11083, -- Soul Dust
        10620, -- Thorium Ore
        10286, -- Heart of the Wild
        9262, -- Black Vitriol
        9260, -- Volatile Rum
        8925, -- Crystal Vial
        8846, -- Gromsblood
        8845, -- Ghost Mushroom
        8839, -- Blindweed
        8838, -- Sungrass
        8836, -- Arthas' Tears
        8831, -- Purple Lotus
        8153, -- Wildvine
        7972, -- Ichor of Undeath
        7082, -- Essence of Air
        7080, -- Essence of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7070, -- Elemental Water
        7068, -- Elemental Fire
        7067, -- Elemental Earth
        6522, -- Deviate Fish
        6371, -- Fire Oil
        6370, -- Blackmouth Oil
        6359, -- Firefin Snapper
        6358, -- Oily Blackmouth
        5637, -- Large Fang
        5635, -- Sharp Claw
        4625, -- Firebloom
        4402, -- Small Flame Sac
        4342, -- Purple Dye
        3860, -- Mithril Bar
        3858, -- Mithril Ore
        3824, -- Shadow Oil
        3821, -- Goldthorn
        3820, -- Stranglekelp
        3819, -- Wintersbite
        3818, -- Fadeleaf
        3575, -- Iron Bar
        3372, -- Leaded Vial
        3371, -- Empty Vial
        3369, -- Grave Moss
        3358, -- Khadgar's Whisker
        3357, -- Liferoot
        3356, -- Kingsblood
        3355, -- Wild Steelbloom
        2456, -- Minor Rejuvenation Potion
        2453, -- Bruiseweed
        2452, -- Swiftthistle
        2450, -- Briarthorn
        2449, -- Earthroot
        2447, -- Peacebloom
        1288, -- Large Venom Sac
        785, -- Mageroyal
        765, -- Silverleaf
        730, -- Murloc Eye
    },
}
