-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 21:11:42

items.Cooking = {
    -- https://www.wowhead.com/forever/items?filter=87:194;3:1;0:1
    [1] = { -- Vanilla
        272941, -- Thick Logs
        252948, -- Cleansed Felbloom
        251524, -- Whimsyfin
        249796, -- Hyjal Berries
        239017, -- Exquisite Spices
        239016, -- Holy Salts
        227813, -- Drinkable Stratholme Holy Water
        21153, -- Raw Greater Sagefish
        21071, -- Raw Sagefish
        21024, -- Chimaerok Tenderloin
        20424, -- Sandworm Meat
        18255, -- Runn Tum Tuber
        17196, -- Holiday Spirits
        17194, -- Holiday Spices
        13893, -- Large Raw Mightfish
        13890, -- Raw Plated Armorfish
        13889, -- Raw Whitescale Salmon
        13888, -- Darkclaw Lobster
        13760, -- Raw Sunscale Salmon
        13759, -- Raw Nightfin Snapper
        13758, -- Raw Redgill
        13756, -- Raw Summer Bass
        13755, -- Raw Winter Squid
        13754, -- Raw Glossy Mightfish
        13465, -- Mountain Silversage
        12223, -- Meaty Bat Wing
        12208, -- Tender Wolf Meat
        12207, -- Giant Egg
        12206, -- Tender Crab Meat
        12205, -- White Spider Meat
        12204, -- Heavy Kodo Meat
        12203, -- Red Wolf Meat
        12202, -- Tiger Meat
        12184, -- Raptor Flesh
        12037, -- Mystery Meat
        11291, -- Star Wood
        10284, -- Simple Flour
        9061, -- Goblin Rocket Fuel
        8959, -- Raw Spinefin Halibut
        8838, -- Sungrass
        8766, -- Morning Glory Dew
        8365, -- Raw Mithril Head Trout
        8150, -- Deeprock Salt
        8146, -- Wicked Claw
        7974, -- Zesty Clam Meat
        6889, -- Small Egg
        6522, -- Deviate Fish
        6362, -- Raw Rockscale Cod
        6361, -- Raw Rainbow Fin Albacore
        6317, -- Raw Loch Frenzy
        6308, -- Raw Bristle Whisker Catfish
        6303, -- Raw Slitherskin Mackerel
        6291, -- Raw Brilliant Smallfish
        6289, -- Raw Longjaw Mud Snapper
        5637, -- Large Fang
        5504, -- Tangy Clam Meat
        5503, -- Clam Meat
        5471, -- Stag Meat
        5470, -- Thunder Lizard Tail
        5469, -- Strider Meat
        5468, -- Soft Frenzy Flesh
        5467, -- Kodo Meat
        5466, -- Scorpid Stinger
        5465, -- Small Spider Leg
        5051, -- Dig Rat
        4655, -- Giant Clam Meat
        4603, -- Raw Spotted Yellowtail
        4536, -- Shiny Red Apple
        4470, -- Simple Wood
        4402, -- Small Flame Sac
        3821, -- Goldthorn
        3818, -- Fadeleaf
        3731, -- Lion Meat
        3730, -- Big Bear Meat
        3713, -- Soothing Spices
        3712, -- Turtle Meat
        3685, -- Raptor Egg
        3667, -- Tender Crocolisk Meat
        3404, -- Buzzard Wing
        3357, -- Liferoot
        3174, -- Spider Ichor
        3173, -- Bear Meat
        3172, -- Boar Intestines
        2924, -- Crocolisk Meat
        2894, -- Rhapsody Malt
        2886, -- Crag Boar Rib
        2692, -- Hot Spices
        2678, -- Mild Spices
        2677, -- Boar Ribs
        2675, -- Crawler Claw
        2674, -- Crawler Meat
        2673, -- Coyote Meat
        2672, -- Stringy Wolf Meat
        2596, -- Skin of Dwarven Stout
        2452, -- Swiftthistle
        2447, -- Peacebloom
        2251, -- Gooey Spider Leg
        1708, -- Sweet Nectar
        1645, -- Moonberry Juice
        1475, -- Small Venom Sac
        1468, -- Murloc Fin
        1205, -- Melon Juice
        1179, -- Ice Cold Milk
        1081, -- Crisp Spider Meat
        1080, -- Tough Condor Meat
        1015, -- Lean Wolf Flank
        785, -- Mageroyal
        769, -- Chunk of Boar Meat
        731, -- Goretusk Snout
        730, -- Murloc Eye
        729, -- Stringy Vulture Meat
        723, -- Goretusk Liver
        159, -- Refreshing Spring Water
    },
}
