-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 21:11:46

items.Leatherworking = {
    -- https://www.wowhead.com/forever/items?filter=87:194;8:1;0:1
    [1] = { -- Vanilla
        274030, -- Malleable Essence of Nature
        273130, -- Undeath Engine
        249429, -- Pristine Scale
        249428, -- Pristine Hide
        249427, -- Pristine Leather
        249410, -- Sulfuric Acid
        249409, -- Cerulean Dye
        248825, -- Fel Leather
        248824, -- Fel Hide
        213379, -- Hyperconductive Arcano-Filament
        213376, -- Low-Background Truesilver Plates
        213370, -- Irradiated Leather Scraps
        213369, -- Faintly Glowing Leather
        22682, -- Frozen Rune
        20501, -- Heavy Silithid Carapace
        20500, -- Light Silithid Carapace
        20498, -- Silithid Chitin
        20381, -- Dreamscale
        19768, -- Primal Tiger Leather
        19767, -- Primal Bat Leather
        19726, -- Bloodvine
        18512, -- Larval Acid
        18251, -- Core Armor Kit
        18240, -- Ogre Tannin
        17012, -- Core Leather
        17011, -- Lava Core
        17010, -- Fiery Core
        15564, -- Rugged Armor Kit
        15423, -- Chimera Leather
        15422, -- Frostsaber Leather
        15420, -- Ironfeather
        15419, -- Warbear Leather
        15417, -- Devilsaur Leather
        15416, -- Black Dragonscale
        15415, -- Blue Dragonscale
        15414, -- Red Dragonscale
        15412, -- Green Dragonscale
        15410, -- Scale of Onyxia
        15409, -- Refined Deeprock Salt
        15408, -- Heavy Scorpid Scale
        15407, -- Cured Rugged Hide
        14342, -- Mooncloth
        14341, -- Rune Thread
        14256, -- Felcloth
        14227, -- Ironweb Spider Silk
        14048, -- Bolt of Runecloth
        14047, -- Runecloth
        13444, -- Major Mana Potion
        13423, -- Stonescale Oil
        12938, -- Blood of Heroes
        12811, -- Righteous Orb
        12810, -- Enchanted Leather
        12809, -- Guardian Stone
        12804, -- Powerful Mojo
        12803, -- Living Essence
        12800, -- Azerothian Diamond
        12799, -- Large Opal
        12753, -- Skin of Shadow
        12607, -- Brilliant Chromatic Scale
        12364, -- Huge Emerald
        12361, -- Blue Sapphire
        11754, -- Black Diamond
        11176, -- Dream Dust
        11137, -- Vision Dust
        11083, -- Soul Dust
        10940, -- Strange Dust
        9206, -- Elixir of Greater Strength
        8951, -- Elixir of Defense
        8949, -- Elixir of Agility
        8368, -- Thick Wolfhide
        8343, -- Heavy Silken Thread
        8173, -- Thick Armor Kit
        8172, -- Cured Thick Hide
        8171, -- Rugged Hide
        8170, -- Rugged Leather
        8169, -- Thick Hide
        8168, -- Jet Black Feather
        8167, -- Turtle Scale
        8165, -- Worn Dragonscale
        8154, -- Scorpid Scale
        8153, -- Wildvine
        8152, -- Flask of Big Mojo
        8151, -- Flask of Mojo
        8150, -- Deeprock Salt
        8146, -- Wicked Claw
        7971, -- Black Pearl
        7428, -- Shadowcat Hide
        7392, -- Green Whelp Scale
        7287, -- Red Whelp Scale
        7286, -- Black Whelp Scale
        7082, -- Essence of Air
        7081, -- Breath of Wind
        7080, -- Essence of Water
        7079, -- Globe of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7075, -- Core of Earth
        7071, -- Iron Buckle
        7070, -- Elemental Water
        7069, -- Elemental Air
        7067, -- Elemental Earth
        6662, -- Elixir of Giant Growth
        6471, -- Perfect Deviate Scale
        6470, -- Deviate Scale
        6261, -- Orange Dye
        6260, -- Blue Dye
        5785, -- Thick Murloc Scale
        5784, -- Slimy Murloc Scale
        5637, -- Large Fang
        5633, -- Great Rage Potion
        5500, -- Iridescent Pearl
        5498, -- Small Lustrous Pearl
        5373, -- Lucky Charm
        5116, -- Long Tail Feather
        5082, -- Thin Kodo Leather
        4470, -- Simple Wood
        4461, -- Raptor Hide
        4340, -- Gray Dye
        4338, -- Mageweave Cloth
        4337, -- Thick Spider's Silk
        4305, -- Bolt of Silk Cloth
        4304, -- Thick Leather
        4291, -- Silken Thread
        4289, -- Salt
        4265, -- Heavy Armor Kit
        4236, -- Cured Heavy Hide
        4235, -- Heavy Hide
        4234, -- Heavy Leather
        4233, -- Cured Medium Hide
        4232, -- Medium Hide
        4231, -- Cured Light Hide
        4096, -- Coarse Gorilla Hair
        3864, -- Citrine
        3827, -- Mana Potion
        3824, -- Shadow Oil
        3391, -- Elixir of Ogre Strength
        3390, -- Elixir of Lesser Agility
        3389, -- Elixir of Lesser Defense
        3385, -- Lesser Mana Potion
        3383, -- Elixir of Wisdom
        3356, -- Kingsblood
        3182, -- Spider's Silk
        2997, -- Bolt of Woolen Cloth
        2934, -- Ruined Leather Scraps
        2840, -- Copper Bar
        2605, -- Green Dye
        2459, -- Swiftness Potion
        2458, -- Elixir of Minor Fortitude
        2457, -- Elixir of Minor Agility
        2455, -- Minor Mana Potion
        2454, -- Elixir of Minor Strength
        2325, -- Black Dye
        2324, -- Bleach
        2321, -- Fine Thread
        2320, -- Coarse Thread
        2319, -- Medium Leather
        2318, -- Light Leather
        2313, -- Medium Armor Kit
        1529, -- Jade
        1210, -- Shadowgem
        1206, -- Moss Agate
        783, -- Light Hide
    },
}
