-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 21:11:48

items.Mining = {
    -- https://www.wowhead.com/forever/items?filter=87:194;9:1;0:1
    [1] = { -- Vanilla
        249426, -- Pitchblende
        248815, -- Heavy Thorium Ore
        22203, -- Large Obsidian Shard
        18567, -- Elemental Flux
        18562, -- Elementium Ore
        17010, -- Fiery Core
        12655, -- Enchanted Thorium Bar
        12365, -- Dense Stone
        12360, -- Arcanite Bar
        12359, -- Thorium Bar
        11370, -- Dark Iron Ore
        10620, -- Thorium Ore
        7911, -- Truesilver Ore
        6037, -- Truesilver Bar
        3858, -- Mithril Ore
        3857, -- Coal
        3576, -- Tin Bar
        3575, -- Iron Bar
        2842, -- Silver Bar
        2840, -- Copper Bar
        2838, -- Heavy Stone
        2835, -- Rough Stone
        2776, -- Gold Ore
        2775, -- Silver Ore
        2772, -- Iron Ore
        2771, -- Tin Ore
        2770, -- Copper Ore
    },
}
