-- Generated by merge_tables.py

items.Mining = {
    -- https://www.wowhead.com/forever/items?filter=86:194;9:1;0:1
    -- https://www.wowhead.com/forever/items?filter=87:194;9:1;0:1
    -- https://www.wowhead.com/forever/items?filter=73:194;1:1;0:1
    [1] = { -- Vanilla
        279960, -- Lodestone
        279952, -- Molten Foundry
        279948, -- Rock Garden
        251291, -- Heavy Thorium Bar
        249726, -- Azerothium Bar
        249426, -- Pitchblende
        248815, -- Heavy Thorium Ore
        219515, -- Greater Moonstone
        219486, -- Starsilver Ore
        219445, -- Fool's Gold Dust
        219401, -- Cold Iron Ore
        22203, -- Large Obsidian Shard
        22202, -- Small Obsidian Shard
        19774, -- Souldarite
        18567, -- Elemental Flux
        18562, -- Elementium Ore
        17771, -- Elementium Bar
        17056, -- Light Feather
        17010, -- Fiery Core
        12800, -- Azerothian Diamond
        12799, -- Large Opal
        12655, -- Enchanted Thorium Bar
        12365, -- Dense Stone
        12364, -- Huge Emerald
        12363, -- Arcane Crystal
        12361, -- Blue Sapphire
        12360, -- Arcanite Bar
        12359, -- Thorium Bar
        12223, -- Meaty Bat Wing
        11754, -- Black Diamond
        11513, -- Tainted Vitriol
        11382, -- Blood of the Mountain
        11371, -- Dark Iron Bar
        11370, -- Dark Iron Ore
        10620, -- Thorium Ore
        9262, -- Black Vitriol
        7912, -- Solid Stone
        7911, -- Truesilver Ore
        7910, -- Star Ruby
        7909, -- Aquamarine
        7101, -- Bug Eye
        7100, -- Sticky Ichor
        7098, -- Splintered Tusk
        7096, -- Plucked Feather
        7076, -- Essence of Earth
        7074, -- Chipped Claw
        7073, -- Broken Fang
        7068, -- Elemental Fire
        7067, -- Elemental Earth
        6303, -- Raw Slitherskin Mackerel
        6037, -- Truesilver Bar
        5833, -- Indurium Ore
        5364, -- Dry Salt Lick
        5362, -- Chew Toy
        5075, -- Blood Shard
        4874, -- Clean Fishbones
        4873, -- Dry Hardened Barnacle
        4872, -- Dry Scorpid Eye
        4870, -- Canvas Scraps
        4867, -- Broken Scorpid Leg
        4865, -- Ruined Pelt
        4776, -- Ruffled Feather
        4775, -- Cracked Bill
        4757, -- Cracked Egg Shells
        4702, -- Prospector's Pick
        4604, -- Forest Mushroom Cap
        4536, -- Shiny Red Apple
        4278, -- Lesser Bloodstone Ore
        3864, -- Citrine
        3860, -- Mithril Bar
        3859, -- Steel Bar
        3858, -- Mithril Ore
        3857, -- Coal
        3577, -- Gold Bar
        3576, -- Tin Bar
        3575, -- Iron Bar
        3340, -- Incendicite Ore
        3299, -- Fractured Canine
        3171, -- Broken Boar Tusk
        3170, -- Large Bear Tooth
        3169, -- Chipped Bear Tooth
        2842, -- Silver Bar
        2841, -- Bronze Bar
        2840, -- Copper Bar
        2838, -- Heavy Stone
        2836, -- Coarse Stone
        2835, -- Rough Stone
        2798, -- Rethban Ore
        2776, -- Gold Ore
        2775, -- Silver Ore
        2772, -- Iron Ore
        2771, -- Tin Ore
        2770, -- Copper Ore
        2672, -- Stringy Wolf Meat
        2590, -- Forest Spider Webbing
        2589, -- Linen Cloth
        2070, -- Darnassian Bleu
        1705, -- Lesser Moonstone
        1529, -- Jade
        1476, -- Snapped Spider Limb
        1210, -- Shadowgem
        1206, -- Moss Agate
        1181, -- Scroll of Spirit
        818, -- Tigerseye
        779, -- Shiny Seashell
        774, -- Malachite
        771, -- Chipped Boar Tusk
        755, -- Melted Candle
        159, -- Refreshing Spring Water
        118, -- Minor Healing Potion
        117, -- Tough Jerky
    },
}
