-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 21:11:48

items.Mining = {
    -- https://www.wowhead.com/forever/items?filter=86:194;9:1;0:1
    [1] = { -- Vanilla
        279960, -- Lodestone
        279952, -- Molten Foundry
        279948, -- Rock Garden
        251291, -- Heavy Thorium Bar
        249726, -- Azerothium Bar
        17771, -- Elementium Bar
        12359, -- Thorium Bar
        11371, -- Dark Iron Bar
        6037, -- Truesilver Bar
        3860, -- Mithril Bar
        3859, -- Steel Bar
        3577, -- Gold Bar
        3576, -- Tin Bar
        3575, -- Iron Bar
        2842, -- Silver Bar
        2841, -- Bronze Bar
        2840, -- Copper Bar
    },
}
