-- Generated by wowhead_to_item_tables.py
-- Generated at 2026-10-01 21:11:50

items.Tailoring = {
    -- https://www.wowhead.com/forever/items?filter=87:194;10:1;0:1
    [1] = { -- Vanilla
        274030, -- Malleable Essence of Nature
        273131, -- Bottled Screams
        249431, -- Viridian Dye
        249430, -- Magenta Dye
        249429, -- Pristine Scale
        249428, -- Pristine Hide
        249427, -- Pristine Leather
        249409, -- Cerulean Dye
        249391, -- Pyrite
        213379, -- Hyperconductive Arcano-Filament
        213378, -- Unstable Microfilament
        213369, -- Faintly Glowing Leather
        22682, -- Frozen Rune
        20520, -- Dark Rune
        20381, -- Dreamscale
        19726, -- Bloodvine
        18240, -- Ogre Tannin
        17012, -- Core Leather
        17011, -- Lava Core
        17010, -- Fiery Core
        16203, -- Greater Eternal Essence
        15407, -- Cured Rugged Hide
        14344, -- Large Brilliant Shard
        14343, -- Small Brilliant Shard
        14342, -- Mooncloth
        14341, -- Rune Thread
        14256, -- Felcloth
        14227, -- Ironweb Spider Silk
        14048, -- Bolt of Runecloth
        14047, -- Runecloth
        13926, -- Golden Pearl
        13468, -- Black Lotus
        12938, -- Blood of Heroes
        12811, -- Righteous Orb
        12810, -- Enchanted Leather
        12809, -- Guardian Stone
        12808, -- Essence of Undeath
        12804, -- Powerful Mojo
        12803, -- Living Essence
        12800, -- Azerothian Diamond
        12662, -- Demonic Rune
        12364, -- Huge Emerald
        12360, -- Arcanite Bar
        11178, -- Large Radiant Shard
        11176, -- Dream Dust
        11175, -- Greater Nether Essence
        11137, -- Vision Dust
        11134, -- Lesser Mystic Essence
        11082, -- Greater Astral Essence
        11040, -- Morrowgrain
        10290, -- Pink Dye
        10286, -- Heart of the Wild
        10285, -- Shadow Silk
        9210, -- Ghost Dye
        8831, -- Purple Lotus
        8343, -- Heavy Silken Thread
        8170, -- Rugged Leather
        8153, -- Wildvine
        7972, -- Ichor of Undeath
        7971, -- Black Pearl
        7910, -- Star Ruby
        7082, -- Essence of Air
        7080, -- Essence of Water
        7079, -- Globe of Water
        7078, -- Essence of Fire
        7077, -- Heart of Fire
        7076, -- Essence of Earth
        7072, -- Naga Scale
        7071, -- Iron Buckle
        7070, -- Elemental Water
        7069, -- Elemental Air
        7068, -- Elemental Fire
        7067, -- Elemental Earth
        6371, -- Fire Oil
        6261, -- Orange Dye
        6260, -- Blue Dye
        6048, -- Shadow Protection Potion
        6037, -- Truesilver Bar
        5500, -- Iridescent Pearl
        5498, -- Small Lustrous Pearl
        4625, -- Firebloom
        4589, -- Long Elegant Feather
        4470, -- Simple Wood
        4342, -- Purple Dye
        4341, -- Yellow Dye
        4340, -- Gray Dye
        4339, -- Bolt of Mageweave
        4338, -- Mageweave Cloth
        4337, -- Thick Spider's Silk
        4306, -- Silk Cloth
        4305, -- Bolt of Silk Cloth
        4304, -- Thick Leather
        4291, -- Silken Thread
        4234, -- Heavy Leather
        3864, -- Citrine
        3829, -- Frost Oil
        3827, -- Mana Potion
        3824, -- Shadow Oil
        3577, -- Gold Bar
        3383, -- Elixir of Wisdom
        3182, -- Spider's Silk
        2997, -- Bolt of Woolen Cloth
        2996, -- Bolt of Linen Cloth
        2842, -- Silver Bar
        2605, -- Green Dye
        2604, -- Red Dye
        2592, -- Wool Cloth
        2589, -- Linen Cloth
        2455, -- Minor Mana Potion
        2325, -- Black Dye
        2324, -- Bleach
        2321, -- Fine Thread
        2320, -- Coarse Thread
        2319, -- Medium Leather
        2318, -- Light Leather
        1529, -- Jade
        1210, -- Shadowgem
        929, -- Healing Potion
        814, -- Flask of Oil
        118, -- Minor Healing Potion
    },
}
